### ISSUE TITLE
request_init_invocation enters infinite loop on request ID conflict

### ISSUE THREAD

**Issue by jhenstridge** [flatpak/xdg-desktop-portal#100]
In `request_init_invocation()`, the following code is used to allocate a random unique request ID:

    r = g_random_int ();
    do
      {
        g_free (id);
        id = g_strdup_printf ("/org/freedesktop/portal/desktop/request/%u", r);
      }
    while (g_hash_table_lookup (requests, id) != NULL);

Since the random number is only chosen once, if the ID conflicts in one iteration of the loop, it will always conflict.

Presumably a new random number should be chosen for each iteration of the loop.

**Comment by mariospr** [comment]
I think you're right. Could you prepare a PR?

**Comment by matthiasclasen** [comment]
Oops :-)

Yes, please
