### ISSUE TITLE
No such interface “org.freedesktop.portal.Background” with PikaBackup Flatpak Scheduled Backups

### ISSUE THREAD

**Issue by moshhh** [flatpak/xdg-desktop-portal#1014]
Hello, 

Having an issue with PikaBackup's background process. Using the flatpak. Running linux mint 21.1; with the relevant packages being ubuntu repos, there seems to be no issue on Ubuntu's tracker. Reported on launchpad.

xdg-desktop-portal-gtk - 1.14.0-1build1
flatpak - 1.12.7-1

Output of `flatpak run -v` when trying to configure scheduled backups

```
pika-backup:2): pika-backup-WARNING **: 10:21:10.646: src/ui/utils.rs:134:0: Background portal response: Zbus(MethodError(OwnedErrorName(ErrorName(Str(Owned("org.freedesktop.DBus.Error.UnknownMethod")))), Some("No such interface “org.freedesktop.portal.Background” on object at path /org/freedesktop/portal/desktop"), Msg { type: Error, sender: UniqueName(Str(Borrowed(":1.74"))), reply-serial: 5, body: Signature("s") }))

(pika-backup:2): pika-backup-WARNING **: 10:21:10.646: src/ui/utils.rs:377:0: Displaying error:
  Request to run in background failed
  The system does not support running Pika Backup in the background. Scheduled backup functionality and continuing backups in the background will not be available. This is either a malfunction, misconfi
…
issue in your distribution issue tracker.

ZBus Error: org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Background” on object at path /org/freedesktop/portal/desktop
```

**Comment by smcv** [comment]
> No such interface “org.freedesktop.portal.Background”

If an application requires o.fd.portal.Background, then it needs xdg-desktop-portal 1.16.0 or later.

There is nothing that Flatpak can do to get a newer xdg-desktop-portal; it's a component that runs outside the Flatpak sandbox, like Flatpak itself, so getting a newer version is between you and your distribution.

**Comment by ways** [comment]
So PikaBackup is no longer compatible with Ubuntu 22.04, Ubuntu 22.10, Fedora 37, Debian 11, CentOS (all)?

**Comment by smcv** [comment]
> So PikaBackup is no longer compatible with Ubuntu 22.10, Fedora 37, Debian 11, CentOS (all) and earlier releases?

If it has a hard requirement on new functionality (I don't know whether it does), then yes. In the absence of a time machine, new features don't exist in distributions that are older than those new features, unless the distribution's policy would allow adding them in later.

Some distributions provide a way to get newer versions of xdg-desktop-portal than the one they originally shipped with; for example, [Debian 11 backports](https://backports.debian.org/) include a backport of xdg-desktop-portal 1.16.0.

**Comment by moshhh** [comment]
It was a requirement for automatic backups. Mint was  on 1.14 but the latest release should fix this issue.

**Comment by taltamir** [comment]
> It was a requirement for automatic backups. Mint was on 1.14 but the latest release should fix this issue.

latest mint version is still on v1.14

**Comment by ways** [comment]
> So PikaBackup is no longer compatible with Ubuntu 22.10, Fedora 37, Debian 11, CentOS (all) and earlier releases?

Never mind this, I was just missing a backend. Pika works fine. Ref. https://wiki.archlinux.org/title/XDG_Desktop_Portal

**Comment by taltamir** [comment]
> > So PikaBackup is no longer compatible with Ubuntu 22.10, Fedora 37, Debian 11, CentOS (all) and earlier releases?
> 
> Never mind this, I was just missing a backend. Pika works fine. Ref. https://wiki.archlinux.org/title/XDG_Desktop_Portal

What do you mean?
As far as I can tell you were right the first time that various OS do not work.
You are now linking an arch linux page where you can update this flatpack component for arch linux.

But if you are using ubuntu LTS or debian LTS, then it does not work.

You need to manually import this specific package from ubuntu lunar (latest version of ubuntu) into LTS instead.
Possibly also other related packages too depending on how they are interlinked.
