### ISSUE TITLE
Can't eject removable media

### ISSUE THREAD

**Issue by bellegarde-c** [flatpak/xdg-desktop-portal#1019]
Since GNOME 44/Silverblue 38, when opening a file on a removable media and then closing the associated application, I am unable to eject/umount it.

The only solution is to kill xdg-portal-document and then eject again with nautilus.

**Comment by xioren** [comment]
This is a known bug that probably will not get fixed. I don't recommend using any Flatpak that uses xdg-document-portal to access files.

**Comment by bellegarde-c** [comment]
crazy I did not find 689 while reporting this: duplicated
