### ISSUE TITLE
Alarm Notifications (with Task Store)

### ISSUE THREAD

**Issue by Mikenux** [flatpak/xdg-desktop-portal#1025]
## Goal

The goal is to register the properties of alarms in order to identify them. Such identification would make it possible to:
- Have an "alarm" notification type that can be toggled on and off;
- Show a standard notification with standard actions;
- Display alarms in a standard widget.

## Required
- A Task Store to register any "task", namely alarms in this case. Registered "tasks" are categorized by app.

## App Registration
- An app with alarms is registered when it is installed or updated. The fact that the app uses alarms must be detectable. Also, this registration is updated when the app is updated (if there is a change in what it supports).
- The app communicates whether it supports sound playback, vibration patterns, and/or LED patterns. If it doesn't support one of these, the system should ideally be able to play a default sound, vibration pattern, or LED pattern. This way, when in a specific feedback mode (i.e. sound, vibration, silent, or do not disturb), the system sends a signal to tell the app what can be played.
- The app communicates which properties it supports (see Alarm Registration below).

## General
- An app with alarms is launched in the background (i.e. without displaying a window), either at the opening of the user session and if there are alarms registered for the day, or by waking it up at alarm time or a bit earlier if needed.
- When an alarm is added, it is automatically enabled. If an alarm is disabled, it is unregistered. To be registered again, it must be re-enabled.

## Permissions
- When an alarm is enabled and must ring on the day of its addition, the app is allowed to run in the background. Otherwise, it can't.
- Permission to play a sound, vibration pattern or LED pattern is given to the app only at the time of the alarm or at the time the alarm repeats.

## Alarm Widget

An alarm widget only displays active alarms (i.e. those that have been enabled) and can open the app with the alarms. The widget can have an action to cancel (disable) an alarm.

## Portal and App User Interfaces

The portal UI is a standard dialog for adding and updating alarms.

Deleting an alarm can be done using a delete button in the standard dialog or in the app UI. If the delete button is in the app UI, it triggers the display of a standard delete confirmation dialog. The minimum number of relevant properties appear in this dialog to indicate to the user which alarm is deleted.

Alarms can be enabled and disabled, but this is usually done in the app UI. In this case, the ideal would be to use a confirmation dialog box (presenting the name of the alarm and/or the ringing duration). To enable and disable several alarms, the app could have an "Apply" action which triggers a dialog box listing all the alarms to be enabled and disabled.

## Alarm Registration

The properties for registering an alarm are:
- Name. Optional.
- Description. Optional.
- Dates or Days.
- Ringing Time. The time at which the alarm must ring (HH:mm).
- Repeat Time. An interval time in minutes to repeat the alarm. If this field is set to "0" or left blank, a system default value is used.
- Sensitivity. Sets the sensitivity level of an alarm's information (see https://gitlab.freedesktop.org/xdg/xdg-specs/-/issues/103). This defines how an alarm notification must be displayed on the lock screen. Three values:
	- public. The alarm notification is displayed with its complete content.
	- private. The notification is only displayed with the alarm name and ringing time.
	- secret. Show notification only with ringing time.

## Notification Actions

An alarm notification has the following standard actions:
- Stop. Triggering this action stops the alarm and the corresponding app if it has no other alarms to ring for the day.
- Action to repeat the alarm, depending on the Repeat Time setting. Examples: "Repeat/Later (XX min)", "Ring/Repeat in XX min", "XX min Later". Triggering it stops the ringing and prevents the app from using sound, vibration, or LED until the alarm rings again.

## Notification Importance

If an alarm is added and enabled to ring, it is certainly important for the user.

## Questions
- Portal UI: Should the portal dialog be styled according to desktop environment or application UI style?
- Registration: Are there other alarm properties to add?
- A "Later" Notification Action: Is it worth delaying an alarm longer than the repeat time (i.e. ringing later) while keeping the original start time of the the alarm?
- Migration: What about migrating alarms for apps that weren't using the portal before? The user would have to review each item, but it might be cumbersome if there are a lot of alarms.

**Comment by Mikenux** [comment]
Other issues with the Task Store: https://github.com/flatpak/xdg-desktop-portal/issues/1026, https://github.com/flatpak/xdg-desktop-portal/issues/1027

**Comment by GeorgesStavracas** [comment]
Closing with the same reasoning as https://github.com/flatpak/xdg-desktop-portal/issues/1026#issuecomment-1664392785

**Comment by Mikenux** [comment]
Unlike https://github.com/flatpak/xdg-desktop-portal/issues/983, this one offers to log alarms instead of using a freely usable class. The user interface is intended to add an alarm reliably: a user can be sure that the alarm they are adding is the one that will be used.

It will also prevent an app from using an alarm notification (if it can send a notification freely) if the device is configured to disturb the user with alarms. Someone might argue that the bug is in the app or that the user can remove the problematic app, but keep in mind that the app will likely have been presented to the user as sandboxed and using a portal that controls things.

So unless I've completely misunderstood what's being offered in https://github.com/flatpak/xdg-desktop-portal/issues/983 or you have another way to handle this, this one seems to me to be of value for the reasons mentioned.

**Comment by GeorgesStavracas** [comment]
I've closed this issue under the premise that app authors haven't requested this functionality, and that nobody is planning on working on this, so this is considered out of scope for now. This issue can be reopened if app developers ask for the specific functionality you sketched here.

**Comment by Mikenux** [comment]
(general comment to anyone who saw this proposal)

I added new things to the proposal. They can be viewed using the “edit” button. The issue has been renamed to better match the proposal.
