### ISSUE TITLE
Scheduled Task Notifications

### ISSUE THREAD

**Issue by Mikenux** [flatpak/xdg-desktop-portal#1027]
## Goal

The goal is to register the properties of different scheduled tasks that apps can perform in order to identify them. Such identification would make it possible to:
- Have a notification type that can be toggled on and off for app scheduled tasks;
- Show a standard notification with standard actions;
- Display app scheduled tasks in a standard widget.

## Required
- A Task Store to register any "task", the app's scheduled tasks in this case. Registered "tasks" are categorized by app.

## App Registration
- An app with scheduled tasks is registered when it is installed or updated. The fact that the app uses such tasks must be detectable.
- The app communicates which notification actions it supports (see Notification Actions below). This registration is updated when the app is updated (if there is a change in what it supports).

## General
- An app with scheduled tasks is launched in the background (i.e. without displaying a window), either at the opening of the user session and if there are tasks registered for the day, or by waking it up at the start time of the task or a bit earlier if necessary.
- When a task is added, it is automatically enabled. If a task is disabled, it is unregistered.
- When a task is enabled and must be executed on the day of its addition, the app is allowed to run in the background. Otherwise, it can't.

## Portal and App User Interfaces

The portal UI is a standard dialog for adding and updating scheduled tasks.

Deleting a scheduled task can be done using a delete button in the standard dialog or in the app UI. If the delete button is in the app UI, it triggers the display of a standard delete confirmation dialog. The minimum number of relevant properties appear in this dialog to indicate to the user which task is deleted.

Scheduled tasks can be enabled and disabled in the app UI. In this case, the ideal would be to use a confirmation dialog box (presenting the task). To enable and disable several tasks, the app could have an "Apply" action which triggers a dialog box listing all the tasks to be enabled and disabled.

### Case

Copy Task is intended for apps that need to copy/duplicate folders and/or files (e.g. backup apps).

### Copy Task Registration
- Name.
- Description. Optional.
- Start Date.
- Start Time.
- Command(s) to Execute.
	- Source Folders. Folders from which content is copied.
	- Destination Folders. Folders where the content is copied.

### Checks and Permissions
- Source and Destination folders must be detectable in the command(s). It is checked if these are folders to which the app has access. (An Activity Monitor can monitor activity in these folders.)
- Source folders are read-only. The app cannot delete or move their files, nor the folders themselves.
- Destination folders are writable. Write access must be requested, as files in these folders may possibly be deleted or replaced. Ideally, if these folders contain files that should not be deleted or replaced, then the creation, deletion, and replacement of files should be limited to specific files (i.e. with specific extensions).
- For the execution of the task, the app does not have access to the network. This prevents the app from downloading content and thus knowing which progress bar and which units to use (if relevant).

### Notification Actions
- Cancel/Stop. The app task is canceled/stopped.
- Pause and Resume. Action to pause and resume app task. 
- Reschedule. Reschedule the app task.

## Questions
- Portal UI: Should the portal dialog be styled according to desktop environment or application UI style?
- Copy Task: Should the command structure be standardized to detect and perform checks on source and destination folders?
- What are the other types of app scheduled tasks?

## To Do
- Sensitivity (see https://gitlab.freedesktop.org/xdg/xdg-specs/-/issues/103).

**Comment by Mikenux** [comment]
Other issues with the Task Store: https://github.com/flatpak/xdg-desktop-portal/issues/1026, https://github.com/flatpak/xdg-desktop-portal/issues/1025

**Comment by GeorgesStavracas** [comment]
Closing with the same reasoning as https://github.com/flatpak/xdg-desktop-portal/issues/1026#issuecomment-1664392785
