### ISSUE TITLE
Video reproduction with Epiphany

### ISSUE THREAD

**Issue by Tarch1** [flatpak/xdg-desktop-portal#1028]
Hi,
I'm running Epiphany browser that works very great in most sites but it will become unusable with youtube, that have working audio but doesn't reproduce video, it instead shows only a white window and when in fullscreen a black one.
I have a laptop with i5-11400H and RTX 3060
The system is Artix, linux kernel 6.3.2, with gnome-shell and gnome relative packages, and by following the Arch wiki I've installed all the Gstreamer plugins.
Whit a video it uses 300 MB and webkitwebprocess uses 750 MB, measured with bpytop.
App version: epiphany 44.2 - webkitgtk-6.0 2.40.1 - webkit2gtk-4.1 2.40.1 - mutter 44.1 - gnome-shell 44.1

**Comment by GeorgesStavracas** [comment]
Hi, please report this bug to https://gitlab.gnome.org/GNOME/epiphany - unfortunately I cannot move this issue directly as Epiphany is in GNOME's GitLab.

Thanks for understanding.
