### ISSUE TITLE
Can anyone point me to some example about how to use this?

### ISSUE THREAD

**Issue by LordRafa** [flatpak/xdg-desktop-portal#1033]
Hello I am trying to understand how xdg-desktop-portal works, hence I was trying to use gsbus to write a quick example but I really dont know how to make it work.

I would like to read my user information using this method:

org.freedesktop.portal.Account.GetUserInformation

I can see that a response object is created but I have no clue how to retrieve the response

**Comment by JakobDev** [comment]
You may want to take a look at [libportal](https://github.com/flatpak/libportal)

**Comment by LordRafa** [comment]
thx
