### ISSUE TITLE
Permissions needed for Documents portal Add method? 

### ISSUE THREAD

**Issue by Dretch** [flatpak/xdg-desktop-portal#1039]
I am calling the Documents portal [Add method](https://flatpak.github.io/xdg-desktop-portal/#gdbus-method-org-freedesktop-portal-Documents.Add) with a file descriptor I wish to add to the document store.

However, as soon as the method call request is sent to dbus, the dbus connection is broken.

It seems that dbus-broker does  not allow the application to pass file descriptors: the logs say `"Peer :1.1837 is being disconnected as it attempted to pass file descriptors without negotiating support for it."`.

This is on Fedora 17, with KDE.

The [Add method documentation](https://flatpak.github.io/xdg-desktop-portal/#gdbus-method-org-freedesktop-portal-Documents.Add) does not mention that any permissions are needed for this method call. I tried `--socket=session-bus` and `--socket=system-bus` without success.

I suppose that either some permissions are needed for Add, or there is some general misconfiguration on my system that is breaking things. I have no clue what is going on though!

**Comment by Dretch** [comment]
I have discovered the problem:

-  The DBUS protocol requires clients to ask for permission before sending file descriptors.
-  The [DBUS library I am using](https://github.com/rblaze/haskell-dbus) does not support this at all (I'll try to change this).

So this is probably not a documentation issue, since file descriptor negotiation is a standard DBUS thing and not specific to this API.

So I'll close this issue.

**Comment by smcv** [comment]
Yes, you'll need to use a D-Bus implementation that implements file descriptor passing (the `h` type) correctly, including [NEGOTIATE_UNIX_FD](https://dbus.freedesktop.org/doc/dbus-specification.html#auth-command-negotiate-unix-fd) during authentication.

> This is on Fedora 17

I would hope not, that's a version from 2012. I hope you meant Fedora 37!
