### ISSUE TITLE
OpenURI: stop handling file: uris

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/xdg-desktop-portal#104]
With file uris, we risk unintentionally bypassing the sandbox restrictions on filesystem visibility, since the file is opened on the portal side, _outside_ the sandbox. Alex and I discussed this in https://github.com/flatpak/flatpak/issues/766 and agreed to do two things:

1) Drop handling of file: uris from the OpenURI method

2) Add an OpenFile method that takes an open fd instead of a uri

**Comment by matthiasclasen** [comment]
Quick, untested implementation in https://github.com/matthiasclasen/xdg-desktop-portal/tree/open-file

**Comment by matthiasclasen** [comment]
And, here is a branch to make g_app_info_launch_default_for_uri use OpenFile: https://git.gnome.org/browse/glib/log/?h=open-file

**Comment by mariospr** [comment]
I left a couple of small comments in the commits there. Also, I think we should file an issue in https://github.com/flatpak/flatpak-xdg-utils to get it to handle `file://`URIs properly once this lands, so I'm writing this now as a reminder not to forget about it. If I manage to get some free time out of the shell rebase I'm working on, I might even look into it myself. It could be "refreshing" :)

**Comment by matthiasclasen** [comment]
Incorporated your feedback in

https://github.com/flatpak/xdg-desktop-portal/pull/105

**Comment by matthiasclasen** [comment]
I've also pushed a cleaned up version of https://git.gnome.org/browse/glib/log/?h=open-file

**Comment by mariospr** [comment]
Thanks. I've merged that PR now and also filed an issue in flatpak-xdg-utils:
https://github.com/flatpak/flatpak-xdg-utils/issues/1
