### ISSUE TITLE
Return value for org.freedesktop.impl.portal.Access.AccessDialog

### ISSUE THREAD

**Issue by WhyNotHugo** [flatpak/xdg-desktop-portal#1041]
I've written my own implementation of an Access Portal, but want to ensure that my return values are correct.

The documentation for the return values merely repeats the data types, but does not address the _meaning_ of these arguments:

https://github.com/flatpak/xdg-desktop-portal/blob/dea5cac995300e98e7509188f2a7c6011c894f41/data/org.freedesktop.impl.portal.Access.xml#L40-L41

As for the `response` argument, I've been able to figure out that `0` is "grant access" and non-zero is "deny access". Is this correct? Or do specific non-zero responses have a specific meaning? Does any value represent "grant access only once"?

Regarding the `results` argument: is it just one (or more) of the provided `options/choices`?

I can send a PR with improvements to the documentation with these details, but I'd rather confirm that my guesses are correct first.

**Comment by Marukesu** [comment]
> As for the response argument, I've been able to figure out that 0 is "grant access" and non-zero is "deny access". Is this correct? Or do specific non-zero responses have a specific meaning? Does any value represent "grant access only once"?

there's a enum with possible/known values in request.h that matches what the gtk backend does. AFAIK, the portals calling access only check if 0 was returned.

> Regarding the results argument: is it just one (or more) of the provided options/choices?

it's all passed choices, with the final values.

**Comment by WhyNotHugo** [comment]
https://github.com/flatpak/xdg-desktop-portal/pull/1114
