### ISSUE TITLE
org.freedesktop.impl.portal.Access.AccessDialog is called with implementation-specific message

### ISSUE THREAD

**Issue by WhyNotHugo** [flatpak/xdg-desktop-portal#1042]
`org.freedesktop.impl.portal.Access.AccessDialog` is called with the following information: 

```
app_id = ""
parent_window = ""
title = "Turn On Camera?"
subtitle = "An application wants to use your camera."
body = "Access to your camera can be changed at any time from the privacy settings."
options = {
    "icon": Str(
        Str(
            Borrowed(
                "camera-web-symbolic",
            ),
        ),
    ),
}
```

The `body` here is very implementation-specific. In GNOME, the access can be changed at any time in privacy settings, but on other desktops this may not be true.

I believe this text should be moved into the `xdg-desktop-portal-gtk` access portal implementation, and something more generic / less DE-specific should be send by the `xdg-desktop-portal` instead.

**Comment by GeorgesStavracas** [comment]
https://github.com/flatpak/xdg-desktop-portal/pull/1227 fixed this
