### ISSUE TITLE
Global shortcuts timestamps incompatible with input timestamps

### ISSUE THREAD

**Issue by jadahl** [flatpak/xdg-desktop-portal#1054]
The `Activated` and `Deactivated` timestamps are specified to be "as seconds and microseconds since the Unix epoch". This has some problems:

  * Input timestamps are practically always using the monotonic clock. The only exception is Xorg from *very* long ago. The clock being different here means we can't pass them forward, thus have to make up new timestamps. That looses information about the actual time the action was triggered.
  * "Since the Unix epoch" means a bunch of things that since long is no longer used for anything other displaying a clock to the user, as it means it'd be affected by timezone changes, when the clock, etc.

Is the "base" for the timestamp really needed? If it really is, it should arguably be using the same as all other input like events on the system, meaning the monotonic clock.

Should we just call it a "bug" and change it? Otherwise we'll need a version bump.

Cc: @aleixpol @GeorgesStavracas

**Comment by jadahl** [comment]
Attempted to see where `xdg-desktop-portal-kde` gets its timestamp from, and it appears to be using the X11 timestamp (monotonic clock in milliseconds), or hard code `0` in the non-X11 case: https://invent.kde.org/plasma/kglobalacceld/-/blob/11d65c8c35ff4d8f0f7a38bf2bf3889eb6973934/src/component.cpp#L199-211 so it's not following the spec. It also makes me believe the intention was to use a clock similar to the input timestamps, since that is what kglobalaccel roughly uses, only that it does not related to any unix epoch, meaning the wording as is is a bug, that we can probably fix without bumping any versions. I don't think there are any other backend implementations than the KDE one today.

The X11 time appears to come from the time field in xcb events (e.g. https://www.x.org/releases/current/doc/man/man3/xcb_key_release_event_t.3.xhtml ), from e.g. here https://github.com/qt/qtbase/blob/3f9817b26cd26fa731ca88537c0137d31c0383e4/src/plugins/platforms/xcb/qxcbconnection.cpp#L636 to https://github.com/qt/qtbase/blob/3f9817b26cd26fa731ca88537c0137d31c0383e4/src/plugins/platforms/xcb/qxcbconnection.h#L152 to https://github.com/qt/qtbase/blob/3f9817b26cd26fa731ca88537c0137d31c0383e4/src/plugins/platforms/xcb/qxcbconnection.h#L151 to https://github.com/qt/qtbase/blob/3f9817b26cd26fa731ca88537c0137d31c0383e4/src/plugins/platforms/xcb/qxcbnativeinterface.cpp#L281 then somehow to https://github.com/qt/qtbase/blob/3f9817b26cd26fa731ca88537c0137d31c0383e4/src/gui/platform/unix/qtx11extras.cpp#L182.

So with that in mind, the KDE implementation already uses the monotonic clock, since that is what the X server has been using for a decade or more, but unless I'm missing something, it's sending the events as milliseconds instead of the stated microseconds.

So I think we should do this:
 * Change the wording to either say "clock undefined" or "monotonic clock"
 * Fix xdg-desktop-portal-kde to pass microseconds instead of milliseconds (unless I failed to found the place where the X11 server time is multiplied by 1000). The clock itself is already correct.
 * kglobalacceld can probably use
```c
    timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
```
and get a suitable microseconds timestamp that way on the non-X11 case (it is in practice the same clock is used for input events on Wayland). Couldn't find that syscall wrapped in Qt/KDE API, maybe there is.

Any objections to this?

**Comment by GeorgesStavracas** [comment]
Excellent investigation, thanks for doing that.

> Any objections to this?

From my side, no. It's pretty clear to me that not using monotonic was an oversight.

**Comment by davidedmundson** [comment]
No objections on the kde side to just changing the spec. 

I'll sort out the x11 portal impl to be of the new unit. We don't have users of the timestamp as far as I can see. 

The equivalent Wayland spec is "	The time argument is a timestamp with millisecond granularity, with an undefined base." So that seems a good new wording.

**Comment by jadahl** [comment]
> The equivalent Wayland spec is " The time argument is a timestamp with millisecond granularity, with an undefined base." So that seems a good new wording.

Will you propose such a change (and tweak the test case)?
