### ISSUE TITLE
Run pytest tests individually

### ISSUE THREAD

**Issue by GeorgesStavracas** [flatpak/xdg-desktop-portal#1057]
https://github.com/flatpak/xdg-desktop-portal/pull/1055 introduced a commit to extend the timeout of pytests to 120s.

That's a temporary breathing room for the test not to get flacky, but ideally we'd run individual portal tests separatedly

**Comment by ebassi** [comment]
Picking this up since I've already had to touch the test suite, but will likely have to wait a couple of weeks—GUADEC and scheduled PTO.
