### ISSUE TITLE
Can't OpenFile in /app

### ISSUE THREAD

**Issue by alexlarsson** [flatpak/xdg-desktop-portal#107]
If an app wants to open a file in its own data, it will be a path in /app, this will not be mapped on the host, nor in the target app. This is common for instance if the app wants to spawn a reader for some docs (say a html or pdf) that is included with the app.

I think we need to identify this case and map /app to the actual location of the file is installed on the host system.

**Comment by alexlarsson** [comment]
Same is true for /usr and the runtime i guess.

**Comment by matthiasclasen** [comment]
that requires a fix to your file visibility check, I guess ?

**Comment by alexlarsson** [comment]
I think we need to reverse-map /app to the real location in xdg-desktop-portal, at that point we know the location of these from the .flatpak-info file:
```
[Instance]
app-path=/var/lib/flatpak/app/org.gnome.gedit/x86_64/stable/3602fece3ffa10bc1add4195d36eca0bec2e648634059ee679f000d8387ba8e6/files
runtime-path=/var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.24/7e0cc2f15bbce94b7123aaa05591c58a69f24294f9544b300588164f80fc22de/files
```
