### ISSUE TITLE
Document portal does not remember last used files after a restart

### ISSUE THREAD

**Issue by valeth** [flatpak/xdg-desktop-portal#1075]
I've noticed this issue in the OBS Studio and qpwgraph Flatpaks, where I have to reselect the directory/file where resources are located every time I start the application.

This problem only occurs after a restart of the document portal, so after a reboot, or when forcibly closing it.

I don't know if it's those applications misusing the portal API, or if it's a lack of functionality or bug currently in the portal.

**Comment by GeorgesStavracas** [comment]
This behaviour is specified by each backend. On GNOME, for example, remembers the [last used folder por application](https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/commit/4254d1c8acc78911c713da5a72bb175c23ef32a8). Please open a feature request to your desktop environment's portal backend implementation if you think they should implement such behaviour.

**Comment by valeth** [comment]
Just for future reference:
I've opened a bug report on the KDE bug tracker
https://bugs.kde.org/show_bug.cgi?id=476796

**Comment by GeorgesStavracas** [comment]
Thank you for reporting it to the KDE folks
