### ISSUE TITLE
how fix? No such interface “org.freedesktop.portal.Background” 

### ISSUE THREAD

**Issue by sgehrman** [flatpak/xdg-desktop-portal#1085]
I've searched for a few hours and couldn't figure it out.  I'm on the latest Debian.

I have xdg-desktop-portal-gnome and xdg-desktop-portal-gtk install.  Do I need to tell users who install my app they need to install these? Didn't seem to help, but wondering about that.

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Background” on object at path /org/freedesktop/portal/desktop
#0 DBusClient.\_callMethod (package:dbus/src/dbus_client.dart:1108)
<asynchronous suspension>
#1 DBusClient.callMethod (package:dbus/src/dbus_client.dart:608)
<asynchronous suspension>
#2 XdgBackgroundPortal.requestBackground.<anonymous closure> (package:xdg_desktop_portal/src/xdg_background_portal.dart:68)
<asynchronous suspension>
#3 XdgPortalRequest.\_onListen (package:xdg_desktop_portal/src/xdg_portal_request.dart:39)
<asynchronous suspension>

Other things I've tried:

steve@5950x:~/Documents/GitHub/dfc/dashboard$ /usr/libexec/xdg-desktop-portal --replace --verbose
XDP: load portals from /usr/share/xdg-desktop-portal/portals
XDP: loading /usr/share/xdg-desktop-portal/portals/gnome-shell.portal
XDP: portal implementation for gnome
XDP: portal implementation supports org.freedesktop.impl.portal.Access
XDP: loading /usr/share/xdg-desktop-portal/portals/gnome-keyring.portal
XDP: portal implementation for gnome
XDP: portal implementation supports org.freedesktop.impl.portal.Secret
XDP: loading /usr/share/xdg-desktop-portal/portals/gtk.portal
XDP: portal implementation for gnome
XDP: portal implementation supports org.freedesktop.impl.portal.FileChooser
XDP: portal implementation supports org.freedesktop.impl.portal.AppChooser
XDP: portal implementation supports org.freedesktop.impl.portal.Print
XDP: portal implementation supports org.freedesktop.impl.portal.Notification
XDP: portal implementation supports org.freedesktop.impl.portal.Inhibit
XDP: portal implementation supports org.freedesktop.impl.portal.Access
XDP: portal implementation supports org.freedesktop.impl.portal.Account
XDP: portal implementation supports org.freedesktop.impl.portal.Email
XDP: portal implementation supports org.freedesktop.impl.portal.DynamicLauncher
XDP: portal implementation supports org.freedesktop.impl.portal.Lockdown
XDP: portal implementation supports org.freedesktop.impl.portal.Settings
XDP: Using gtk.portal for org.freedesktop.impl.portal.Lockdown in GNOME
XDP: providing portal org.freedesktop.portal.MemoryMonitor
XDP: providing portal org.freedesktop.portal.PowerProfileMonitor
XDP: providing portal org.freedesktop.portal.NetworkMonitor
XDP: providing portal org.freedesktop.portal.ProxyResolver
XDP: providing portal org.freedesktop.portal.Trash
XDP: providing portal org.freedesktop.portal.GameMode
XDP: providing portal org.freedesktop.portal.Realtime
XDP: Using gtk.portal for org.freedesktop.impl.portal.Settings
XDP: providing portal org.freedesktop.portal.Settings
XDP: Using gtk.portal for org.freedesktop.impl.portal.FileChooser in GNOME
XDP: providing portal org.freedesktop.portal.FileChooser
XDP: Using gtk.portal for org.freedesktop.impl.portal.AppChooser in GNOME
XDP: providing portal org.freedesktop.portal.OpenURI
XDP: Using gtk.portal for org.freedesktop.impl.portal.Print in GNOME
XDP: providing portal org.freedesktop.portal.Print
XDP: Using gtk.portal for org.freedesktop.impl.portal.Notification in GNOME
XDP: providing portal org.freedesktop.portal.Notification
XDP: Using gtk.portal for org.freedesktop.impl.portal.Inhibit in GNOME
XDP: providing portal org.freedesktop.portal.Inhibit
XDP: Using gnome-shell.portal for org.freedesktop.impl.portal.Access in GNOME
XDP: providing portal org.freedesktop.portal.Device
XDP: providing portal org.freedesktop.portal.Location
XDP: providing portal org.freedesktop.portal.Camera
XDP: Using gtk.portal for org.freedesktop.impl.portal.Account in GNOME
XDP: using org.freedesktop.impl.portal.Account at org.freedesktop.impl.portal.desktop.gtk

XDP: providing portal org.freedesktop.portal.Account
XDP: Using gtk.portal for org.freedesktop.impl.portal.Email in GNOME
XDP: providing portal org.freedesktop.portal.Email
XDP: Using gnome-keyring.portal for org.freedesktop.impl.portal.Secret in GNOME
XDP: providing portal org.freedesktop.portal.Secret
XDP: Using gtk.portal for org.freedesktop.impl.portal.DynamicLauncher in GNOME
XDP: providing portal org.freedesktop.portal.DynamicLauncher
XDP: org.freedesktop.portal.Desktop acquired

steve@5950x:~/Documents/GitHub/dfc/dashboard$ cd /usr/share/dbus-1/interfaces/
steve@5950x:/usr/share/dbus-1/interfaces$ ls
com.endlessm.ParentalControls.AccountInfo.xml org.freedesktop.Accounts.xml org.freedesktop.Avahi.Server.xml org.freedesktop.ColorManager.Device.xml org.freedesktop.GeoClue2.Location.xml org.freedesktop.Tracker3.Miner.Files.Index.xml org.gnome.Shell.Introspect.xml org.kde.kded5.xml
com.endlessm.ParentalControls.AppFilter.xml org.freedesktop.Avahi.AddressResolver.xml org.freedesktop.Avahi.ServiceBrowser.xml org.freedesktop.ColorManager.Profile.xml org.freedesktop.GeoClue2.Manager.xml org.freedesktop.Tracker3.Miner.xml org.gnome.Shell.PadOsd.xml
com.endlessm.ParentalControls.SessionLimits.xml org.freedesktop.Avahi.DomainBrowser.xml org.freedesktop.Avahi.ServiceResolver.xml org.freedesktop.ColorManager.Sensor.xml org.freedesktop.GeoClue2.xml org.freedesktop.UPower.Device.xml org.gnome.Shell.Screencast.xml
kf5_org.kde.krunner1.xml org.freedesktop.Avahi.EntryGroup.xml org.freedesktop.Avahi.ServiceTypeBrowser.xml org.freedesktop.ColorManager.xml org.freedesktop.PackageKit.Transaction.xml org.freedesktop.UPower.KbdBacklight.xml org.gnome.Shell.Screenshot.xml
org.fedoraproject.Config.Printing.xml org.freedesktop.Avahi.HostNameResolver.xml org.freedesktop.bolt.xml org.freedesktop.GeoClue2.Agent.xml org.freedesktop.PackageKit.xml org.freedesktop.UPower.xml org.gnome.ShellSearchProvider2.xml
org.freedesktop.Accounts.User.xml org.freedesktop.Avahi.RecordBrowser.xml org.freedesktop.ColorHelper.xml org.freedesktop.GeoClue2.Client.xml org.freedesktop.RealtimeKit1.xml org.gnome.Shell.Extensions.xml org.gnome.ShellSearchProvider.xml

xdg-desktop-portal-gtk is already the newest version (1.14.1-1).

steve@5950x:/usr/share/dbus-1/interfaces$ sudo apt install xdg-desktop-portal-gnome
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
xdg-desktop-portal-gnome
0 upgraded, 1 newly installed, 0 to remove and 3 not upgraded.
Need to get 175 kB of archives.
After this operation, 1,024 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian bookworm/main amd64 xdg-desktop-portal-gnome amd64 43.1-2 [175 kB]
Fetched 175 kB in 0s (1,077 kB/s)  
Selecting previously unselected package xdg-desktop-portal-gnome.
(Reading database ... 392271 files and directories currently installed.)
Preparing to unpack .../xdg-desktop-portal-gnome_43.1-2_amd64.deb ...
Unpacking xdg-desktop-portal-gnome (43.1-2) ...
Setting up xdg-desktop-portal-gnome (43.1-2) ...
Processing triggers for libglib2.0-0:amd64 (2.74.6-2) ...
Processing triggers for mailcap (3.70+nmu1) ...
Processing triggers for desktop-file-utils (0.26-1) ...
Processing triggers for gnome-menus (3.36.0-1.1) ...

**Comment by sgehrman** [comment]
?

**Comment by smcv** [comment]
> I'm on the latest Debian

"The latest" isn't a version number. Is that Debian 12, or Debian testing/unstable, or what? From your apt output, the answer seems to be Debian 12 'bookworm'.

> I have xdg-desktop-portal-gnome and xdg-desktop-portal-gtk install. Do I need to tell users who install my app they need to install these?

I don't know what your app does, so I can't answer that.

If your app has a hard requirement on the Background interface, then it will need a working implementation of the Background interface at runtime.

If your app wants to use the Background interface if available but can cope without it, then you can handle the error (catch the exception) and turn it into a non-fatal warning, or just a debug-log message, or whatever error handling you would prefer to have.

xdg-desktop-portal-gtk does not provide the Background interface.

xdg-desktop-portal-gnome provides the Background interface, but only if you are running GNOME. If you are not running GNOME, it cannot implement the Background interface, even if it's installed. If you *are* running GNOME, you'll probably need to restart xdg-desktop-portal after installing xdg-desktop-portal-gnome.

Similarly, xdg-desktop-portal-kde provides the Background interface, but only if you are running KDE Plasma.

Other desktop environments do not seem to offer an implementation of the Background interface at the moment.

None of this seems like an xdg-desktop-portal bug: it's providing the functionality that's available, but it can't provide functionality that isn't available to it.
