### ISSUE TITLE
[RFE] Update pofiles before new version release

### ISSUE THREAD

**Issue by AsciiWolf** [flatpak/xdg-desktop-portal#110]
Would it be possible to update the pofiles of _xdg-desktop-portal_ and _xdg-desktop-portal-gtk_ before releasing a new version? It would make translating a lot easier.

**Comment by AsciiWolf** [comment]
Thanks!

**Comment by AsciiWolf** [comment]
@matthiasclasen Would it also be possible to make xdg-desktop-portal-gtk.pot file for _xdg-desktop-portal-gtk_?
P.S. I think there should be "Report-Msgid-Bugs-To: https://github.com/flatpak/xdg-desktop-portal-gtk/issues\n" in the _xdg-desktop-portal-gtk_ pofiles. The current version is empty.

**Comment by matthiasclasen** [comment]
Make it yourself: cd po; make xdg-desktop-portal-gtk.pot. The pot file is not supposed to be under source control

**Comment by AsciiWolf** [comment]
@matthiasclasen What about the [xdg-desktop-portal one](https://github.com/flatpak/xdg-desktop-portal/blob/master/po/xdg-desktop-portal.pot)?

**Comment by matthiasclasen** [comment]
that was added by accident. fixed now.

**Comment by AsciiWolf** [comment]
Thanks. Would it also be possible to fix the _Report-Msgid-Bugs-To_ in xdg-desktop-portal-gtk?

**Comment by matthiasclasen** [comment]
sure. send a pr ?

**Comment by AsciiWolf** [comment]
Done.

**Comment by AsciiWolf** [comment]
(By the way, do not want to bother you but I see that you pushed the commit removing the pot file into gnome-accounts branch, not master. Is it ok?)

**Comment by matthiasclasen** [comment]
arr
