### ISSUE TITLE
Mechanism to retain compatibility across x-d-p 1.16 -> 1.17

### ISSUE THREAD

**Issue by smcv** [flatpak/xdg-desktop-portal#1102]
With the move from x-d-p 1.16 to 1.17, users of non-integrated, self-assembled or non-portal-aware desktop environments will find that Flatpak/Snap apps can no longer find a suitable portal backend (#1077 is an example of this). Prior to 1.17, users of these environments were implicitly relying on the fact that distro package dependencies would pull in at least one portal backend (in practice x-d-p-gtk), and x-d-p would run it. As a temporary stopgap I've patched in a hard-coded fallback to x-d-p-gtk in Debian's x-d-p, at a lower priority than trying UseIn; but that isn't going to help other distros, and @ebassi indicated in #1077 that this is unlikely to be accepted upstream.

I am not happy about having that hard-coded fallback, but I'm also not happy about the prospect of knowingly making desktop environments and desktop-environment-like things regress, because I expect that as soon as I remove the fallback, I'll get high-severity bug reports asking "why can't I just", which are relatively likely to be accompanied by accusations of incompetence or malfeasance.

I have been trying to get desktop environments to (set `XDG_CURRENT_DESKTOP` and) add a `${DESKTOP}-portals.conf`, either upstream ([GNOME](https://gitlab.gnome.org/GNOME/gnome-session/-/issues/114), [GNOME Flashback](https://gitlab.gnome.org/GNOME/gnome-flashback/-/issues/91), [Mate](https://github.com/mate-desktop/mate-desktop/issues/574), [Cinnamon](https://github.com/linuxmint/cinnamon/issues/11857), [Xfce](https://gitlab.xfce.org/xfce/xfce4-session/-/issues/181)) or [downstream](https://udd.debian.org/cgi-bin/bts-usertags.cgi?user=xdg-desktop-portal%40packages.debian.org&tag=portals.conf). Actively advocating this in a selection of major desktop environments has already been quite time consuming, so I am not going to be able to do this for all of the desktop environments that I don't use, and certainly not for the long tail of window-managers-that-act-like-a-desktop-environment. I've also had some push-back from window manager maintainers who [don't want to be responsible for choosing portals for their users](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1050911).

So I'm asking here: can we do something better/more-compatible in x-d-p that will "do what I mean" for users of less-major desktop environments, without losing the benefits of `portals.conf(5)`?

Some options that spring to mind:

1. On #1077, @ebassi suggested that distributions can provide a `/usr/share/xdg-desktop-portal/portals.conf` if they want to. However, if I provided that file in Debian's `xdg-desktop-portal` package, it would be treated as higher-precedence than `UseIn`, meaning that desktop environments that have not yet added a `${DESKTOP}-portals.conf` would regress by accidentally switching to x-d-p-gtk and disabling any other backends that had previously been picked up from `UseIn`. GNOME and KDE have been fixed already, Mate/Cinnamon/Xfce are in progress, and LXQt is in progress in at least Ubuntu, but wlroots-based compositors would regress by not selecting `x-d-p-wlr`, which they get from `UseIn=wlroots;sway;Wayfire;river;phosh;Hyprland` at the moment. So it doesn't necessarily seem desirable to do that before at least [sway](https://bugs.debian.org/1050913) and [wayfire](https://bugs.debian.org/1050914) provide a `${DESKTOP}-portals.conf`. (The others are not packaged in Debian, so are not currently my problem.)

2. After going through the `portals.conf(5)` stack, and then trying `UseIn`, we could make x-d-p try loading `/usr/share/xdg-desktop-portal/fallback.conf`. Upstream, x-d-p would not provide this, remaining entirely backend-agnostic. Downstream, x-d-p packagers (like me) can provide a `fallback.conf` that selects a "good enough" portal backend, in practice x-d-p-gtk. This is essentially the same as the hard-coded fallback that's in Debian now, but as a configuration file rather than a patch.

3. Or, after going through the `portals.conf(5)` stack, either before or after trying `UseIn`, as a last resort we could make x-d-p try  loading files from some other directory like `/usr/share/xdg-desktop-portal/fallbacks/` with the same naming rules as `portals.conf(5)`. Again, upstream, x-d-p would not provide this, remaining entirely backend-agnostic, but downstream, x-d-p packagers can provide fallbacks in that directory for desktop environments that haven't caught up, without conflicting with desktop environment maintainers (who are free to add the higher-precedence version any time they want to, at which point the version in the x-d-p packaging becomes redundant and can be removed).

Or maybe someone has a better idea than all of those?

**Comment by matthiasclasen** [comment]
I would say: users of those self-assembled environments will just have to do some more self-assembly.

**Comment by smcv** [comment]
#1103 (unfinished), #1192 and #1199 are various implementations of possible approaches to resolving this. There seems to be interest in this from people other than me, and there is some more discussion about this on #1192.

We should agree on one of the proposed solutions, or one of my other suggestions on this issue, or someone's better idea, and reject the others.
