### ISSUE TITLE
Updated Hebrew translation

### ISSUE THREAD

**Issue by yoseforb** [flatpak/xdg-desktop-portal#1109]
Can you please push the he.po.txt file attached? This is an update for the Hebrew translation file (should be renamed to he.po)
[he.po.txt](https://github.com/flatpak/xdg-desktop-portal/files/12656373/he.po.txt)

**Comment by Mikenux** [comment]
Why not open a PR?

**Comment by GeorgesStavracas** [comment]
@yoseforb please open a pull request with this file :)

**Comment by GeorgesStavracas** [comment]
Closing, as this needs to be a pull request, and this file is probably outdated now.

@yoseforb if you open a pull request, it'll be merged, no questions asked :slightly_smiling_face:
