### ISSUE TITLE
The portal config file does not actually specify the order of portals to be tried

### ISSUE THREAD

**Issue by q234rty** [flatpak/xdg-desktop-portal#1111]
The [documentation](https://github.com/flatpak/xdg-desktop-portal/blob/1.18.0/doc/portals-conf.rst#file-format) suggests that

> Each key in the group contains a semi-colon separated list of portal backend
implementation, to be searched for an implementation of the requested interface,
**in the same order as specified in the configuration file**.

However, this does not seems to match the actual behavior: In KDE with
```
[preferred]
org.freedesktop.impl.portal.FileChooser=gtk;kde
```
The kde file chooser is still opened despite `gtk` being specified first.

Looking at the code, it seems that the implementation are sorted based on UseIn and name in https://github.com/flatpak/xdg-desktop-portal/blob/1.18.0/src/portal-impl.c#L317 , then tried in that order in https://github.com/flatpak/xdg-desktop-portal/blob/1.18.0/src/portal-impl.c#L550 , so instead of searching in the same order as in the config and returning the first portal implementing the interface, which is what the documentation suggests, it searches in the "old" order based on UseIn and name, using the config only as an allowed list of portals.

**Comment by GeorgesStavracas** [comment]
hm, no, probably not

**Comment by alyssais** [comment]
I've opened https://github.com/flatpak/xdg-desktop-portal/pull/1240 to try to fix this.

**Comment by GeorgesStavracas** [comment]
Thanks, very much appreciated
