### ISSUE TITLE
[Bug]: Flatpak doesn't use Breeze theme, uses Adwaita in KDE Plasma

### ISSUE THREAD

**Issue by meatsink** [flatpak/xdg-desktop-portal#1112]
### Checklist

- [X] I agree to follow the [Code of Conduct](https://github.com/flatpak/flatpak/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/flatpak/flatpak/issues) for a bug that matches the one I want to file, without success.
- [X] If this is an issue with a particular app, I have tried filing it in the appropriate issue tracker for the app (e.g. under https://github.com/flathub/) and determined that it is an issue with Flatpak itself.
- [X] This issue is not a report of a security vulnerability (see [here](https://github.com/flatpak/flatpak/blob/main/SECURITY.md) if you need to report a security issue).

### Flatpak version

1.15.4

### What Linux distribution are you using?

Other (specify below)

### Linux distribution version

openSUSE Tumbleweed 20230921

### What architecture are you using?

x86_64

### How to reproduce

Use KDE Plasma
Launch Firefox, Thunderbird or a GTK4 app

### Expected Behavior

Apps use Breeze, which is installed in flatpak

### Actual Behavior

App seems to use Adwaita theme with gigantic Adwaita cursor when you hover over the app, doesn't use Breeze, and GTK4 apps appear with crusty font rendering
![image](https://github.com/flatpak/flatpak/assets/121370032/11cd0090-5d1f-46cb-a65f-2583af8603e4)
![image](https://github.com/flatpak/flatpak/assets/121370032/bd561664-33bd-42b0-8131-c5c4fe457e25)

### Additional Information

This does not happen with the native version of the apps.

**Comment by smcv** [comment]
What xdg-desktop-portal backends do you have installed? (x-d-p-gtk, x-d-p-kde, maybe others)

What (if anything) is in `/usr/share/xdg-desktop-portal/kde-portals.conf`?

Do you have any local [portals.conf(5)](https://github.com/flatpak/xdg-desktop-portal/blob/main/doc/portals-conf.rst) configuration?

Are any warnings logged in the systemd Journal when xdg-desktop-portal starts?

**Comment by smcv** [comment]
cc @ebassi @kennylevinsen @GeorgesStavracas 

I think this is the missing issue report for which #1106 is one proposed solution. I am unsure whether #1106 is the *correct* solution for it - that will need more discussion.

Another possible solution to this, from the KDE/Plasma side, would be for `/usr/share/xdg-desktop-portal/kde-portals.conf` to say something like this (untested):

```
[preferred]
default=kde
org.freedesktop.impl.portal.Settings=kde;gtk;
```

or even this, although like #1106, this comes with an increased risk of re-introducing related issues like https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/issues/74, https://github.com/linuxmint/xdg-desktop-portal-xapp/issues/5, #986, #1024 and #1032:

```
[preferred]
default=kde
org.freedesktop.impl.portal.Settings=kde;*;
```

Or, whatever KDE/Plasma component asks GTK apps to use the Breeze theme (I don't use Plasma myself, but I think `kde-gtk-config` is responsible for this?) could install a small extra portal backend that implements the relevant part of the Settings interface - perhaps named `kde-gtk-config.portal`? - and then the `kde-portals.conf` could say something like this:

```
[preferred]
default=kde
org.freedesktop.impl.portal.Settings=kde;kde-gtk-config;
```

Or that functionality could be integrated into `x-d-p-kde`.

There are several options here, and from my point of view, the important things here are:

1. fix the issue;
2. but avoid reintroducing #986, #1024, #1032 by doing so

The reason I'm wary about #1106 is that I think it carries a risk of succeeding at (1.) but failing (2.).

**Comment by smcv** [comment]
There is also some discussion on this topic in comments on #1017.

cc @Rongronggg9 @travier @nicolasfella

**Comment by travier** [comment]
In KDE & Fedora land this is:
- https://bugzilla.redhat.com/show_bug.cgi?id=2240211
- https://pagure.io/fedora-kde/SIG/issue/396
- https://bugs.kde.org/show_bug.cgi?id=474746

I've made a PR with your suggestion in https://invent.kde.org/plasma/xdg-desktop-portal-kde/-/merge_requests/231

**Comment by smcv** [comment]
> I've made a PR with your suggestion in https://invent.kde.org/plasma/xdg-desktop-portal-kde/-/merge_requests/231

As with #1106, I would be concerned that the configuration currently proposed there will result in running other desktop environments' portal backends that are not necessarily intended or designed to run correctly under Plasma.

`x-d-p-gtk` should be OK (because it's the portal that we end up using as a fallback, even though it wasn't originally intended for that purpose), therefore configuring `kde;gtk;` should also be OK; but other desktops' desktop-specific backends like `-gnome` and `-xapp` have caused genuine problems in the past (see links above) and that doesn't give me a high level of confidence that there won't be similar issues again in the future.

I'd be using `org.freedesktop.impl.portal.Settings=kde;gtk;` if it was up to me.

**Comment by nicolasfella** [comment]
What if tomorrow wxWidgets creates a settings portals and apps using wxWidgets expect it to be there?

Would desktops need to add `org.freedesktop.impl.portal.Settings=kde;gtk;wxwidgets;` to their config? And how would they know this is necessary?

**Comment by Erick555** [comment]
KDE made fixes/workarounds:

https://invent.kde.org/plasma/xdg-desktop-portal-kde/-/merge_requests/231

https://invent.kde.org/plasma/xdg-desktop-portal-kde/-/merge_requests/233

Distros may backport them or wait for next release.

**Comment by GeorgesStavracas** [comment]
Is there anything else to be discussed in this issue? The original complaint about GTK themes on KDE seems to have been resolved with the two merge requests above. So either this issue needs to be repurposed to something else, or a new issue should be open with a proposed behavioural change.

**Comment by kennylevinsen** [comment]
I personally prefer fully explicit configuration as it will have many fewer caveats, so considering the new behavior a feature is fine by me. As we still have UseIn= support, we could consider if we should have a fallback for when no portal config file was found (`config == NULL || portal_impl_matches_config...`).

Regarding #1106, I don't quite agree that it undoes #1018 - my intent with #1018 was to make Settings configurable where it previously was not, while #1106 changes the default behavior - but it should indeed only be merged if requiring explicit configuration is considered a bug, and I wrote that patch in case you decided to lean that way.

**Comment by 4e554c4c** [comment]
>  I feel as though oscillating between two mutually contradictory policies ("all Settings backends must be safe to run in all environments" vs. "we need to avoid running unintended Settings backends")

I don't think this is a binary that needs to exist. Why not add a field to `/usr/share/xdg-desktop-portal/portals/*.portal` that advertises whether it is safe to use in other desktops?
e.g.

/usr/share/xdg-desktop-portal/portals/gnome-shell.portal:
```
[portal]
DBusName=org.gnome.Shell.Portal
Interfaces=org.freedesktop.impl.portal.Access
UseIn=gnome
Exclusive=true
```
/usr/share/xdg-desktop-portal/portals/gnome-shell.portal:
```
[portal]
DBusName=org.gnome.Shell.Portal
Interfaces=org.freedesktop.impl.portal.Access
UseIn=gnome
Exclusive=false
```

even better, a desktop portal could specify `UseIn=*` if it is not specific to any desktop environment. Each desktop could then include it in their `<desktop>-portals.conf`.

If backwards compatibility is an issue, it seems fair to assume `Exclusive=false` if it is not specified.

**Comment by GeorgesStavracas** [comment]
Given that https://github.com/flatpak/xdg-desktop-portal/pull/1018 landed, let's close https://github.com/flatpak/xdg-desktop-portal/pull/1106 and call this done.
