### ISSUE TITLE
Transient screen cast stream restoration no longer works

### ISSUE THREAD

**Issue by aiddya** [flatpak/xdg-desktop-portal#1124]
Screen cast stream restoration with persist mode as transient no longer works with xdg-desktop-portal 1.18. It works if the persist mode is until explicitly revoked.

### Steps to reproduce
1. Open this [WebRTC test page](https://mozilla.github.io/webrtc-landing/gum_test.html) with Chromium on a distro with xdg-desktop-portal 1.18
2. Click on "screen capture" and switch to "Window" or "Entire screen" tabs.
3. Select a source on portal dialog and wait for the thumbnail to appear
4. Click on "Share"

### Expected behavior
Shared screen/window is displayed.

### Actual behavior
The portal dialog appears again.

DBus logs show that the application is passing restore token correctly and the portal implementation is returning restore data. The bug is either in storing the restore token along with restore data or while retrieving it.

cc @jadahl

**Comment by aiddya** [comment]
It appears that the bug is a result of deleting all transient restore tokens once the screen cast session is closed. However, the documentation for transient persist mode says that "Permissions persist as long as the application is running".

**Comment by grulja** [comment]
I can reproduce. I expect this is related to https://github.com/flatpak/xdg-desktop-portal/pull/1004.

**Comment by GeorgesStavracas** [comment]
This is not reproducible on Firefox. Are you sure this is not a Chromium issue?

**Comment by GeorgesStavracas** [comment]
Now that I test this, I think I've seen that on Chromium for a long time... certainly before #1004.

**Comment by grulja** [comment]
> This is not reproducible on Firefox. Are you sure this is not a Chromium issue?

Firefox works differently and doesn't rely on stream restoration. I've seen this issue before with Google Meet, which might be a bug in Chromium (on my TODO list), but for example the WebRTC test page has been working all the time. There was no Chromium change to screen sharing for a while.

**Comment by aiddya** [comment]
The flow in Chromium is that it starts a screen cast session to show thumbnails on the screen/window picker and it restores the stream in a new session to show the stream on the web page.  Firefox does not show thumbnails, so it doesn't use stream restoration.

The regression was introduced by #1004, specifically the [`internal_closed_cb`](https://github.com/flatpak/xdg-desktop-portal/pull/1004/commits/e80eee5269b8357d4bb68e79db23e020f651ec1a#diff-7412bf4118dc7bb0aa6bc850cd0ef461ac8fd56f0083900a38eaa6334f31683cR31) method which was not present before the refactor. It deletes all restore tokens created in a session when a session is closed. Since Chromium uses one session to capture thumbnails and another session to show the stream on the page, the restore tokens are being deleted at the end of the first session.

This is contrary to the documentation of transient persist mode, which says that  "Permissions persist as long as the application is running".

**Comment by GeorgesStavracas** [comment]
Thanks @aiddya, I think your diagnostic is correct. Patch incoming.

**Comment by GeorgesStavracas** [comment]
> It'd be helpful to document that in meson_options.txt and in CONTRIBUTING.md as something to watch out for.

Patches welcomed :)

**Comment by aiddya** [comment]
>Patches welcomed :)

I may not have all the information write such documentation, but I can give it a shot.

@grulja I think the Google Meet issue that you're seeing might be fixed with a patch like this on Chromium: https://github.com/electron/electron/pull/40098
