### ISSUE TITLE
Limited portal config expressiveness

### ISSUE THREAD

**Issue by M1cha** [flatpak/xdg-desktop-portal#1133]
The new config file format does not allow me to express the config I want(aka what I had previously). What I want is:
- Use all the interfaces provided by impl A (default)
- Use all the interfaces provided by impl B that are not provided by impl A

Right now it looks like I would have to manually list every interface that's supported by B and stay in the loop with their implementation so I know when they add new ones.

_Originally posted by @M1cha in https://github.com/flatpak/xdg-desktop-portal/issues/1131#issuecomment-1753336843_

**Comment by GeorgesStavracas** [comment]
Have you tried:

```
[preferred]
default=A;B;
```

?

**Comment by ebassi** [comment]
> aka what I had previously

Before the introduction of `portals.conf`, you couldn't "express" anything: the portals determined the exposed interfaces, and in which desktops they worked.

> - Use all the interfaces provided by impl A (default)
> - Use all the interfaces provided by impl B that are not provided by impl A

```
[preferred]
default=A;B
```

**Comment by M1cha** [comment]
> ```
> [preferred]
> default=A;B
> ```
> 
> Should work, since the key is expanded in the same way.

Oh I didn't know that was possible. Did I miss that in the documentation? If not it'd be great if we can add it.

> I mean, yes; that's what you get when you're building your own environment and overriding the default behaviours to match your desired results.

Well that depends on your perspective on how detailed and explicit you want to configure your system.

**Comment by GeorgesStavracas** [comment]
> Oh I didn't know that was possible. Did I miss that in the documentation? If not it'd be great if we can add it.

This is documented in the documentation file you mentioned in the other issue. Closing.
