### ISSUE TITLE
Portal for trash?

### ISSUE THREAD

**Issue by TingPing** [flatpak/xdg-desktop-portal#114]
Currently if you try to trash a file on the host using `gio` it will fail: `gio: file:///foo: Unable to trash file /foo across filesystem boundaries`. Perhaps this makes sense to expose as a portal?

**Comment by noverby** [comment]
Kind of a big deal in GNOME Builder. :)

**Comment by jflesch** [comment]
Same for [Paperwork](https://github.com/openpaperwork/paperwork/issues/703)

**Comment by hadess** [comment]
Did you add gvfs to the D-Bus whitelist, as a work-around?

**Comment by jflesch** [comment]
No but I can try later today. `--talk-name=org.gtk.vfs --talk-name=org.gtk.vfs.*`, right ?

**Comment by hadess** [comment]
That's what I used in totem to get it to talk to gvfs:
https://github.com/flathub/org.gnome.Totem/blob/master/org.gnome.Totem.json#L33

**Comment by TingPing** [comment]
Ah I can confirm that `gio trash` does work with those permissions.

**Comment by jflesch** [comment]
Hm, weird. Doesn't seem to be good enough for Paperwork:

```
% flatpak run "--talk-name=org.gtk.vfs" "--talk-name=org.gtk.vfs.*" work.openpaper.Paperwork//master
(...)
INFO   paperwork_backend.fs           Deleting file:///home/jflesch/papers_test/20171202_1205_19 ...
ERROR  paperwork.frontend.diag        === UNCATCHED EXCEPTION ===
Traceback (most recent call last):
  File "/app/lib/python3.5/site-packages/paperwork_backend-1.2.2-py3.5.egg/paperwork_backend/fs.py", line 326, in rm_rf
    if not f.trash():
GLib.GError: g-io-error-quark: Unable to trash file /home/jflesch/papers_test/20171202_1205_19 across filesystem boundaries (15)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/lib/python3.5/site-packages/paperwork-1.2.2-py3.5.egg/paperwork/frontend/mainwindow/docs.py", line 631, in _on_doc_deleted_from_index
    doc.destroy()
  File "/app/lib/python3.5/site-packages/paperwork_backend-1.2.2-py3.5.egg/paperwork_backend/common/doc.py", line 125, in destroy
    self.fs.rm_rf(self.path)
  File "/app/lib/python3.5/site-packages/paperwork_backend-1.2.2-py3.5.egg/paperwork_backend/fs.py", line 329, in rm_rf
    raise IOError(str(exc))
OSError: g-io-error-quark: Unable to trash file /home/jflesch/papers_test/20171202_1205_19 across filesystem boundaries (15)
ERROR  paperwork.frontend.diag        ===========================
```

(flatpak 0.8.7)

**Comment by hadess** [comment]
My guess is that you don't have access to the ~/ as well, so you're accessing the local file via FUSE. The GIO code needs to be taught about app-local trashes and we'd need the trash backend in gvfs to support those app-local Trashes too.

**Comment by matthiasclasen** [comment]
https://github.com/matthiasclasen/xdg-desktop-portal/tree/trash has a trash portal
https://gitlab.gnome.org/GNOME/glib/tree/trash-portal has portal support for g_file_trash

**Comment by alexlarsson** [comment]
Generally looks good to me, but I made some comments on it. @jhenstridge could you also look?

**Comment by matthiasclasen** [comment]
One thing we discussed on irc: it would be good to make it possible to implement a "quick undo" using this api, by returning some kind of temporary handle that can be passed to a Restore() method.

**Comment by matthiasclasen** [comment]
merged

**Comment by jhenstridge** [comment]
Sorry for the delay.  The only thing I'd be wary of is allowing `O_PATH` file descriptors, as they don't prove access.  They're already blocked for snap clients, but allowed for Flatpaks to support old versions of glib.

If the glib side doesn't create O_PATH descriptors, then there is no compatibility issue, so supporting them on the portal side is untested with possibly unexpected side effects.

As for the non-O_PATH case, a comment suggests it can't be used to check writability of directories.  So do attempts to trash folders work?

**Comment by matthiasclasen** [comment]
I haven't tried trashing directories. I shall do that.
