### ISSUE TITLE
parse_app_info_from_flatpak_info fails with a permission denied error in some conditions

### ISSUE THREAD

**Issue by veluca93** [flatpak/xdg-desktop-portal#1149]
### Operating System

Arch Linux

### XDG Desktop Portal version

1.18

### Desktop Environment

GNOME

### Expected Behavior

parse_app_info_from_flatpak_info does not return an error.

### Current Behavior

parse_app_info_from_flatpak_info fails when trying to read the `/proc/[pid]/root` symlink.

### Steps to Reproduce

1. Configure dbus to allow other users (i.e. root) to send dbus commands to session daemons. For example, add 
```
<busconfig>
  <policy context="mandatory">
    <allow user="root"/>
  </policy>
</busconfig>
```
to `/etc/dbus-1/session-local.conf`
2. Send a request for a screenshot from the `root` user, with a command like `desktop.Screenshot("Screenshot", {"handle_token": f"{my_token}"}, dbus_interface="org.freedesktop.portal.Screenshot")`

### Anything else we should know?

The following patch works around the crash, although of course it probably introduces other issues.

```
diff --git a/src/xdp-utils.c b/src/xdp-utils.c
index b57bfad..9adae08 100644
--- a/src/xdp-utils.c
+++ b/src/xdp-utils.c
@@ -602,25 +602,6 @@ parse_app_info_from_flatpak_info (int pid, GError **error)
   root_fd = openat (AT_FDCWD, root_path, O_RDONLY | O_NONBLOCK | O_DIRECTORY | O_CLOEXEC | O_NOCTTY);
   if (root_fd == -1)
     {
-      if (errno == EACCES)
-        {
-          struct statfs buf;
-
-          /* Access to the root dir isn't allowed. This can happen if the root is on a fuse
-           * filesystem, such as in a toolbox container. We will never have a fuse rootfs
-           * in the flatpak case, so in that case its safe to ignore this and
-           * continue to detect other types of apps.
-           */
-          if (statfs (root_path, &buf) == 0 &&
-              buf.f_type == 0x65735546) /* FUSE_SUPER_MAGIC */
-            return NULL;
-        }
-
-      /* Otherwise, we should be able to open the root dir. Probably the app died and
-         we're failing due to /proc/$pid not existing. In that case fail instead
-         of treating this as privileged. */
-      g_set_error (error, G_IO_ERROR, G_IO_ERROR_FAILED,
-                   "Unable to open %s", root_path);
       return NULL;
     }
```

**Comment by TingPing** [comment]
> Configure dbus to allow other users (i.e. root) to send dbus commands to session daemons.

I'm pretty sure there is just no way to support this. If the daemon doesn't have permissions to read files from another users process... it will always fail.

**Comment by veluca93** [comment]
Why do you say that? We managed to get this to work just fine with the
patch I mentioned in the first message.

**Comment by veluca93** [comment]
> > of course it probably introduces other issues
> 
> The other issue that it introduces could potentially be a security vulnerability. Deleting code that checks for errors in a process that acts as a privilege boundary is something that should only be done when backed up by a careful check that it is not introducing a vulnerability.
> 
> The failure mode with the code deletion that you suggest would be that if a Flatpak, Snap or otherwise sandboxed process can somehow arrange for its root filesystem to be unreadable by xdg-desktop-portal, then xdg-desktop-portal would think it is unprivileged and allow it to do arbitrary things, which would be a sandbox bypass.

That seems fair. Nonetheless, I believe it should _somehow_ be possible to configure xdg-desktop-portal to allow a sufficiently-privileged user (such as root) to execute actions on another user's session. As `root` could read and write memory of the xdg-desktop-portal-using process, I do not believe this would introduce a new security vulnerability.

**Comment by TingPing** [comment]
Root could execute anything as the correct user.

**Comment by veluca93** [comment]
I understand the concerns about the bus.

I would like to remark that I never proposed my patch as a solution. It was
a quick hack that made things work for us, but if I wanted to propose a
real solution I would have done things otherwise (for example, check if the
PID of the calling user is root, and trust the caller unconditionally in
that case would be a better solution that does not have the issue that you
mentioned).
