### ISSUE TITLE
github main page 'About' section leads to Document not found

### ISSUE THREAD

**Issue by darkblaze69** [flatpak/xdg-desktop-portal#1163]
### Operating System

any

### XDG Desktop Portal version

Other

### XDG Desktop Portal version (Other)

any

### Desktop Environment

Other

### Desktop Environment (Other)

any

### Expected Behavior

Should be valid link.

### Current Behavior

Wrong link in about section.

github main page 'About' section leads to 'Document not found' (https://flatpak.github.io/xdg-desktop-portal/portal-docs.html)

![Screenshot from 2023-10-19 12-14-50](https://github.com/flatpak/xdg-desktop-portal/assets/6976920/84c06453-6778-4f85-b1e1-3cb13b18242e){height=50px}

### Steps to Reproduce

* open https://github.com/flatpak/xdg-desktop-portal
* open link in About section

**Comment by GeorgesStavracas** [comment]
Updated
