### ISSUE TITLE
file access issue in Email portal

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/xdg-desktop-portal#118]
i just realized that ComposeEmail has the same file access issue as the original OpenURI call had. We need to replace it with a different api that takes fds for the files to attach :-(

**Comment by matthiasclasen** [comment]
See https://github.com/flatpak/xdg-desktop-portal/pull/119

**Comment by mariospr** [comment]
Looks good to me, with a very minor suggestion in the first commit. I've also filed https://github.com/flatpak/flatpak-xdg-utils/issues/3 not to forget about updating flatpak's own xdg-utils
