### ISSUE TITLE
[1.18.0-2] Unable to capture entire screen with WebRTC

### ISSUE THREAD

**Issue by acro5piano** [flatpak/xdg-desktop-portal#1181]
### Operating System

Arch Linux

### XDG Desktop Portal version

1.18

### Desktop Environment

wlroots (sway)

### Expected Behavior

Able to capture entire screen on any WebRTC supported browsers

### Current Behavior

**Unable** to capture entire screen

### Steps to Reproduce

1. Go to https://mozilla.github.io/webrtc-landing/gum_test.html
2. Click "Screen capture"
3. Not able to select "Window" and "Entire Screen". When you attempt to click them, the focus goes back to "Chromium Tab" immediately.

### Anything else we should know?

I found these errors in chromium log:

```
session: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.ScreenCast” on object at path /org/freedesktop/portal/desktop
```

The current workaround is to downgrade to 1.16.0. 

```
sudo pacman -U /var/cache/pacman/pkg/xdg-desktop-portal-1.16.0-3-x86_64.pkg.tar.zst
```

I suppose other older versions also work.

**Comment by acro5piano** [comment]
@GeorgesStavracas I tried bunch of tools, but none of them worked:

- `zoom`: Probably zoom's problem, as it crashes and won't work on 1.16 too
- `kooha`: with the same error

The following is kooha's log.

```
Failed to start recording

Caused by:
    0: Check out <a href="https://github.com/SeaDve/Kooha#-it-doesnt-work">It Doesn't Work page</a> for help.
    1: Failed to create ScreencastSession
    2: Failed to create session
    3: Failed to call `CreateSession` with parameters: Variant { ptr: 0x56460e1c04e0, type: VariantTy { inner: "(a{sv})" }, value: "({'handle_token': <'kooha_1'>, 'session_handle_token': <'kooha_0'>},)" }
    4: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.ScreenCast” on object at path /org/freedesktop/portal/desktop
```

Thanks

**Comment by acro5piano** [comment]
I'm not sure what "backend" exactly mean, so let me share my entire stack:

- xdg-desktop-portal-wlr
- wireplumber (0.4.15-1)
- pipewire (1:0.3.84-1)
- pipewire-audio (1:0.3.84-1)
- pipewire-pulse (1:0.3.84-1)
- gst-plugin-pipewire (1:0.3.84-1)

**Comment by GeorgesStavracas** [comment]
What's the config file you're using? See `man 5 portals.conf` for more information

**Comment by tytan652** [comment]
Sway apparently does not set `XDG_CURRENT_DESKTOP` which prevent xdg-desktop-portal to find the config file provided by Arch Linux package.

**Comment by acro5piano** [comment]
Oh really, I didn't know the config file should be updated on user land! That makes sense.

However, I remember it was not working even if I set `XDG_CURRENT_DESKTOP` manually before starting wayland session. I'll try to confirm the bahavior it later.

**Comment by GeorgesStavracas** [comment]
@acro5piano have you been able to confirm that using a config file makes things work for you?

**Comment by acro5piano** [comment]
@GeorgesStavracas OK, I'm cheking it.

**Comment by acro5piano** [comment]
I read the Arch wiki and realized what `config` means. Sorry for bothering you so far.

My config files are the following:

`find /usr/share/xdg-desktop-portal/ -type f | xargs head -100`

```ini
==> /usr/share/xdg-desktop-portal/portals/wlr.portal <==
[portal]
DBusName=org.freedesktop.impl.portal.desktop.wlr
Interfaces=org.freedesktop.impl.portal.Screenshot;org.freedesktop.impl.portal.ScreenCast;
UseIn=wlroots;sway;Wayfire;river;phosh;Hyprland;

==> /usr/share/xdg-desktop-portal/wlr-portals.conf <==
[preferred]
default=wlr

==> /usr/share/xdg-desktop-portal/sway-portals.conf <==
[preferred]
default=gtk
org.freedesktop.impl.portal.Screencast=wlr
org.freedesktop.impl.portal.Screenshot=wlr

```

```
~> ls ~/.config/xdg-desktop-portal/
ls: cannot access '/home/kazuya/.config/xdg-desktop-portal/': No such file or directory

```

**Comment by acro5piano** [comment]
I'm experimenting the behavior by building it on my own. I build 1.16.0 on my machine and run it. However, I had the same error.

So my issues might not be introduced on 1.18, but the build configuration change might affect it. I'm looking it further.

The log

```
~> meson setup . _build && meson compile -C _build/
... [165/165] Linking target tests/test-portals

~> ./_build/src/xdg-desktop-portal --version
xdg-desktop-portal 1.16.0

~> ./_build/src/xdg-desktop-portal --replace
```

**Comment by acro5piano** [comment]
I took a look at PKGBUILD for Pacman and suppose `xdg-desktop-portal-impl` might be related. However, I cannot dig deeper with my knowledge and time.

- https://gitlab.archlinux.org/archlinux/packaging/packages/xdg-desktop-portal/-/blob/1.16.0-3/PKGBUILD?ref_type=tags#L56
- https://gitlab.archlinux.org/archlinux/packaging/packages/xdg-desktop-portal/-/blob/1.18.0-2/PKGBUILD?ref_type=tags#L58

**Comment by GeorgesStavracas** [comment]
I'm going to close this issue as it is unactionable in its current form, but if you find supporting evidence for this bug, please reopen.

**Comment by acro5piano** [comment]
Cleaning up all files completely and re-install everything fixed the issue.

# Delete everything

```
systemctl --user disable pipewire wireplumber xdg-desktop-portal xdg-desktop-portal-wlr
systemctl --user stop pipewire wireplumber xdg-desktop-portal xdg-desktop-portal-wlr
sudo pacman -Rcs xdg-desktop-portal xdg-desktop-portal-wlr pipewire wireplumber sway xorg
sudo rm /usr/lib/systemd/user/pipewire.service /usr/lib/systemd/user/wireplumber.service /usr/lib/systemd/user/wireplumber@.service
```

# Install everything again

```
sudo pacman -S xdg-desktop-portal xdg-desktop-portal-wlr pipewire wireplumber xorg-xwayland
systemctl --user restart pipewire wireplumber xdg-desktop-portal xdg-desktop-portal-wlr
```

# footnotes

This troubleshooting guide helped me a lot: https://github.com/emersion/xdg-desktop-portal-wlr/wiki/%22It-doesn't-work%22-Troubleshooting-Checklist
