### ISSUE TITLE
Can't use the eyedropper tool from Chrome DevTools

### ISSUE THREAD

**Issue by sanzc** [flatpak/xdg-desktop-portal#1193]
### Operating System

Arch Linux

### XDG Desktop Portal version

1.18

### Desktop Environment

KDE

### Expected Behavior

Be able to open the eyedropper tool and pick a color

### Current Behavior

KDE Wayland:
When clicking on the eyedropper tool, a XDG Portal window pops up asking to share the screen and closes immediately.

KDE X11:
When clicking on the eyedropper tool, I'm able to use the tool but it won't pick the right color and the color preview shows glitched colors.

### Steps to Reproduce

1. Open a chrome based browser
2. Open the devtools and click on the "Elements" tab then "Styles"
3. Look for a CSS color rule and toggle the color picker
4. Click on the eyedropper tool

### Anything else we should know?

It works fine with Firefox and Falkon. I tried with Brave (flatpak and AUR package), Chrome and Chromium and none of them worked. I'm a noob with Linux but I looked at journalctl and the browser logs but it didn't seem like any error was displayed.

**Comment by GeorgesStavracas** [comment]
Hey, thanks. I can reproduce this, but `dbus-monitor` shows that Chromium tries to use the screencast portal (!!!) to pick the color. Chromium is using the wrong portal for this! It should be using the Screenshot portal, which provides a method for color picking. Please report this to Chromium developers.
