### ISSUE TITLE
Auto-activation of the frontend doesn't pick up env variables

### ISSUE THREAD

**Issue by grulja** [flatpak/xdg-desktop-portal#120]
When xdg-desktop-portal is launched automatically by systemd, it doesn't use env variables so when you rely on XDG_CURRENT_DESKTOP you are not able to tell which backend to use. Launching xdg-desktop-portal manually it uses correct backend (KDE in my case), but when it is started automatically it uses fallback which is GTK frontend in my case.

**Comment by matthiasclasen** [comment]
This is not an xdg-desktop-portal problem, but a session setup issue. Whatever sets up your session needs to make sure that the dbus activation environment contains all the relevant environment variables.

**Comment by grulja** [comment]
I think I found where is the problem. In startkde (script we use for session setup) we use **dbus-update-activation-environment --systemd --all** which apparently used to work in past and the same command is also mentioned on the wiki page for dbus-update-activation-environment [1], but it doesn't seem to work now as it is missing environment assignments for --systemd parameter. Now what to do, either pass all the environments we want to export or report this to systemd if this is something what should work as it is or at least to know if this has been broken in past and not it was just fixed.

[1] - https://dbus.freedesktop.org/doc/dbus-update-activation-environment.1.html

**Comment by grulja** [comment]
My fault, I had some faulty variables set, preventing to succesfuly export my other variables.
