### ISSUE TITLE
[FileChooser] No (documented) way to close an existing file picker.

### ISSUE THREAD

**Issue by emilio** [flatpak/xdg-desktop-portal#1225]
### Operating System

Arch Linux

### XDG Desktop Portal version

1.18

### Desktop Environment

Other

### Desktop Environment (Other)

not relevant

### Expected Behavior

Should be able to hide an already-open file chooser portal.

### Current Behavior

You can only do it in GNOME, which implements a `Close` method on their file chooser portal that GTK uses (see [here](https://gitlab.gnome.org/GNOME/gtk/-/blob/bcab0e4254ace10bb2b3de8d4c10bc25ef3368ce/gtk/gtkfilechoosernativeportal.c#L219-222) for gtk4, and [here](https://gitlab.gnome.org/GNOME/gtk/-/blob/65b0c289b03680b825101b68a5c4b11e99e31b43/gtk/gtkfilechoosernativeportal.c#L187-190) for the gtk3 equivalent).

However, that's not documented nor implemented in other portals. Should it be properly documented / standardized?

### Steps to Reproduce

N/A (I mean, I could build a test-case if wanted but the description should be pretty self-explanatory)

**Comment by emilio** [comment]
> ### Anything else we should know?
> 
> _No response_

Actually Github ate my response here. This would be very useful because we (Firefox) have a use case to hide already open file pickers (to prevent spoofing, can talk more about it if needed).

It'd be great if this worked across platforms but right now there's no way of making it work on e.g. KDE if you are using a flatpak or what not.

**Comment by emilio** [comment]
cc: @stransky @xhorak @canadahonk

**Comment by GeorgesStavracas** [comment]
There is nothing special with how the File Chooser portal creates requests. Using any one of the D-Bus methods of the File Chooser portal will create a request object on the bus, on which you can call the Close() method.

Backends need to listen to the CLose signal on the request object, and cancel the operation when it's emitted. The GNOME backend [does this for the File Chooser portal](https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/blob/main/src/filechooser.c?ref_type=heads#L482-515), and other portals too.

If KDE or other backends don't properly cancel their operations when the request is closed, strictly speaking, this is a backend bug that needs to be fixed there.

**Comment by emilio** [comment]
Ah I was just looking at the FileChooser docs, I didn't realise Close was defined more generically in https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.portal.Request.html#org-freedesktop-portal-request-close

Thanks! Then this is not a bug here.

**Comment by emilio** [comment]
https://bugs.kde.org/show_bug.cgi?id=477479 for the KDE bug

**Comment by GeorgesStavracas** [comment]
Thank you for reporting this to the KDE backend :slightly_smiling_face:
