### ISSUE TITLE
Username is given when app writing to its own path

### ISSUE THREAD

**Issue by Mikenux** [flatpak/xdg-desktop-portal#1235]
### Operating System

Fedora Linux 39 Workstation

### XDG Desktop Portal version

1.18

### XDG Desktop Portal version (Other)

1.18.2

### Desktop Environment

GNOME

### Expected Behavior

The username is not given.

### Current Behavior

The username is given.

I thought portals aren't supposed to give out the username. Besides, there is an account portal for this.

### Steps to Reproduce

1. Install Workbench
2. Click on `Library` then the `Rust` label in `Welcome`.
3. Click on Run. Install needed extensions if reported by Workbench, restart the app and repeat the steps.

See, in the console of the main window:
`Compiling demo v1.0.0 (/home/username/.var/app/re.sonny.Workbench/data/...`

**Comment by GeorgesStavracas** [comment]
The unix username is not secret information. Any app can call `getlogin()` or similar to get the username. It's also not an information leak, because apps can't do much with that.

The Accounts portal gives more sensitive information such as the real user name, the profile picture, etc.

**Comment by Mikenux** [comment]
What I'm thinking of is that an app developer could get the username and then guess who it is on the internet, assuming users use the same type of username, depending on the places (on the Internet).

**Comment by GeorgesStavracas** [comment]
Hiding the username is outside of the scope of portals. The username is user-controllable, so users who are concerned about this case should set a different username during initial setup of the system.

**Comment by Mikenux** [comment]
> The username is user-controllable, so users who are concerned about this case should set a different username during initial setup of the system.

For what it is worth, not all users have the privacy manual. What is obvious to you is not obvious to everyone.
