### ISSUE TITLE
Dark theme doesn't apply when running a root instance of applications from normal user boot

### ISSUE THREAD

**Issue by fulalas** [flatpak/xdg-desktop-portal#1237]
### Operating System

Slackware 15.0 (but it seems it applies to any distro)

### XDG Desktop Portal version

1.17

### XDG Desktop Portal version (Other)

1.17.1+

### Desktop Environment

GNOME

### Desktop Environment (Other)

GNOME 45.x

### Expected Behavior

Nautilus should show up in dark theme.

### Current Behavior

Nautilus shows up in light theme.

### Steps to Reproduce

1. make sure you have your root account dconf file set to use dark theme
2. log in as normal user
3. go to the terminal, run `su` and put your credentials
4. from the same terminal call `nautilus`
5. nautilus should show up in dark mode but in shows up in light mode

### Anything else we should know?

After seeing this issue I decided to build 1.17.0 and this issue doesn't happen. I built 1.17.1 and then the issue happens. I kept building newer versions and they all suffer from the same issue.

Not sure if this helps, but the problem is precisely in `/usr/libexec/xdg-desktop-portal`, meaning if I install 1.18.2 and revert just this binary to 1.17.0 the issue doesn't happen.

**Comment by GeorgesStavracas** [comment]
> 3. go to the terminal, run `su` and put your credentials
> 4. from the same terminal call `nautilus`

That's not supported, and it's probably the cause of this issue.

**Comment by GeorgesStavracas** [comment]
@smcv as the resident D-Bus expert, do graphical apps as sudo expected to be able to use xdg-desktop-portal?

**Comment by ebassi** [comment]
Incidentally, you don't need to run Nautilus as super user; that's what the `admin://` scheme is for.

**Comment by GeorgesStavracas** [comment]
Thanks.

Given the explanations above, this is situation is not supposed to work, which makes this issue report invalid.

**Comment by fulalas** [comment]
I understand that this is not your use case, but it doesn't apply to everybody, right? Please notice that this is not a feature request, but a regression report. Something in 1.17.1 broke a useful feature, but no changelog explaining why has been provided (AFAIK), and when someone reports an issue you close it because you don't agree with the use case.

This issue can be replicated using `pkexec`. And, yes, I know about `admin://`, but it doesn't address many use cases that have been working for years. For example, when in an admin instance of nautilus if the user:
1. opens a terminal from inside it, this terminal won't be loaded in admin mode
2. wants to execute a `pkexec` operation it will ask for super user password again
3. right clicks on a left panel folder and select to open a new tab/window it will not be loaded in admin mode
4. believe me, there are many more examples

I appreciate your work and I understand the time constraints. I'm also an open source developer and have been contributing to many projects -- actually, that's the reason why I'm reporting this since I don't use this project. Not sure if you guys see this, but it seems this behavior of yours is one of the reasons why so many people get sad about GNOME and its side projects. As Linus Torvalds once said, the whole _we know best_ thing can be toxic.

No hard feelings. I hope you understand :)
