### ISSUE TITLE
xdg-desktop-portal tries to access non-existing org.freedesktop.impl.portal.Request

### ISSUE THREAD

**Issue by Sodivad** [flatpak/xdg-desktop-portal#1241]
### Operating System

Neon 22.04

### XDG Desktop Portal version

Git

### XDG Desktop Portal version (Other)

main

### Desktop Environment

KDE

### Expected Behavior

`xdg-desktop-portal` should not try to access non-existent object/give the impl a chance to create them

### Current Behavior

I can see that for  requests an app makes xdg-desktop-portal  tries to read properties of a non-existing Request. The event flow is as follows with `org.freedesktop.portal.FileChooser.OpenFile` as an example

-  `org.freedesktop.portal.FileChooser.OpenFile` is called
- `xdg-desktop-portal` makes a call to the  impl  at  `/org/freedesktop/portal/desktop/request/connection/token` `org.freedesktop.DBus.Properties.GetAll('org.freedesktop.impl.portal.Request',)`
- `xdg-desktop-portal` calls org.freedesktop.impl.portal.FileChooser.OpenFile
- `xdg-desktop-portal` send the method return of the original `org.freedesktop.portal.FileChooser.OpenFile`

### Steps to Reproduce

- Use a flatpaked app or make a call manually 

### Anything else we should know?

I can see this order of event flows with multiple interfaces. At least FileChooser, Screenshot and Screencast

**Comment by GeorgesStavracas** [comment]
Is this causing any problem? GDBusProxy initialization calls `org.freedesktop.DBus.Properties.GetAll()` on the object during construction, but the `org.freedesktop.impl.portal.Request` interface does not have any properties, so this ends up never returning nothing of interest.

**Comment by Sodivad** [comment]
> Is this causing any problem? 

Not to my knowledge. I  just keep spotting this in bustle 

>  but the org.freedesktop.impl.portal.Request interface does not have any properties, so this ends up never returning nothing of interest.

Even if it it had properties, It would fail as the Request object does not exist yet.

**Comment by GeorgesStavracas** [comment]
So it's not a critical issue or anything. Cool. In any case, it would be good to figure it out.

**Comment by GeorgesStavracas** [comment]
Could you please verify if https://github.com/flatpak/xdg-desktop-portal/pull/1244 fixes that for you, without introducing any regressions?
