### ISSUE TITLE
Default applications portal?

### ISSUE THREAD

**Issue by jhenstridge** [flatpak/xdg-desktop-portal#126]
It is fairly common for a web browser or email client to want some way to set themselves as the default application for the user.  It is also pretty clear that a sandboxed application shouldn't be able to unilaterally change the user's default application settings.

Would it make sense to add a portal interface for this?  Perhaps something like this:

 * `IsDefault(mime_type, desktop_id) -> bool`
    Returns true if the given desktop ID is the default for the given mime type.  The portal may return false if the sandboxed app does not control the given desktop ID.

 * `SetDefault(mime_type, desktop_id)`
    After confirming with the change with the user, set the given desktop ID as default handler for the given mime type.  The portal will refuse to make the change if the sandboxed app does not control the given desktop ID.  The portal may remember if the user's decision if they reject the change (to handle badly behaved apps that repeatedly try to change the settings).

It might need a bit more nuance though: a browser will probably want to set a number of `x-scheme-hanlder/*` defaults (http, https, etc), but the user should only be prompted once.

**Comment by matthiasclasen** [comment]
I don't think so. it is generally just annoying if applications are pushy about this. They should announce what mime types they support, and leave choice of default handlers to the desktop and the user.

**Comment by TingPing** [comment]
I think the Windows 10 solution to this is actually decent, instead of allowing applications constantly request it the OS will, at install time of a new handler, ask if you want it to be default.
