### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by AsciiWolf** [flatpak/xdg-desktop-portal#127]
I think it could be a good idea to release a new version of _xdg-desktop-portal_ and _xdg-desktop-portal-gtk_. The last version was released in June and there were many translation updates and other fixes since then.

**Comment by mariospr** [comment]
I think you're right, let's tag @matthiasclasen here as he's who does the releases.

**Comment by AsciiWolf** [comment]
Any news?

**Comment by AsciiWolf** [comment]
Thanks!
