### ISSUE TITLE
[Bug] Flameshot doesn't work correctly besides the fact that the Flatpak version doesn't work at all

### ISSUE THREAD

**Issue by lxwulf** [flatpak/xdg-desktop-portal#1317]
### Operating System

Fedora 39

### XDG Desktop Portal version

Other

### XDG Desktop Portal version (Other)

1.18.2

### Desktop Environment

GNOME

### Expected Behavior

Working `Flameshot` application with shortcut key (`PrtScr`).

### Current Behavior

As already mentioned [here](https://github.com/flatpak/xdg-desktop-portal/issues/649#issuecomment-2017421603) as example, `Flameshot` doesn't work correctly. The system is updated to the newest packages. 

From the terminal, I can start `Flameshot` with `flameshot &`. I can start it with a click on the status bar icon. The shortcut key, in my case `PrtScr` doesn't work. It spawns a new process with again says `Unable to capture screen`. No permissions asking or something else from GNOME.

The `flatpak` version of `Flameshot` doesn't work at all. It says `Unable to capture screen`. Also, without any permission asking from GNOME.

Additional references:
[Flameshot issue 2868](https://github.com/flameshot-org/flameshot/issues/2868)
> They say the problem relays on the `xdg-desktop-portal` together with GNOME. I can't prove this exactly just wanna to help to resolve this problem. :v: 

### Steps to Reproduce

**Flatpak version:**

1. Install it with `flatpak install flameshot`
2. Execute it.
3. Click on the icon in the status bar.
4. Notification appears `Unable to capture the screen`.

**RPM version:**

1. Install it with `dnf install flameshot`
2. Execute it from the app menu.
3. Click on the icon in the status bar.
4. Notification appears `Unable to capture the screen`.
5. Kill the `flameshot process`.
6. Open a new terminal and execute `flameshot &`.
7. Click on the icon in the status bar.
8. You may now get asked for permissions, ofcourse we need to allow this.
9. Now you can use `flameshot` with a click on the icon in the status bar.

> Shortcut setup still doesn't work.

**Comment by Mikenux** [comment]
Hello @lxwulf!

It is known. See https://github.com/flatpak/xdg-desktop-portal/issues/1093

**Comment by lxwulf** [comment]
Okay, thank you, do you have any updates or information how it goes? I still have no working screenshot application and in the link of you is also not that much information. :confused:

**Comment by Mikenux** [comment]
Unfortunately, I don't know anything.

**Comment by lxwulf** [comment]
Are there any updates to this unhappy situation?

**Comment by xalt7x** [comment]
For Flameshot Flatpak on GNOME Wayland, the user currently needs to set the Screenshot Portal permission manually:
`flatpak permission-set screenshot screenshot org.flameshot.Flameshot yes`
See https://github.com/flameshot-org/flameshot/issues/2868 ; https://github.com/tchx84/Flatseal/pull/728

**Comment by lxwulf** [comment]
Many thanks for mentioning the solution and possible explanation of the problematic situation!

It does work now with the mentioned command.

Thank you!

**Comment by gutopardini** [comment]
I hit similar GNOME Wayland limitations with Flameshot and ended up building WayShot, a small GNOME-focused tool that uses the native GNOME screenshot flow and then opens an editor automatically.
It may be useful for people specifically on GNOME + Wayland who need a workaround while these portal/app-id issues remain unresolved: [wayshot](https://github.com/gutopardini/wayshot)
Not trying to derail the issue — just sharing it as an alternative for this specific GNOME Wayland case.
