### ISSUE TITLE
xdg-activation support in OpenURI portal is pretty much broken

### ISSUE THREAD

**Issue by ilya-fedin** [flatpak/xdg-desktop-portal#1329]
### Operating System

NixOS

### XDG Desktop Portal version

1.18

### Desktop Environment

KDE

### Expected Behavior

I expect xdg-desktop-portal to override the [Gio::AppLaunchContext::get_startup_notify_id](https://docs.gtk.org/gio/method.AppLaunchContext.get_startup_notify_id.html) vfunc that does the right ([1](https://gitlab.gnome.org/GNOME/glib/-/blob/main/gio/gdesktopappinfo.c#L2952), [2](https://gitlab.gnome.org/GNOME/glib/-/blob/main/gio/gdesktopappinfo.c#L3134)) thing...

### Current Behavior

g_app_launch_context_setenv is used that doesn't work with dbus activation... And gtk seem to [lack](https://gitlab.gnome.org/GNOME/gtk/-/blob/main/gdk/gdk.c#L152-170) non-dbus xdg-activation interop support (reading only DESKTOP_STARTUP_ID but not XDG_ACTIVATION_TOKEN). So it's completely broken when starting gtk applications, both via dbus and process execution.
https://github.com/flatpak/xdg-desktop-portal/blob/efd23749cea121deccdf6df9c2461aef494c5dc7/src/open-uri.c#L278

### Steps to Reproduce

1. Use OpenURI/OpenFile with activation token set

**Comment by GeorgesStavracas** [comment]
Fixed by #1332
