### ISSUE TITLE
camera: After dialog timeout the permission will be set to "no"

### ISSUE THREAD

**Issue by A6GibKm** [flatpak/xdg-desktop-portal#1336]
### Operating System

Fedora Silverblue 40

### XDG Desktop Portal version

1.18

### XDG Desktop Portal version (Other)

xdgp-gnome

### Desktop Environment

GNOME

### Expected Behavior

When the user does not interact with the permission  dialog, nothing should happen.

### Current Behavior

After around 25 seconds the permission will be set to `no`. If the user clicks "Allow" on the dialog, the permission will still remain as "no".

### Steps to Reproduce

```sh
flatpak permission-reset org.gnome.Snapshot
flatpak permission-show org.gnome.Snapshot # is empty
flatpak run org.gnome.Snapshot # and wait for 30 secons
# click allow on the dialog if it appears, otherwise do nothing
flatpak permission-show org.gnome.Snapshot
# Table   Object App                Permissions Data
# devices camera org.gnome.Snapshot no          0x00
```

### Anything else we should know?

On bustle I see org.freedesktop.impl.portal.Access.AccessDialog with reply body  `"Timeout was reached"` then a call to `org.freedesktop.impl.portal.PermissionStore.SetPermission` with `["no"]`.

**Comment by GeorgesStavracas** [comment]
Please file this issue against xdg-desktop-portal-gnome

**Comment by A6GibKm** [comment]
Done, thanks https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/issues/128.
