### ISSUE TITLE
OpenURI portal can crash when failing to register URI for sandboxed handler 

### ISSUE THREAD

**Issue by mariospr** [flatpak/xdg-desktop-portal#134]
We found quite an usual case in Endless that led to a crash in the internals of GIO because the OpenURI portal would try open and URI handled by a sandboxed application (Visual Studio), which did not have access to such URI, thus failing to register the path with the document portal (https://github.com/flatpak/xdg-desktop-portal/blob/master/src/open-uri.c#L195).

And because no check is done after that, a GList of one single element, which happened to be NULL, got passed to g_app_info_launch_uris(), which ended up blowing up internally in `expand_macro()`, due to trying to reference that NULL when expanding the macro arguments from the desktop file.

There are a [couple of things that can be fixed in GLib](https://bugzilla.gnome.org/show_bug.cgi?id=791337
) for that (I already have a WIP branch, will submit it for review there later), but regardless I think the portal could use some extra checks here to prevent this situation.

**Comment by mariospr** [comment]
Pull request ready for review here: https://github.com/flatpak/xdg-desktop-portal/pull/135

**Comment by mariospr** [comment]
(pressed the wrong button, sorry for the closing - reopening dance)

**Comment by pwithnall** [comment]
#135 has been merged, so I guess this can be closed.
