### ISSUE TITLE
Brave (Chromium) failing to render in 1.18.4

### ISSUE THREAD

**Issue by defunctl** [flatpak/xdg-desktop-portal#1346]
### Operating System

Manjaro (arch)

### XDG Desktop Portal version

1.18

### XDG Desktop Portal version (Other)

1.18.4

### Desktop Environment

GNOME

### Expected Behavior

Running Brave (or Chromium) with ozone auto or wayland should work, e.g.

```shell
brave --enable-features=UseOzonePlatform --ozone-platform=wayland
```

### Current Behavior

Creates visual artifacts, browser never renders even gnome-session and gnome-shell crashed and logged me out, but that could be unrelated. The brave processes are running the background.

It runs just fine forcing x11 with:

```shell
brave --enable-features=UseOzonePlatform --ozone-platform=x11
```

### Steps to Reproduce

Running Gnome 46/nvidia proprietary drivers.

1. Update to xdg-desktop-portal v1.18.4
2. Run `brave --enable-features=UseOzonePlatform --ozone-platform=wayland`
3. Observe issues
...

### Anything else we should know?

**Downgrading to xdg-desktop-portal v1.18.3** and running the following works just fine:

```shell
brave --enable-features=UseOzonePlatform --ozone-platform=wayland
```

- Nvidia driver version: 550.76
- Brave version: 1.65.114
- xdg-desktop-portal-gnome 46.0-1
- xdg-desktop-portal-gtk 1.15.1-1

I'm using 3 monitors, in case that matters.

**Comment by GeorgesStavracas** [comment]
There are only three commits between 1.18.4 and 1.18.3, could you please check which commit is responsible for the regression?

**Comment by defunctl** [comment]
@GeorgesStavracas what's the best way to go about that?

Modify a PKGBUILD and install for each commit hash?

**Comment by GeorgesStavracas** [comment]
It depends on your distro, you can modify and build the packages, or you can just build the project manually using meson and ninja.

**Comment by defunctl** [comment]
Alright, I tried each commit and I guess I was mistaken. Even on v1.18.3 it still exists if ozone platform is auto or wayland.

Most likely a Chromium bug I guess?

![image](https://github.com/flatpak/xdg-desktop-portal/assets/1066195/4971b19a-0cf1-4d37-b45c-7e282e26fc55)

**Comment by GeorgesStavracas** [comment]
So according to Flathub, there was a Chromium update yesterday. I just received this update and it also broke for me. I think this Chromium is broken somehow? Can you try downgrading Chromium / Brave on your end and seeing if it works again?

**Comment by defunctl** [comment]
https://github.com/brave/brave-browser/issues/37716

Yeah, I found this as well, users downgraded and everything is working for them. Likely a chromium bug.

I thought it was this because I hadn't rebooted since I updated brave.

**Comment by GeorgesStavracas** [comment]
Okay, let's close this one then, thanks

**Comment by defunctl** [comment]
Thanks, George.

Also, confirmed downgrading to Brave 1.64.122 resolves the issue for now.

Sorry about the bad bug report.
