### ISSUE TITLE
Notifications display empty screen (looks like a guake termnal)

### ISSUE THREAD

**Issue by superuser-miguel** [flatpak/xdg-desktop-portal#1351]
### Operating System

Fedora 40

### XDG Desktop Portal version

1.18

### Desktop Environment

GNOME

### Expected Behavior

Show notification only

### Current Behavior

![2024-04-27_19-57-54](https://github.com/flatpak/xdg-desktop-portal/assets/16271056/a92e6378-5e39-4b40-bf2b-22ca20c5829d)
As shown in this screenshot, this happens during notifications. Files is shown here.

Just occurred with Thunderbird while writing this message. . . Thunderbird sending notification of alarm.

![2024-04-27_20-01-15](https://github.com/flatpak/xdg-desktop-portal/assets/16271056/57a57191-28ff-4d44-badc-ce84f97e6771)

### Steps to Reproduce

1. Reproducible with programs sending system notifications
2.
3.
...

**Comment by GeorgesStavracas** [comment]
This is not a bug in xdg-desktop-portal, as xdg-desktop-portal has no user interface. Please report it against GNOME Shell.
