### ISSUE TITLE
Type of session_handle in the response of CreateSession differs from documentation

### ISSUE THREAD

**Issue by kb-1000** [flatpak/xdg-desktop-portal#1359]
### Operating System

Fedora 40

### XDG Desktop Portal version

1.18

### Desktop Environment

KDE

### Expected Behavior

It should return an object path as specified in the documentation (`o` type)

### Current Behavior

It returns a string (`s` type)

### Steps to Reproduce

1. Call CreateSession on RemoteDesktop, ScreenCast, GlobalShortcuts, or CreateMonitor on Inhibit
2. Listen for the Response signal
3. Look at the type of the session_handle

**Comment by bilelmoussaoui** [comment]
See https://github.com/bilelmoussaoui/ashpd/blob/master/src/desktop/session.rs#L115-L151 for context
