### ISSUE TITLE
`Ignoring invalid max threads value 4294967295 > max (100000).`

### ISSUE THREAD

**Issue by paulmenzel** [flatpak/xdg-desktop-portal#1363]
### Operating System

Debian sid/unstable

### XDG Desktop Portal version

1.18

### Desktop Environment

GNOME

### Expected Behavior

No warnings/errors in the log.

### Current Behavior

The journal contains:

    xdg-document-portal[2075]: Ignoring invalid max threads value 4294967295 > max (100000).

### Steps to Reproduce

1. Run `journalctl -b`.

### Anything else we should know?

    $ LANG= dpkg -l xdg-desktop-portal
    Desired=Unknown/Install/Remove/Purge/Hold
    | Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
    |/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
    ||/ Name               Version      Architecture Description
    +++-==================-============-============-===============================================
    ii  xdg-desktop-portal 1.18.4-1     amd64        desktop integration portal for Flatpak and Snap

**Comment by paulmenzel** [comment]
It looks like the message is coming from *libfuse3-3* 3.14.0-6, but the reason is

https://github.com/libfuse/libfuse/blob/3f65bb699cd2f0afe2b9519c39d29922229f2168/lib/fuse_loop_mt.c#L38C1-L39C52

If the value could be arbitrarily large, it could be just increased? The macro was defined in merge/pull request https://github.com/libfuse/libfuse/pull/654, so @bsbernd, do you have an idea?

**Comment by bsbernd** [comment]
Currently on vacation and typing on my phone. This looks like an uninitialized value 4294967295? Or actually -1, i.e. not correctly initialized?

**Comment by paulmenzel** [comment]
You are right. It’s probably a [libfuse3 issue fixed in 3.14.1](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1037410#18) but Debian sid/unstable only ships 3.14.0.

**Comment by bsbernd** [comment]
Not sure if it is libfuse - can you provide more details how to get it and what is the application?  I can only check next week - on vacation.

**Comment by paulmenzel** [comment]
On Debian sid/unstable, I am logging into GNOME (with X.Org) and then do `journalctl --user -b` and see the error message.

**Comment by bsbernd** [comment]
That is for sure a bug in libfuse and I don't think fixed in the current version. The warning itself is harmless, though.
