### ISSUE TITLE
Add Slovenian (sl) l10n

### ISSUE THREAD

**Issue by filmsi** [flatpak/xdg-desktop-portal#1400]
### Operating System

Ubuntu

### XDG Desktop Portal version

1.18

### Desktop Environment

GNOME

### Expected Behavior

Slovenian should be used.

### Current Behavior

It doesn't exist yet.

### Steps to Reproduce

1.
2.
3.
...

### Anything else we should know?

[sl.zip](https://github.com/user-attachments/files/16403905/sl.zip)

**Comment by filmsi** [comment]
The translation is provided by the Slovenian GNOME l10n team.

**Comment by filmsi** [comment]
So, Georges, can you help?

**Comment by GeorgesStavracas** [comment]
Unfortunately, I cannot. There are currently no plans of integrating XDG Desktop Portal with translation platforms.

You can read more on how to create a pull request here: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

It's not that difficult, and other translators routinely do that.

Thanks

**Comment by filmsi** [comment]
This is like requiring of all programmers in order to check in their changed or new UI string to provide with it all 200+ world language translations. Would you be able to do that? No, you wouldn't.

OK, so now I will start butchering your git with invalid pull requests ...

**Comment by filmsi** [comment]
No, I will not do this, I don't know how to create a new branch.
I will open a new issue for you to start using transifex or weblate for translation process.
You do not deserve your project to be localized in any language for now.
