### ISSUE TITLE
Screenshot API needs to be color-managed

### ISSUE THREAD

**Issue by Jehan** [flatpak/xdg-desktop-portal#142]
"RGB" without any attached profile is just meaningless data. They are just numbers which basically could mean any color (but well we have an ok-ish approximation). If a display is not color-managed, this is not much of a problem since the colors are approximate from the start.

But if the displays are color-managed, then pixel values have meaning and you must return the profile associated to the display (if there are several displays, that means several profiles for several images).
Otherwise you are basically returning false value (i.e. we are talking about a bug here; this is not an improvement discussed here: you are not returning the right colors => API is broken).

These are the details which would make the XDG-desktop portal (and any desktop which would implement it, like GNOME) really adapted to graphics professional. :-)

**Comment by Jehan** [comment]
For info, right now in GIMP code for screenshots using dbus portals (for all desktops), we have FIXME comments to figure out the color profiles, waiting for implementations.

This means that right now, our screenshot are actually *really* working (returning the right colors) only for X11, Windows and MacOS, but screenshot colors are returned wrong for all the API implementations for Wayland and portals (GNOME, KDE and XDG).

**Comment by matthiasclasen** [comment]
> "RGB" without any attached profile is just meaningless data

That is somewhere between willful misrepresentation and outright untruth.

**Comment by Jehan** [comment]
>>     "RGB" without any attached profile is just meaningless data
> That is somewhere between willful misrepresentation and outright untruth.

It is absolutely not. :-)
RGB alone means nothing without a profile. Quoting from Wikipedia:

> RGB is a device-dependent color model: different devices detect or reproduce a given RGB value differently, since the color elements (such as phosphors or dyes) and their response to the individual R, G, and B levels vary from manufacturer to manufacturer, or even in the same device over time. Thus a RGB value does not define the same color across devices without some kind of color management.

Some color spaces are not device dependent. This is the case for instance of LAB. But this is not the case of RGB, which is *always* device dependent. So yes, a RGB value is absolutely meaningless without its attached profile. Of course, many applications approximate ok colors by assuming the most common RGB profiles (i.e. the standardized sRGB by IEC), when no profiles are attached to an image. Many go even as far as assuming that everything is such sRGB (even sometimes discarding an attached profile; browsers often do this by default, if not mistaken and if things didn't change). But that does not mean that RGB is suddenly device-independent. Anyone who saw a adobeRGB (or other profile) image in a software assuming sRGB knows that you can get completely wrong result (and not just a little) if you are not given exactly the right profile to use to know the actual meaning of the pixel colors.

This not a misrepresentation, nor a lie ("outright untruth", basically you are saying I am a liar) and it's a bit hurtful to say so. Do we really have to say this kind of thing in a bug report? Could we please not do that?

Also I may be wrong. I often am wrong. When I am, I'd prefer you tell me I am wrong than telling me I am lying to you. I hope you can understand why one is perfectly acceptable and the other is hurtful.
Thanks.

**Comment by hadess** [comment]
> "RGB" without any attached profile is just meaningless data.

That's completely untrue. Sure there's no reference point, which means it might look different on different devices, but saying it's meaningless data is just as Matthias described it.

This "meaningless data" can be viewed and have colours exactly matching if both viewing devices have been calibrated to the same standard. If they weren't, then there's still data that can be corrected. It's not as useful for some use cases, but good enough for most.

In any case, the portal returns a file, which depending on the implementation (the part of the stack giving back a file to the specific portal implementation, probably mutter in this case) would have this information provided as file metadata (PNG and JPG both support this).

There's nothing more to be done at the portal API level, so closing.

**Comment by Jehan** [comment]
> That's completely untrue. Sure there's no reference point, which means it might look different on different devices, but saying it's meaningless data is just as Matthias described it.

"there's no reference point, which means it might look different on different devices" basically means the same thing as what I am saying! It means that the RGB numbers don't represent a color unless it is attached to a profile which defines its reference.
Now you are both right that "meaningless" was a little strong. There is obviously "relative" meaning in the RGB numbers. Basically it tells a color is reder, greener, bluer than another. But absolute meaning is given with the profile. Sorry for using the word "meaningless", it seems like it raised hell and that's obviously not the intention. Semantic is really not what I wanted to talk about here, so I remove my word. I was wrong.

> In any case, the portal returns a file, which depending on the implementation (the part of the stack giving back a file to the specific portal implementation, probably mutter in this case) would have this information provided as file metadata (PNG and JPG both support this).

Yep, this is definitely the best implementation, and what I was already proposing on issue #139 (https://github.com/flatpak/xdg-desktop-portal/issues/139#issuecomment-358779550). This is what does macOS screenshot for instance, and as I said in #139 is ideal.

I was under the impression that you had some implementation in xdg-desktop-portal, which is why I opened this report. This is only the bare API without any implementation on this repo, then?

**Comment by hadess** [comment]
xdg-desktop-portal implements practically nothing itself, everything is implemented either in xdg-desktop-portal-gtk (for GNOME desktops) or equivalents for other desktops, which, in turn, calls actual backends. Screenshots are implemented in mutter for the gtk portal.
