### ISSUE TITLE
FileChooser version is at 3 (should be 4)

### ISSUE THREAD

**Issue by bermeitinger-b** [flatpak/xdg-desktop-portal#1445]
### Operating System

Arch Linux

### XDG Desktop Portal version

1.18

### Desktop Environment

Other

### Desktop Environment (Other)

i3 (with XFCE fallback)

### Expected Behavior

The FileChooser portal works in Electron applications.

### Current Behavior

Electron checks for FileChooser version 4 before opening the FileChooser portal 

### Steps to Reproduce

1. Install a fairly new Electron application with flatpak (e.g. org.signal.Signal)
2. Try to save or attach a file: not FileChooser portal is not used

### Anything else we should know?

Electron requires FileChooser version 4 since https://github.com/electron/electron/pull/43570 

However, my current (up-to-date) versions report version 3:

```bash
$ /usr/lib/xdg-desktop-portal --version
xdg-desktop-portal 1.18.4
$ /usr/lib/xdg-desktop-portal --version
xdg-desktop-portal-gtk 1.15.1
```

I check the version with 
```bash
$ gdbus introspect --session --dest=org.freedesktop.portal.Desktop --object-path=/org/freedesktop/portal -pr | grep -A2 "org\.freedesktop\.portal\.FileChooser" | sed -n 's/.*\(version = [0-9]\+\).*/\1/p'
version = 3
```
(There might be a better way. I'm not familiar with dbus. `qdbusviewer6` shows me the same version.)

**Comment by smcv** [comment]
The version in git main is indeed 4, but there have not been any releases since that change.

This is effectively a request for 1.19.x beta versions, and then 1.20.x stable versions, to be released: there is no code change that will fix this, it's purely a matter of release management.

**Comment by bermeitinger-b** [comment]
Thank you for the answer! It clarifies a lot.

So Electron was too fast adopting this version, then.

**Comment by GeorgesStavracas** [comment]
There isn't much we can do in our side, except release 1.20, which is in the plans for the next few months. So I'll close this issue as resolved.
