### ISSUE TITLE
Find a better home for the docs

### ISSUE THREAD

**Issue by allanday** [flatpak/xdg-desktop-portal#147]
The xdg-desktop-portal docs are currently hosted on flatpak.org (when they're working at least - that's issue 138). flatpak.org isn't a great place for them - no other developer documentation is hosted there.

freedesktop.org might be an appropriate place, logically at least.

**Comment by matthiasclasen** [comment]
put them wherever the flatpak developer documentation ends up, is what I would suggest

**Comment by allanday** [comment]
> put them wherever the flatpak developer documentation ends up, is what I would suggest

Yes, that could work. I don't know of any plans to move those from their current location on [readthedocs](http://docs.flatpak.org/).

**Comment by TingPing** [comment]
The flatpak docs just shove their generated html into the other docs: https://github.com/flatpak/flatpak-docs/blob/master/docs/flatpak-builder-docs.html

It seems to work if not pretty or automated...

**Comment by matthiasclasen** [comment]
https://flatpak.github.io/xdg-desktop-portal/portal-docs.html is the current location of the docs
