### ISSUE TITLE
Segfault when trying to print using gnome-text-editor

### ISSUE THREAD

**Issue by dCosminn** [flatpak/xdg-desktop-portal#1483]
### Operating System

Gnome 47 (Arch Linux)

### XDG Desktop Portal version

1.18

### Desktop Environment

GNOME

### Expected Behavior

Open gnonme-text-editor, click on Print and the printing menu should appear.

### Current Behavior

Open gnonme-text-editor, click on Print and the app is crashing.

### Steps to Reproduce

1.
2.
3.
...

### Anything else we should know?

This also happens with the Image Viewer(Loupe), the Print menu shows for a few seconds then it's crashing, but it's crashing only the print menu and not the whole program.

[loupe journal.txt](https://github.com/user-attachments/files/17460112/loupe.journal.txt)
[loupe coredump.txt](https://github.com/user-attachments/files/17460111/loupe.coredump.txt)
[text-editor journal.txt](https://github.com/user-attachments/files/17460113/text-editor.journal.txt)
[text-editor coredump.txt](https://github.com/user-attachments/files/17460115/text-editor.coredump.txt)

**Comment by GeorgesStavracas** [comment]
Thanks for providing coredumps, they were useful. Sadly however seems like the crash is happening on GTK code. We cannot move the issue to GTK because it lives in GNOME's Gitlab. Can you please report this to [GTK](https://gitlab.gnome.org/GNOME/gtk)? Please check if it wasn't reported there before first.

**Comment by dCosminn** [comment]
I'm no longer getting the errors, the GTK guys fixed the issue.

**Comment by GeorgesStavracas** [comment]
That's great news!
