### ISSUE TITLE
Translate paths on sandbox boundaries if possible

### ISSUE THREAD

**Issue by amtlib-dot-dll** [flatpak/xdg-desktop-portal#151]
As there lies the file path problem #148 #95, it would be better if portal services like `OpenFile` or `SaveFile` translates the path of the file to be opened to the real path. For example, if an application with `--persist=.mozilla` tries to open `~/.mozilla/README.htm` in the user's browser, the browser may just open `~/.var/app/<APPID>/.mozilla` rather than the file under `/run`; if an application with `--filesystem=~/.mozilla` tries to open `~/.mozilla/README.htm` in the user's browser, the browser may just open the path as-is. On the contrary, if the file to save is accessible for the application (for example the user saves the file under `~/Documents` when `--filesystem=xdg-documents` is applied), the returned file name should just be the real path, as per #141 

Possible problem: the logic might be complex

**Comment by matthiasclasen** [comment]
we have a file-transfer portal now, which can solve this problem
