### ISSUE TITLE
GTK 3 apps on Wayland have broken anti-aliasing and theming, under KDE Plasma with GTK_USE_PORTAL=1

### ISSUE THREAD

**Issue by guss77** [flatpak/xdg-desktop-portal#1535]
### Operating System

Neon 6.2

### XDG Desktop Portal version

Other

### XDG Desktop Portal version (Other)

1.19.0

### Desktop Environment

KDE

### Expected Behavior

with `GTK_USE_PORTAL=1` (needed in order for GTK apps to use the desktop environment file dialogs) on Wayland, GTK3 apps should look and behave like they do on X11 and also on Wayland without `GTK_USE_PORTAL` (except for the portal file dialogs):

This is how `awf-gtk3` looks for me on Plasma Wayland, without `GTK_USE_PORTAL=1` :
![Screenshot_20241212_104034](https://github.com/user-attachments/assets/0b798798-3ce0-49d6-a1ea-d31d75413874)

We can also get the same behavior by setting `GTK_USE_PORTAL=1` and forcing XWayland rendering.

### Current Behavior

This is how `awf-gtk3` looks for me on Plasma Wayland, with `GTK_USE_PORTAL=1` 
![Screenshot_20241212_103930](https://github.com/user-attachments/assets/b3e55c69-9c6d-4fcc-9947-d29ae0701572)

This behavior is new for 1.19.0 - it works fine if I downgrade to 1.18.3. Looking at the D-Bus calls, it looks like XDG Desktop Portal does not call the `gtk` implementation service (and depending on its startup triggers, it may no even start if it is set to start lazily with systemd D-Bus trigger).

### Steps to Reproduce

1. Install xdg-desktop-portal 1.19.0
2. Set the environment variable `GTK_USE_PORTAL=1` 
3. Start a Plasma Wayland session
4. Start any GTK 3 application.

### Anything else we should know?

This behavior was originally reported on the closed issue #1123 - that was closed as dup of #1112. I'm reporting this again as (a) probably nobody pays attention to closed issues; (b) at least this behavior seems unrelated to #1112 (and I believe also the originally reported behavior there).

My `/usr/share/xdg-desktop-portal/kde-portals.conf` - which I know XDG Desktop Portal reads, because I `strace`d it - looks like this:

```
[preferred]
default=kde
org.freedesktop.impl.portal.Settings=kde;gtk;
org.freedesktop.impl.portal.Secret=kwallet
```

**Comment by Sodivad** [comment]
Hmm did not automatically close

**Comment by guss77** [comment]
@Sodivad Thank you!
