### ISSUE TITLE
Cannot save multiple files via org.freedesktop.portal.FileChooser

### ISSUE THREAD

**Issue by mjog** [flatpak/xdg-desktop-portal#158]
It's not currently possible to save multiple files at once from within a sandbox using the org.freedesktop.portal.FileChooser portal. This manifests as [GtkFileChooserNativePortal not implementing SELECT_FOLDER](https://bugzilla.gnome.org/show_bug.cgi?id=785884) and silently falling back to a non-native chooser when an application attempts to use it, which works fine if you have RW permissions for $HOME, but not when sandboxed.

Pitivi breaks out of the sandbox to work around this, but it has also broken Geary's Save All Attachments feature, as [reported by a user](https://github.com/flathub/org.gnome.Geary/issues/5) against Flathub, and I'm reluctant to take Pitivi's approach there.

This could maybe be implemented by adding a org.freedesktop.portal.FileChooser SaveFiles method that expects to be passed a list of file names to be saved, and with SaveFilesResponse returning absolute URIs for each file. A select-folder file chooser could then be presented to the user, which can be used to generate the absolute URIs based on the selected folder and the given filenames. This would need some GTK+ API additions to implement, however.

**Comment by thiblahute** [comment]
We basically took that approach in Pitivi because we started using flatpak even before the concept of Portal was properly settled :-) Now this bug is blocking us into properly having Pitivi sandboxed (as far as filesystem access is concerned).

**Comment by glaubersm** [comment]
Fix this problem please. It's impossible to choose folders located in other partitions/devices
and consequently this bug can make some flatpaks unusable.
https://bugs.kde.org/show_bug.cgi?id=406115

**Comment by matthiasclasen** [comment]
Saying "fix this please" doesn't make the underlying fundamental problem go away.

**Comment by mjog** [comment]
@thiblahute would the approach I'm taking over in https://github.com/flatpak/xdg-desktop-portal/pull/368 work for Pitivi?

In addition to the portal support, I was going to look into GTK API for it, I'm thinking of a method like `gtk_file_chooser_native_new_save_files(...)` that allow specifying the files to be saved, so that then `gtk_file_chooser_get_filenames()` and `gtk_file_chooser_get_uris()` subsequently work as usual.
