### ISSUE TITLE
Attempting to call OpenURI on NixOS fails with "No such interface"

### ISSUE THREAD

**Issue by silverjam** [flatpak/xdg-desktop-portal#172]
I've compiled the xdg-desktop-portal package for NixOS and am attempting to us it with gdbus bus I'm getting failures that "No such interface" is found:

```
gdbus call --session --dest org.freedesktop.portal.Desktop \
  --object-path /org/freedesktop/portal/desktop \
  --method org.freedesktop.portal.OpenURI.OpenURI "" "http://google.com"
Error: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.freedesktop.portal.OpenURI' on object at path /org/freedesktop/portal/desktop
```

OpenURI shows up in the dbus interface configs here:
```
$ ls /run/current-system/sw/share/dbus-1/interfaces/|grep OpenURI
org.freedesktop.portal.OpenURI.xml@
```
Any idea what could be going wrong?

**Comment by matthiasclasen** [comment]
Is the xdg-desktop-portal process running ?

**Comment by silverjam** [comment]
I'm experimenting by running the compiled packages manually, don't know enough about NixOS yet to figure out how to integrate the service files into the system.  So, on the system I'll manually run the daemons in a couple terminals:

```
jason     6329  0.0  0.2 603624 35632 pts/7    Sl+  22:50   0:00 /home/jason/dev/xdg-desktop-portal/result-3/lib/libexec/xdg-desktop-portal-kde -v
jason     8196  0.0  0.0 448108  5548 pts/2    Sl+  22:52   0:00 /home/jason/dev/xdg-desktop-portal/result-2/libexec/xdg-desktop-portal -v
```

Then, some of the service will show up in `qdbusviewer` for example:

![screenshot_20180324_225833](https://user-images.githubusercontent.com/183436/37872193-338f279a-2fb7-11e8-977e-4861a3d08bd8.png)

The daemons will logs things like this:
```
$ /home/jason/dev/xdg-desktop-portal/result-2/libexec/xdg-desktop-portal -v
XDP: providing portal org.freedesktop.portal.NetworkMonitor
XDP: providing portal org.freedesktop.portal.ProxyResolver
XDP: org.freedesktop.portal.Desktop acquired

$ /home/jason/dev/xdg-desktop-portal/result-3/lib/libexec/xdg-desktop-portal-kde -v
xdg-desktop-portal-kde: Desktop portal registered successfuly
Icon theme "oxygen" not found.
```

Are things like pipewire required for the Desktop object to function correctly?

**Comment by matthiasclasen** [comment]
you need a backend implementation, either xdg-desktop-portal-gtk or xdg-desktop-portal-kde

**Comment by silverjam** [comment]
See the second part of the shell output above, `xdg-desktop-portal-kde` is running.

**Comment by matthiasclasen** [comment]
Almost certainly an issue with your setup, nothing wrong on the portal side
