### ISSUE TITLE
add a portal for screencasts and screen sharing

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/xdg-desktop-portal#18]
The screencast interface will be needed to fix things like screen sharing in bluejeans, webrtc, etc.

For screenshots, one suggested user experience is to first take the screenshot, then present a dialog with the result and ask "ok to share this with app foo ? "

For screencasts, pinos probably should be involved.

**Comment by matthiasclasen** [comment]
screenshots are done

**Comment by phw** [comment]
One thing that would be handy for screencasting would be to specify the position relative to a window of the calling application. As getting window screen coordinates on Wayland is not possible for conceptional reasons this would still allow use cases like using a window to select a screen area (as used for example by my own [Peek](https://github.com/phw/peek/) or [Green Recorder](https://github.com/green-project/green-recorder).

Alternatively allowing the recording of the full window of the calling app would work, too (but requires some cutting of the video for the use cases above).

**Comment by matthiasclasen** [comment]
this is covered by #38
