### ISSUE TITLE
Add an Avahi portal.

### ISSUE THREAD

**Issue by AdrianKoshka** [flatpak/xdg-desktop-portal#183]
I'm trying to package [barrier](https://github.com/debauchee/barrier/issues/30#issuecomment-384003713), (a synergy fork) as a flatpak. Instead of compiling the whole avahi daemon within the flatpak, I was wondering if it'd just be smarter to have a portal for this.

**Comment by hadess** [comment]
> Related discussion: flatpak/flatpak#348

@TingPing: Not related :) The other issue is about the inability to use system-wide NSS modules, so we'd likely need to ship nss-mdns inside the sandbox, with the necessary nsswitch.conf changes.

@AdrianKoshka open up the D-Bus service name for Avahi (`--system-talk-name=org.freedesktop.Avahi` in the finish-args), you don't need to do anything special to use it through D-Bus.

If you need the helper libraries from Avahi, then I'm afraid that you will need to compile it yourself. Make sure to disable the daemon and all the bits you don't need.

Also, given that we do not want to have a portal for networking in general, and that everything that Avahi does is already possible for pretty much any network client, there's no real reason to restrict it.

**Comment by AdrianKoshka** [comment]
Thanks for the help @hadess
