### ISSUE TITLE
Color Picker Portal

### ISSUE THREAD

**Issue by mrmcq2u** [flatpak/xdg-desktop-portal#188]
Any chance of a color picker portal? This is something that would be needed for flutter desktop embedder and might be useful for applications like gimp as well.
Two relevent bugs ->
https://bugzilla.gnome.org/show_bug.cgi?id=780375
https://bugzilla.gnome.org/show_bug.cgi?id=789756

**Comment by matthiasclasen** [comment]
I want to make this just another method in the screenshot portal. It is very similar - just a 1x1 screenshot

**Comment by matthiasclasen** [comment]
https://gitlab.gnome.org/GNOME/gnome-shell/issues/286
