### ISSUE TITLE
Document Portal does not support `chmod`, `utime` & `setxattr`

### ISSUE THREAD

**Issue by ntninja** [flatpak/xdg-desktop-portal#192]
## Linux distribution and version

Debian unstable with KDE from KDE Neon

## Flatpak version

Flatpak 0.11.3

## Description of the problem

Currently calling `utime` (`touch`), `chmod` or `setxattr` on a file shared using the document portal into `${XDG_RUNTIME_DIR}/doc` will return `ENOTSUP` (errno 95) instead of performing the requested action. This breaks Python's `shutil.copy` & `shutil.copy2` which the application I'm attempting to port happens to use.

## Steps to reproduce

 1. Share a file to a running Flatpak app using the file chooser or `flatpak document-export`
 2. Run `touch "${XDG_RUNTIME_DIR}/doc/<share-id>/<filename>` on the shared file
 3. Observe the error: *touch: setting times of '<runtime-dir>/doc/<share-id>/<filename>': Function not implemented*

**Comment by matthiasclasen** [comment]
This will have to be implemented in the documents portal fuse fs, I think

**Comment by hfiguiere** [comment]
chomd and touch do work

**Comment by hfiguiere** [comment]
`attr -l` list selinux attributes.

I think this was fixed since. #517 show that chmod now works.

Likely part of commit ecc0af3b
