### ISSUE TITLE
Portal for running commands on the host

### ISSUE THREAD

**Issue by mzabaluev** [flatpak/xdg-desktop-portal#193]
Applications such as IDEs and terminal emulators often need a way to run commands on the host system, but the set of commands allowed to an application should be at the discretion of the user.

The issue flatpak/flatpak#953 was closed with a terse comment "this is now in with the portal", but no implementation has been made apparent to me so far. So I'm adding this issue to track the eventual portal solution.

**Comment by matthiasclasen** [comment]
Its here : https://github.com/flatpak/flatpak/blob/master/data/org.freedesktop.Flatpak.xml

Not technically a portal, but it is a dbus interface that you can allow into your sandbox if you need it.

**Comment by mzabaluev** [comment]
The interface `org.freedesktop.Flatpak.Development` seems only marginally portal-ready: `HostCommand` must return the PID quickly, so a service implementation that interjects with a user authorization prompt before executing the command would need to spawn a placeholder process that will exec the command when approved by the user. If something goes wrong with the authorization, there is no way to signal this in `HostCommandExited` that would be distinguishable from the command itself exiting with a particular status (which might collide with error codes used by the actual command).
