### ISSUE TITLE
Allow matching based on prefix

### ISSUE THREAD

**Issue by nedrichards** [flatpak/xdg-desktop-portal#203]
From: https://github.com/flathub/org.gnome.Weather/issues/1

> nick@endless-nedr:~$ flatpak run org.gnome.Weather
> Gjs-Message: JS LOG: Failed to connect to GeoClue2 service: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: Agent rejected 'org.gnome.Weather' for user '1001'. Please ensure that 'org.gnome.Weather' has installed a valid org.gnome.Weather.desktop file.

This leads to the 'Automatic Location' button being disabled in the Places popover. Looks like a problem with sandboxing/the difference between org.gnome.Weather.Application and org.gnome.Weather.BackgroundService.

@gcampax then said "I am tempted to call this a bug in the portal. They should treat org.gnome.Weather.Application.desktop as valid because it has the right prefix."

**Comment by matthiasclasen** [comment]
this is geoclue. it does not live here. My opinion is that geolocation needs to be redone as a proper portal, but for now, please complain to Zeeshan

**Comment by nedrichards** [comment]
Ah, apologies, I misread the error. Agreed on the proper portal thing!
