### ISSUE TITLE
g_network_monitor_get_network_available () status is wrong

### ISSUE THREAD

**Issue by janbrummer** [flatpak/xdg-desktop-portal#208]
Starting with version 0.99 the status of g_network_monitor_get_network_available is always false. Reconnects during runtime also has no effect. It looks like the status is not handled at all.

Flatpak app has of course shared permission to network. If requested i can provide a simple demo app.

Note: Killing xdg-desktop-portal causes a change to true.

**Comment by mjog** [comment]
Confirming. This has stopped people from being able to use Geary installed from Flathub on Fedora Silverblue, since it is unable to connect to any mail servers. E.g. [upstream](https://gitlab.gnome.org/GNOME/geary/issues/73) and on [flathub](https://github.com/flathub/org.gnome.Geary/issues/9).

**Comment by matthiasclasen** [comment]
which version of glib are you using ? we did change the network monitor portal api in 0.99 to fix some sandboxing concerns before 1.0. This requires a relatively recent glib release, 2.57.2

**Comment by janbrummer** [comment]
Name         : glib2
Version      : 2.57.2
Release      : 1.fc29
Arch         : x86_64

**Comment by matthiasclasen** [comment]
but what glib is in the runtime that is used ?

**Comment by fbruetting** [comment]
How can we find out?

**Comment by janbrummer** [comment]
Within 3.28 runtime, it is 2.56.1

**Comment by matthiasclasen** [comment]
Alex, maybe we should patch glib in the stable runtime to support the new network monitor portal api ? The current glib code supports both versions.

**Comment by janbrummer** [comment]
I would highly recommend it as it currently breaks all apps which makes use of the gnetworkmanager. This is at least not what i expected from a flatpak xdg-desktop-portal change.

**Comment by alexlarsson** [comment]
@matthiasclasen I'm backporting this to the runtimes now. But it would be nice to have a glib 2.56 stable release with this in it.

**Comment by matthiasclasen** [comment]
I'll put it on my list

**Comment by fbruetting** [comment]
Apps like Geary and Feedreader still are broken with the latest runtimes (Platform//3.28 @ f5ad47d93872). When will they work again?

**Comment by janbrummer** [comment]
Yes, it's the same for me. But at least one runtime 3.24 is working, everything above does not work.

**Comment by matthiasclasen** [comment]
Please reopen issues when commenting. In particular when you think they are not fixed.

**Comment by fbruetting** [comment]
I thought it may still be in the pipe…

It’s v0.99 of current Silverblue.

**Comment by janbrummer** [comment]
Also with 1.0 it is not working.

**Comment by matthiasclasen** [comment]
I just installed geary from flathub, and it seems to work just fine here. At least, it downloads all of my mail

**Comment by janbrummer** [comment]
Unfortunately it does not work for me. I did a fresh installation of Fedora Rawhide and installed Geary from flathub. It cannot connect to my mail server and according to debug log server is unreachable:

util-connectivity-manager.vala:85: Error checking mail.XXXXXXXX.net/default:143 reachable, treating as unreachable: Network unreachable

The same issue is stated with my own app: Network is reported as offline.

What kind of information do you need to analyse this issue?

**Comment by janbrummer** [comment]
@matthiasclasen which runtime are you using (gnome/flathub)? what's the checksum?

**Comment by matthiasclasen** [comment]
I think the title of this issue is misleading. g_network_monitor_get_network_available() works fine with the latest network monitor code. What is broken is g_network_monitor_can_reach(). But that has probably been broken all along with the portal implementation.

**Comment by mjog** [comment]
On 24 August 2018 11:36:48 Matthias Clasen <notifications@github.com> wrote:
> What is broken is g_network_monitor_can_reach(). But that has probably been 
> broken all along with the portal implementation.

Yep, I noticed bgo 777706 a while ago and had to add a workaround: 
https://gitlab.gnome.org/GNOME/geary/blob/master/src/engine/util/util-connectivity-manager.vala#L116

This previously enabled Geary to work fine under Flatpak, and it is 
currently working fine for me on e.g. Ubuntu Bionic, with the Flatpak PPA 
and up-to-date runtimes.

Maybe the workaround needs to be updated to work with the new portal, but 
it would be nice if g_network_monitor_can_reach() was actually implemented 
properly so I can take the workaround out at some point.

**Comment by matthiasclasen** [comment]
I have pushed some branches with a can_reach() implementation

**Comment by janbrummer** [comment]
No the title is not misleading (at least for my app). I'm attaching a simple sample application. It reports 0 as available network even though the system is connected to wifi.

[nettest.zip](https://github.com/flatpak/xdg-desktop-portal/files/2317094/nettest.zip)

**Comment by mjog** [comment]
FYI it looks like the org.gnome.Platform//3.28 update hasn't actually hit Flathub yet.

The manifest for the 3.28 branch [shows glib-2.56.2](https://gitlab.gnome.org/GNOME/gnome-sdk-images/commit/5bbd71d8e79d0a258efa186392a44cbb20fcb349), but my up-to-date runtime only has 2.56.0:

```
mjog@blanchefort:~/Projects/GNOME/glib$ flatpak info org.gnome.Platform//3.28
Ref: runtime/org.gnome.Platform/x86_64/3.28
ID: org.gnome.Platform
Arch: x86_64
Branch: 3.28
Origin: flathub
Collection ID: org.flathub.Stable
Date: 2018-08-13 22:50:57 +0000
Subject: build of org.gnome.Sdk, Mon Aug 13 14:53:04 UTC 2018
Commit: f5ad47d93872b617a6a05227d82e04481bc5a236c7299d04005e3c1f306f76d8
Parent: cd176f8f59d2bf3177d7b1cecceb9af1059196e3183eea915b1898a47decb179
Location: /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.28/f5ad47d93872b617a6a05227d82e04481bc5a236c7299d04005e3c1f306f76d8
Installed size: 1.3 GB
mjog@blanchefort:~/Projects/GNOME/glib$ grep -r glib-networking-2 /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.28/f5ad47d93872b617a6a05227d82e04481bc5a236c7299d04005e3c1f306f76d8/files/manifest.json
          "url" : "https://download.gnome.org/sources/glib-networking/2.56/glib-networking-2.56.0.tar.xz",
```

(It's actually long out of date since Alex's change bumped it from .1 to .2, not from .0)

**Comment by fbruetting** [comment]
Guys, quite some apps are totally broken since weeks. 🙄 Can’t you please push a fix?

**Comment by mjog** [comment]
@matthiasclasen in particular, is there anything blocking getting org.gnome.Platform//3.28 updated on flathub to contain the glib updates? Is there anything I can do to help make that happen?

As you point out, g_network_monitor_can_reach() has never been working under Flatpak, but Geary's current workaround for this falls back to calling g_network_monitor_get_network_available() as a sanity check, so even getting only the latter fixed would be extremely helpful.

**Comment by mjog** [comment]
Or perhaps don't worry -- I've just hacked around this for Flathub, maybe that's the easiest thing to do for the moment.

**Comment by matthiasclasen** [comment]
Its just a matter of getting the fixed code released and deployed. Should happen soon

**Comment by matthiasclasen** [comment]
This should finally be fixed with glib 2.58.1 and xdg-desktop-portal 1.02 on the host side.

Please reopen if you still see issues with those versions.

**Comment by loupianche** [comment]
This issue is present in glib 2.58.3 and xdg-desktop-portal 1.2.0.

Please reopen the bug.

**Comment by loupianche** [comment]
https://gitlab.gnome.org/World/lollypop/issues/1588#note_456227

**Comment by hadess** [comment]
It's a bug in the way glib uses the portal (or how the application uses that info? maybe):
https://gitlab.gnome.org/GNOME/glib/issues/1718

So won't be reopening, different problem.
