### ISSUE TITLE
ensure the file chooser only sends file: uris back

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/xdg-desktop-portal#213]
So far, we've used GIO_USE_VFS=local to guarantee this, but we do want to let the user access gvfs. That means that we need to translate non-file uris to their local (fuse) equivalents, since we can't rely on  things like trash: or recent: to work inside the sandbox.

**Comment by matthiasclasen** [comment]
A quick test shows that the file chooser already returns file: uris, at least for recent files.

**Comment by hadess** [comment]
This little song and dance gets a file:/// URI for most gvfs backends:
https://gitlab.gnome.org/GNOME/totem/blob/master/src/backend/bacon-video-widget.c#L4045
`get_target_uri()` is the interesting one.

**Comment by Be-ing** [comment]
I am stumbling over this as well. I am working on [rfd](https://github.com/PolyMeilex/rfd/), a cross platform Rust library abstracting over file dialogs on different OSes. On macOS and Windows, the file dialogs only return file paths. But the XDG Desktop Portal allows the file dialog to return arbitrary URIs. I can easily strip off the `file://` prefix, but if the user picks something with a different prefix, the best this cross platform abstraction can do is act as if no file was picked or ask the user to pick again.

**Comment by lissyx** [comment]
Until this issue is fixed, UX should not show anything to the user: https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/issues/48

**Comment by sergio-costas** [comment]
proposed patch in xdg-desktop-portal-gnome that fixes this: https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/merge_requests/67

**Comment by GeorgesStavracas** [comment]
This has been pushed into a documentation change. Backends are responsible for returning only `file://` URIs.

**Comment by sergio-costas** [comment]
Thanks!
