### ISSUE TITLE
Add screensaver status to inhibit portal

### ISSUE THREAD

**Issue by hadess** [flatpak/xdg-desktop-portal#214]
So that applications don't need to talk to `org.gnome.ScreenSaver` directly:
https://github.com/search?q=org:flathub+org.gnome.Screensaver&type=Code

Ideally, this would also have a GLib API that works both in and out of the sandbox.

**Comment by matthiasclasen** [comment]
Draft api here: https://github.com/matthiasclasen/xdg-desktop-portal/tree/screensaver

No implementation yet.

**Comment by matthiasclasen** [comment]
I hadn't thought about the client-side api yet. But yes, a boolean on GtkApplication seems likely.

**Comment by matthiasclasen** [comment]
client-side api: https://gitlab.gnome.org/GNOME/gtk/merge_requests/312
