### ISSUE TITLE
Gio File Copy: g-io-error-quark, Software caused connection abort

### ISSUE THREAD

**Issue by FalkAlexander** [flatpak/xdg-desktop-portal#230]
Moved from https://github.com/flatpak/flatpak/issues/2177

## Linux distribution and version
Fedora 28/29, Ubuntu 18.04, Arch Linux
## Flatpak version
1.0.2
## Description of the problem
Using the copy function on a Gio File object for copying into another directory throws
`g-io-error-quark: Error opening file “/run/user/1000/doc/291bd18e/Safe.kdbx”: Software caused connection abort (0)`
https://lazka.github.io/pgi-docs/#Gio-2.0/classes/File.html#Gio.File.copy

Independent of the filesystem permission, tried without, with home and host.
## Steps to reproduce
1. Optionally get my app at https://gitlab.gnome.org/World/PasswordSafe
2. Start Password Safe
3. Click on "New..." for creating a new database
4. Select a directory for the database with GtkFileChooserNative
5. Click Save
6. Close the app
7. Look into the directory, there is a database file which size is > 0kb
8. Delete the database file
9. Reopen the app and recreate the database with the same filename
10. Gio throws g-io-error-quark and the database file size is 0 kb

Does not necessarily have to be the identical folder, sometimes this happens without previous deletion of the database file. Couldn't find an exact schema.

This does only happen with the Flatpak package.

I've discussed already with @bilelmoussaoui about this, maybe he has some information he can add here also.
@bertob experienced this behaviour also while using Password Safe.

**Comment by bilelmoussaoui** [comment]
I can confirm this issue when I was trying to use Gtk.NativeFileChooser on my application. I had to switch to a Gtk.FileChooser instead & added `--filesystem=home` in order to fix it. 
I can provide a test env if you want :+1:

**Comment by matthiasclasen** [comment]
Thats not a 'fix', thats just disabling the sandboxing :(

**Comment by bilelmoussaoui** [comment]
@matthiasclasen Never said it was a fix. I just switched to that before reporting the issue! once it's fixed I will switch back to the NativeFileChooser

**Comment by BrainBlasted** [comment]
I'm trying to write an export function for an app, using FileChooserNative. `--filesystem=home` did not work:

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 103, kind: ConnectionAborted, message: "Software caused connection abort" }', libcore/result.rs:945:5
```

**Comment by alexlarsson** [comment]
I mean, it should work. I think ConnectionAborted == ECONNABORTED == the fuse process died.
This sounds somewhat like d21be2e0d87511fca2924ce29a22447bd8e97841. What version of xdg-desktop-portal is this?

**Comment by FalkAlexander** [comment]
> What version of xdg-desktop-portal is this?

1.0.2

The issue is gone for me with d21be2e0d87511fca2924ce29a22447bd8e97841
Thank you @alexlarsson

**Comment by BrainBlasted** [comment]
The issue persists for me, but with a quirk: if the file does not exist, a blank file will be created but no data will be saved to it. If the blank file (or another file with the same name) already exists, it will save properly.

**Comment by FalkAlexander** [comment]
I have to withdraw my last statement that the issue is gone: Can confirm what @BrainBlasted reported.
Also there was sometimes thrown `g-io-error-quark: Error opening file “/run/user/1000/doc/291bd18e/Safe.kdbx”: Transport endpoint is not connected (45)` in my tests while trying to override an existing blank 0kb file.

**Comment by matthiasclasen** [comment]
Can you point gdb at the xdg-document-portal process and see if it crashes ?

**Comment by FalkAlexander** [comment]
Debuginfo: 
[gdb.txt](https://github.com/flatpak/xdg-desktop-portal/files/2450188/gdb.txt)

**Comment by matthiasclasen** [comment]
thanks!

**Comment by matthiasclasen** [comment]
Alex, could you take a look ? I'm not sure I fully understand the ownership handling in xdp_inode_create_file:

inode is an autoptr, and lookup_child_unlocked returns a reference, but then there is extra manual unreffing, and no reffing of the return value. I think the code may be correct without the autoptr ?

**Comment by matthiasclasen** [comment]
Worth noting that the autoptr was introduced recently, to fix a leak.
