### ISSUE TITLE
Add way to exclude cursor from screen capture stream

### ISSUE THREAD

**Issue by jadahl** [flatpak/xdg-desktop-portal#234]
Right now the screen capture (including remote desktop) includes the cursor. This is due to there not being a defined way to pass the cursor position and sprite as meta data in the PipeWire stream, as well as no defined way to communicate what the stream should include. This should be added, both to avoid unnecessary frames just for cursor movements, as well as communicating the exact cursor position for a frame.

**Comment by jadahl** [comment]
cc:ing @wtay for the PipeWire part.

**Comment by matthiasclasen** [comment]
sounds good

**Comment by matthiasclasen** [comment]
I think  AvailableCursorModes in  the ScreenCast portal covers this
