### ISSUE TITLE
File chooser: add support for preview widgets

### ISSUE THREAD

**Issue by quequotion** [flatpak/xdg-desktop-portal#237]
It can be difficult to select a specific file from a large group of files without a preview, especially when filenames are not meaningful (IMG_07615.JPG, etc). xdg-desktop-portal should allow for applications to send previews to filechooser dialogs.

See Michael Catanzaro's comment [on epiphany's filechooser implementation](https://gitlab.gnome.org/GNOME/epiphany/issues/552#note_343936) for details.

**Comment by mcatanzaro** [comment]
Looking into this more, no changes are required in xdg-desktop-portal, so this can be closed.

I'll comment in the original bug momentarily.

**Comment by quequotion** [comment]
I'll take your word for it!
