### ISSUE TITLE
HEX and URL decoding of mailto instructions

### ISSUE THREAD

**Issue by fbruetting** [flatpak/xdg-desktop-portal#240]
Some people use HEX and URL encoding for raising the bar for spam bots. Would be cool if this could be decoded by the portal.

![bildschirmfoto von 2018-10-29 00-40-38](https://user-images.githubusercontent.com/10520767/47623755-52845300-db15-11e8-91a8-2af7811d9ccc.png)

![](https://hosteurope.de/blog/wp-content/uploads/2014/11/example6.png)

![](https://hosteurope.de/blog/wp-content/uploads/2014/11/example7.png)

**Comment by GeorgesStavracas** [comment]
Please report this to the portals backend of your desktop environment, the portal does not touch the content it receives
