### ISSUE TITLE
xdp_mkstempat uses extremely poor PRNG

### ISSUE THREAD

**Issue by setharnold** [flatpak/xdg-desktop-portal#243]
https://github.com/flatpak/xdg-desktop-portal/blob/d4a92e02e990b70f782fd22de1269f7b741d1d1b/src/xdp-utils.c#L69

Hello,

I noticed that `xdp_mkstempat()` uses a really poor PRNG. Since the `mkstemp()` family of functions is used primarily for generating filenames that are extremely difficult for an attacker to collide, I believe this function should be using a significantly stronger RNG, preferably `getrandom(2)` if new-enough Linux is the target OS, or `/dev/urandom` if new-enough unix-alike is the target OS.

Thanks

**Comment by matthiasclasen** [comment]
I don't think it matters here.

**Comment by matthiasclasen** [comment]
Fixing this should probably start at the source - this code is more or less copied from glib, which is more or less copied from glibc...

**Comment by GeorgesStavracas** [comment]
Seems like not to be under anyone's radar. As Matthias mentions, it's just copying other more security sensitive places.
