### ISSUE TITLE
Only one fork()

### ISSUE THREAD

**Issue by setharnold** [flatpak/xdg-desktop-portal#244]
https://github.com/flatpak/xdg-desktop-portal/blob/70ad5e4a05239177f14b8bea27c3a9a7f746862c/document-portal/document-portal.c#L1511

Hello, I noticed that document-portal.c only performs one `fork(2)` when daemonizing. The usual approach is to `fork(2)`, call `setsid(2)`, then `fork(2)` again. The second `fork(2)` call would prevent the final process from gaining a controlling terminal by accident.

Thanks

**Comment by alexlarsson** [comment]
Actually, i'm not even sure why we have the --daemon option. In testing, you run non-daemonize, and in deployment the portal is always launched by dbus (directly or indirectly via systemd), and that daemonizes by itself.

**Comment by matthiasclasen** [comment]
So, shall we remove it, then ?

**Comment by alexlarsson** [comment]
Yeah, i think so, i can't find any place we use it. Both the dbus and the systemd service files don't pass it.
