### ISSUE TITLE
add a sound portal

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/xdg-desktop-portal#27]
Access to speakers and microphones.

**Comment by hadess** [comment]
Playback should ultimately not require any questions, but we'd have to clean up PulseAudio to not allow unfettered access before that.

**Comment by alexlarsson** [comment]
I can't find the mail, but i believe @a-darwish is the one working on pulseaudio support for this.

**Comment by hadess** [comment]
In which case the sound portal should only be a microphone portal.

**Comment by alexlarsson** [comment]
There is some kind of pluggable authentication layer being added to pulseaudio, and there will be a plugin that does the authentication which stores the result in the permissions portal.

**Comment by matthiasclasen** [comment]
I've now found this:
https://lists.freedesktop.org/archives/pulseaudio-discuss/2015-February/023243.html
https://cgit.freedesktop.org/~wtay/pulseaudio/log/?h=access-hooks

**Comment by matthiasclasen** [comment]
And this:
https://lists.freedesktop.org/archives/pulseaudio-discuss/2015-April/023596.html

**Comment by matthiasclasen** [comment]
And last:
https://github.com/a-darwish/pulseaudio/commits/access-control-v1

**Comment by a-darwish** [comment]
Hi @matthiasclasen, @alexlarsson 

Yes, we're cooking something in this area. Two days ago we've just created the [AccessControl for PulseAudio](https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/Developer/AccessControl/) document.

For extra context regarding wtay patches, please check [this message](http://article.gmane.org/gmane.comp.audio.pulseaudio.general/26141). Basically we have two competing designs for how to _properly_ implement this in pulse, and the document hosted at freedesktop.org above shall have all the necessary details (I'm working on it, in small chunks, daily). Hopefully a consensus shall be reached, and the winning design shall be implemented on top of wtay's work.

Adding @ford-perfect in the loop.

thanks,

**Comment by matthiasclasen** [comment]
Hey Ahmed, thanks for chiming in here!

**Comment by patrakov** [comment]
The discussion above is mostly centered on privacy issues, with "spying on the microphone" and "recording audio" being the main attack vectors. Please be aware that there are other concerns.

1. I personally would rather not let any random untrusted software, and especially web browsers, access expensive HiFi speakers - it's possible to destroy them by playing a full scale 19 kHz wave at normal volume appropriate for music. So maybe we should have a distinction between "robust" and "brittle" output devices.

2. PulseAudio currently has a number of DoS attacks, where DoS means "other programs can no longer output sound". Some of them (e.g. ability to kill it via rtkit by playing too many streams at once, with weird sample rates) are not easy to fix and may require an incompatible redesign that shifts some work into clients. Others are features (like passthrough support which mutes all other streams) or arbitrary limits (256 concurrent connections). Flatpak team should IMHO decide whether such DoS attacks are out of scope for this ticket, or must be dealt with by PulseAudio developers for this ticket to be treated as done.

**Comment by alexlarsson** [comment]
There is little to no protection against DoS attacks in flatpak. For instance, we don't do cpu limiting, process limiting, memory use limiting, open fd limiting, toplevel window limiting, dbus message rate limiting, GPU fill rate limiting, memory bandwidth limiting, etc, etc.

Basically, if you were trying to make the computer unusable, that is going to be easy from within a confined app. And fixing this is extremely hard. Doing so would be nice, but there are risks that such limits cause e.g. performance problems (cpu limiting a game?) and is less important than the major goal of flatpak of isolating apps from each other and from the users private data.

**Comment by alexlarsson** [comment]
Having some output devices not being granted "play" access by default seems like a nice option though.

**Comment by ford-prefect** [comment]
I've documented some of the cases we need to deal with at https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/Developer/AccessControl/#threatmodel

I'm sure it's not exhaustive, and there are some open questions there, so please add/comment.

**Comment by hadess** [comment]
> An application should only only be able to control the volume of its own streams
> How does this operate with flat volumes?

We don't plan on using flat volumes anymore, but system-wide classes of volumes. So one volume for all the playback apps, for example.

> An application should not be able to set the default sink/source without authorisation

This is likely something we'd need to offer either in a system menu, or as a portal.

> Having some output devices not being granted "play" access by default seems like a nice option though.

That's perhaps the worst decision we can make.

**Comment by HulaHoopWhonix** [comment]
When discussing audio system restrictions for contained apps with a similar isolation project (FireJail), the dev pointed out malicious apps may still bypass this by going directly to the ALSA modules and ignoring PulseAudio altogether.

https://github.com/netblue30/firejail/issues/419#issuecomment-228318501

**Comment by HulaHoopWhonix** [comment]
When discussing audio system restrictions for contained apps with a similar isolation project (FireJail), the dev pointed out malicious apps may still bypass this by going directly to the ALSA modules and ignoring PulseAudio altogether.

So a solution is needed to possibly block access to the latter.

https://github.com/netblue30/firejail/issues/419#issuecomment-228318501

**Comment by tanuk** [comment]
Bypassing pulseaudio would require access to /dev/snd/*, which I expect sandboxed applications to not have.

**Comment by matthiasclasen** [comment]
Indeed.

sh-4.3$ ls /dev
console  full  null  ptmx  pts	random	shm  stderr  stdin  stdout  tty  urandom  zero

**Comment by matthiasclasen** [comment]
I've pushed some work towards this here:

https://github.com/matthiasclasen/xdg-desktop-portal/tree/device
https://github.com/matthiasclasen/pulseaudio/tree/portal

**Comment by HulaHoopWhonix** [comment]
@tanuk @matthiasclasen

Interesting. So how do you allow sandboxed apps to use pulseaudio if access to sound devices is blocked?

**Comment by ford-prefect** [comment]
The app is sandboxed, PulseAudio is not (in the future, it can be sandboxed but permitted to used the `/dev/snd/*` devices, but applications themselves would have to talk to PulseAudio to play/record/control audio).

**Comment by matthiasclasen** [comment]
https://github.com/matthiasclasen/pulseaudio/tree/flatpak

is rebased on a pulseaudio fixes from wtay, should actually work (since it now gets the proper pid via peer creds)

**Comment by a-darwish** [comment]
@HulaHoopWhonix To answer your question, clients ususally connect to the PulseAudio server using two mechanisms:
- `/run/user/$UID/pulse/native`: Used for the initial handshake with the server, for the server to get information about the client through kernel-trusted mechanisms ([SCM_CREDENTIALS](http://man7.org/linux/man-pages/man7/unix.7.html)), for commands-exchange between client and server through a well-defined protocol, etc.
- `/dev/shm/pulse/pulse-shm-*`: Used for clients to send playback audio to the server, for server to send recorded microphone audio to clients, for the [shared ringbuffer channel](https://www.freedesktop.org/wiki/Software/PulseAudio/Notes/6.0/#performanceimprovements) mechanism, etc. Since [v9.0](https://www.freedesktop.org/wiki/Software/PulseAudio/Notes/9.0/#memfd-backedsharedmemorytransport), this can be replaced with memfds which allows us to use shared memory without breaking apps boundary.

Given the above, you can get audio sandboxing by:

1. Blocking ALSA access to apps by blocking `/dev/snd/*`
2. Blocking POSIX SHM by giving each app its own `/dev/shm/` domain
3. Passing only the PulseAudio socket to the sandbox, and adding an access-control layer to the PulseAudio daemon. The access-control layer can then provide decisions based on the client PID, which is given by a trusted component: _the kernel_. This PID can then be used to determine if the app is sandboxed or not by asking the kernel if the app is in a systemd flatpak control group. That is, if `/proc/$PID/cgroup` has a line in the form of `1:name=systemd:.*flatpak-.*`

**Comment by matthiasclasen** [comment]
Fedora ships the puleaudio bits in F26, so you get a device access portal dialog.
This still needs to go into upstream pulseaudio

**Comment by fenryxo** [comment]
> From the AccessControl for PulseAudio document:
> An application should only be able to perform [whatewer] on its own input and output streams.

What exactly do "an application" and "its own" mean?

1. Let's say the main process of an application launches a subprocess to play audio. Will be the main process able to control the audio of its child processes? And grandchildren, etc.?
2. Let's say the main process of an application launches a subprocess to play audio, but the subprocess detaches from the parent (i.e., the parent PID is the init daemon or Flatpak's equivalent thereof). Will be the main process able to control the audio of its "detached" child processes? And grandchildren, etc.?

A real-world example is WebKitGTK, which plays audio in subprocesses, and I'd like the main process to be able to mute the audio when headphones are unplugged.

**Comment by hadess** [comment]
> What exactly do "an application" and "its own" mean?

An application is what runs inside a single Flatpak container. How you do your sauce inside is up to you. The "code" inside the Flatpak should not be able to control other applications or system configuration.

> A real-world example is WebKitGTK, which plays audio in subprocesses, and I'd like the main process to be able to mute the audio when headphones are unplugged.

This sounds like something which should be implemented in PulseAudio, not in the application.

And any questions you might have would probably be best served by PulseAudio developers.

**Comment by matthiasclasen** [comment]
I think I'll close this. We have the basics in place
