### ISSUE TITLE
Error getting permissions: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for inhibit

### ISSUE THREAD

**Issue by mcatanzaro** [flatpak/xdg-desktop-portal#272]
I've been trying to debug why my computer is turning off the display when watching YouTube video longer than 5m. Turns out there's an unrelated bug in WebKit causing it to not attempt to use the inhibit portal at all. Anyway, with my WebKit modified to avoid that, and hacked up a bit to try using the portal even when running outside flatpak, then when running `/usr/libexec/xdg-desktop-portal --verbose`, I see:

```
(/usr/libexec/xdg-desktop-portal:61123): WARNING **: 15:27:37.829: Error getting permissions: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for inhibit
```

That occurs at the top of `get_allowed_inhibit` in inhibit.c. Not sure how this permission store is supposed to work, but seems like it's broken?

Note: I'm running WebKit outside flatpak, just for testing purposes.

**Comment by matthiasclasen** [comment]
The permission warnig is a red herring - by default, the portal allows all inhibiting, and nothing ever creates permissions to change that. We should not warn there.

As far as I can determine with my portal test app, it calls the Inhibit portal, the Inhibit portal calls its backend, the backend calls org.gnome.SessionManager.Inhibit, the inhibitor shows up in d-feet, and gnome-shell sees it and pops up the dialog when I try to log out.

So,as far as portals are concerned, everything is a-ok.

**Comment by mcatanzaro** [comment]
> It uses the portal directly: https://github.com/WebKit/webkit/blob/89c28d471fae35f1788a0f857067896a10af8974/Source/WebCore/PAL/pal/system/glib/SleepDisablerGLib.cpp#L74-L96

Note I've locally disabled all the code that tries using org.freedesktop.ScreenSaver to ensure it only tries using the portal.

**Comment by mcatanzaro** [comment]
Yeah it looks like the portal is working properly. I got tricked by a WebKit bug, and that bogus warning. So let's repurpose this bug for the warning, then?

**Comment by matthiasclasen** [comment]
Sure
