### ISSUE TITLE
org.freedesktop.portal.Desktop: Timeout was reached

### ISSUE THREAD

**Issue by bilelmoussaoui** [flatpak/xdg-desktop-portal#274]
Since my latest update on Fedora Rawhide, the apps are taking much longer to open. I can't click on links, nor for apps to open a browser window.

It seems to be related to this error/warning message.

Clocks(from gnome-apps-nightly): taking a lot of time to open, freeze after that
```
 Gdk-WARNING **: 01:29:08.324: Settings portal not found: Error calling StartServiceByName for org.freedesktop.portal.Desktop: Timeout was reached
```
Fractal(stable, from flathub): not being able to open links
```
(fractal:2): GLib-GIO-WARNING **: 01:35:40.249: Cannot create document portal proxy: Error calling StartServiceByName for org.freedesktop.portal.Desktop: Timeout was reached
```
INFO:
```
bilelmoussaoui@localhost ~> cat /etc/fedora-release 
Fedora release 30 (Rawhide)
```

```
bilelmoussaoui@localhost ~> dnf info xdg-desktop-portal
Installed Packages
Name         : xdg-desktop-portal
Version      : 1.0.3
Release      : 1.fc30
Arch         : x86_64
Size         : 1.5 M
Source       : xdg-desktop-portal-1.0.3-1.fc30.src.rpm
Repo         : @System
From repo    : rawhide
Summary      : Portal frontend service to flatpak
URL          : https://github.com/flatpak/xdg-desktop-portal/
License      : LGPLv2+
Description  : xdg-desktop-portal works by exposing a series of D-Bus interfaces known as
             : portals under a well-known name (org.freedesktop.portal.Desktop) and object
             : path (/org/freedesktop/portal/desktop). The portal interfaces include APIs for
             : file access, opening URIs, printing and others.
```

**Comment by matthiasclasen** [comment]
What does this say ?

```
/usr/libexec/xdg-desktop-portal-gtk --replace --verbose
/usr/libexec/xdg-desktop-portal --replace --verbose 
```

**Comment by bilelmoussaoui** [comment]
I just keep receiving this 
<pre>(fractal:2): Gdk-<font color="#657B83"><b>WARNING</b></font> **: <font color="#268BD2">14:42:57.633</font>: Failed to read portal settings: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop
</pre>

**Comment by matthiasclasen** [comment]
Yeah, that is gtk telling you that the Settings portal is not there. We should maybe tone that down, since we fall back to the old way of doing things.

**Comment by jadahl** [comment]
Try running with https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/merge_requests/95.

**Comment by jokeyrhyme** [comment]
@julianfairfax if you aren't running GNOME, the easiest fix would be to make sure xdg-desktop-portal-gnome is not installed

**Comment by keachi** [comment]
I don't know how you did that, but your all my heros! I had a similar issue and found this thread. Suddenly I found an issue in my nix config which I searched for hours now. You're such great people! :-)
