### ISSUE TITLE
Can't save app state on reboot/shutdown

### ISSUE THREAD

**Issue by ghost** [flatpak/xdg-desktop-portal#282]
Lollypop uses Gio.Application.shutdown signal to save current state on logout/shutdown/reboot.

It works well when installed with RPM/Deb/Pacman...

It was not working in flatpak so I added a catch on SIGINT/SIGTERM to save state but it's not working either.

What is happening when I logout, why GTK apps do not receive shutdown signal? Why catching SIGINT/SIGTERM does not work?

**Comment by matthiasclasen** [comment]
Here is a minimal implementation of session state support:

https://github.com/flatpak/xdg-desktop-portal/pull/294
https://github.com/flatpak/xdg-desktop-portal-gtk/pull/178
https://gitlab.gnome.org/GNOME/gtk/merge_requests/519

**Comment by fbruetting** [comment]
Can this be added to the milestone v1.5? 😬

**Comment by matthiasclasen** [comment]
No need, it was merged for 1.4
