### ISSUE TITLE
notifications portal invokes bubblewrap in a way that won't work on pure 32-bit

### ISSUE THREAD

**Issue by smcv** [flatpak/xdg-desktop-portal#288]
The notifications portal uses `bwrap ... --ro-bind /lib64 /lib64`, which will only work if you have `/lib64`. Pure 32-bit systems (such as i386 with no x86_64 biarch support, and 32-bit ARM with no aarch64 biarch support) typically won't have that directory.

I'm testing a patch for this, based on fixes previously made in libgnome-desktop.

**Comment by matthiasclasen** [comment]
I have a fix for that locally

**Comment by matthiasclasen** [comment]
Pushed a fix, testing appreciated
