### ISSUE TITLE
An option to remember the selection in the application portal

### ISSUE THREAD

**Issue by furkanusta** [flatpak/xdg-desktop-portal#302]
I am using Zotero flatpak application and every time I try to open a pdf file it brings up the Application selection portal and I have to choose evince from there. It would be useful if they can use the default application in the system or have a checkbox in the portal to remember the selection. 

This issue seems to be already reported in the Zotero flathub page: https://github.com/flathub/org.zotero.Zotero/issues/15

And kind of related to #126

**Comment by A6GibKm** [comment]
This also applies to open attachments in org.gnome.Geary and org.gnu.emacs.

**Comment by rvlobato** [comment]
Also, for org.telegram.desktop

**Comment by Khyber3737** [comment]
Same problem on nwjs applications. It gets really annoying and often the Open With window appears twice.

**Comment by go-ten** [comment]
also for Thunderbird and Shotwell.

Any news ?

Regards

**Comment by matthiasclasen** [comment]
The portal remembers the choice. It also has a threshold mechanism to stop asking if you chose the same app for a certain number of times. But it is currently not being used - nobody set the the threshold to something smaller than MAXINT

**Comment by Fak3** [comment]
> But it is currently not being used - nobody set the the threshold to something smaller than MAXINT

Oh, where can i configure this? Is that runtime option or build-time?

**Comment by matthiasclasen** [comment]
I've now changed things so that the portal will stop asking if you choose the same app 3 times
