### ISSUE TITLE
Fuse mount `/run/user/1000/doc` unavailable after sleep 

### ISSUE THREAD

**Issue by divoxx** [flatpak/xdg-desktop-portal#305]
I'm running Flatpak on Gentoo and it seems like the `/run/user/1000/doc` fuse mount is unmounted when going into sleep and then not re-mounted after it wakes up.

This is what I see before going into sleep/hibernate, and it's gone after waking up:

```
/dev/fuse on /run/user/1000/doc type fuse (rw,nosuid,nodev,relatime,user_id=1000,group_id=1000)
```

I've tried running `xdg-document-portal` manually with debug logging, to see if there is any error happening when waking up but there is no additional output after the initial output when running the command:

Before sleeping:

```
$ env G_MESSAGES_DEBUG=all /usr/libexec/xdg-document-portal --replace --verbose
XDP: org.freedesktop.portal.Documents acquired
XDP: xdp_fuse_getattr 1 (fi=(nil))
XDP: xdp_fuse_getattr <- OK
XDP: xdp_fuse_access 1 4
XDP: xdp_fuse_lookup 1/.Trash ->
XDP: xdp_fuse_lookup <- error child ENOENT
XDP: xdp_fuse_lookup 1/.Trash-1000 ->
XDP: xdp_fuse_lookup <- error child ENOENT
```
After sleep, the output is still the same, no additional output. Restarting that command does fix the problem and the mount is established again.

Let me know if I can provide any additional information.

**Comment by bLuka** [comment]
Heya, I've got the exact same issue when resuming after suspend, needing to reboot after suspends when I want to run any flatpak app. /run/user/1000/doc is empty.

Gentoo with Gnome/OpenRC here; and as mentionned, restarting xdg-document-portal after a suspend did fix the issue.

**Comment by ploth** [comment]
Yep, same here.

**Comment by matthiasclasen** [comment]
Any idea what is responsible for unmounting fuse fs on suspend/hibernate ?

**Comment by matthiasclasen** [comment]
This should be fixed in master - the portal now exists when its fuse mount gets unmounted externally.
