### ISSUE TITLE
O_PATH isn’t supported on FreeBSD

### ISSUE THREAD

**Issue by pwithnall** [flatpak/xdg-desktop-portal#307]
I have no personal interest in FreeBSD, but while looking at [this GLib MR](https://gitlab.gnome.org/GNOME/glib/merge_requests/704) it seems that xdg-desktop-portal has a hard requirement on `O_PATH`, and hence can’t currently work on FreeBSD.

FreeBSD doesn’t have `O_PATH` (or anything like it, in my limited understanding). That’s an architectural stumbling block in xdg-desktop-portal which is probably going to have to be overcome at some point.

**Comment by matthiasclasen** [comment]
I don't think it is worth keeping this open until somebody shows up with an active interest in building portals on freebsd

**Comment by pwithnall** [comment]
The point was that the architecture is designed such that supporting FreeBSD is impossible at the moment; this issue was supposed to be about potentially changing the architecture so it *could* be supported (even if we didn’t do the work to add that support ourselves). However, I don’t care enough to push for this, and this architecture has now been released, so it’s on the FreeBSD people to rework things when they get round to it.

**Comment by matthiasclasen** [comment]
I don't think the portals are the biggest hurdle here. Flatpak is stuffed to the brim with linux-specific apis
