### ISSUE TITLE
Notifications: Validator Does Not Support GFileIcon

### ISSUE THREAD

**Issue by BrainBlasted** [flatpak/xdg-desktop-portal#317]
Currently the icon validator [does not accept GFileIcon](https://github.com/flatpak/xdg-desktop-portal/blob/cc70c0b73d5a8e85a2c0a035743e770e5c0d0f76/src/notification.c#L3140). This means that when we switched to using GNotification in Fractal, our notifications were broken because we [used GFileIcon to set the avatar](https://gitlab.gnome.org/GNOME/fractal/blob/152255031400049a30667c581c0dc31a4ef03146/fractal-gtk/src/appop/notify.rs#L90). xdg-desktop-portal-gtk supports GFileIcon.

**Comment by TingPing** [comment]
There are complications with file access about ensuring who has the rights to read what, everything becomes more simple (if technically slower) for you to just send the bytes since the application clearly always has access to the bytes.

**Comment by BrainBlasted** [comment]
That makes sense. Could this be an "at your own risk" thing? In Fractal's case, we do have access since
the files are within our sandboxed cache.

If not, perhaps there should be a warning somewhere when using a GFileIcon?

**Comment by mcatanzaro** [comment]
Problem is the portal's view of the filesystem is not the same as the app's, so an app telling the portal to display a notification with a file inside the sandbox is just not going to work. The app can point to /usr/share/icons, but on the host system the path will be under /var/lib/flatpak. I just spent two hours on this and didn't realize it until I read this issue. <_<

@TingPing: xdg-desktop-portal-gtk has explicit support for GFileIcon in call_notify(), in notification.c. That should be removed.

Also: we should consider whether an invalid icon is really worth torpedoing the entire notification over.

**Comment by BrainBlasted** [comment]
Hmm. How can we pass the avatar then? GBytesIcon doesn't work.

**Comment by mcatanzaro** [comment]
GBytesIcon should work.

**Comment by mcatanzaro** [comment]
BTW @TingPing: there's no indication in the documentation of `g_notification_set_icon()` that certain GIcon types are disallowed, none at all. And developers won't notice because it will work fine outside flatpak. Problem could be avoided entirely by adding a new serialization function to the GIcon interface, `g_icon_serialize_to_bytes_icon()`, for example, that would allow converting any GIcon types that implement it (probably just GFileIcon) to GBytesIcon.

**Comment by TingPing** [comment]
I'm not sure if this was discussed in an issue, but yes this can be entirely transparent to applications since a file can always be turned into bytes.

**Comment by matthiasclasen** [comment]
https://gitlab.gnome.org/GNOME/glib/merge_requests/827

**Comment by mcatanzaro** [comment]
So close this?
