### ISSUE TITLE
Desktop file portal

### ISSUE THREAD

**Issue by lionirdeadman** [flatpak/xdg-desktop-portal#326]
Certain programs (Lutris, Epiphany, menulibre, etc.) may want to create desktop files, we should give a portal to do so.

We probably want a way to track what files each flatpak create to remove them when the flatpak is deleted.

**Comment by TingPing** [comment]
This was just briefly discussed by Epiphany and some thoughts brought up:

Not only does `flatpak` need to have knowledge of these new launchers but also stores like `gnome-software` will want appdata and the ability to delete them itself most likely via a new `flatpak` API.

**Comment by sonnyp** [comment]
[ Dynamic Launcher Portal design questions #681](https://github.com/flatpak/xdg-desktop-portal/issues/681)

**Comment by mwleeds** [comment]
Released in 1.14.0
