### ISSUE TITLE
urls and directories always open in the same app

### ISSUE THREAD

**Issue by Fak3** [flatpak/xdg-desktop-portal#330]
xdg-desktop-portal-kde v5.15.3. Flatpak v 1.2.3 on openSUSE
Tumbleweed

I have installed slack client from flathub. Every time when i click url in slack or open directory, xdg-desktop-portal launches seamonkey without even asking xdg-desktop-portal-kde.

xdg-desktop-portal log:
```
XDP: Content type for https://github.com/ uri https: x-scheme-handler/https
XDP: launching seamonkey https://github.com/
```
xdg-desktop-portal-kde log is empty.

In contrast, when i open yaml file from the slack app, i see the dialog to choose the application to open file, as expected.

xdg-desktop-portal-kde logs the request:
```
xdp-kde-app-chooser: ChooseApplication called with parameters:
xdp-kde-app-chooser:     handle:
"/org/freedesktop/portal/desktop/request/1_206/t"
xdp-kde-app-chooser:     app_id:  "com.slack.Slack"
xdp-kde-app-chooser:     parent_window:  ""
xdp-kde-app-chooser:     choices:  ("wine-extension-rgs",
"wine-extension-lst", "wine-extension-pyw", "wine-extension-asm",
"wine-extension-inl", "wine-extension-cod", "wine-extension-tli",
"wine-extension-dsp", "wine-extension-s", "wine-extension-mdp",
"wine-extension-def", "wine-extension-odl", "wine-extension-map",
"wine-extension-sln", "wine-extension-dsw", "wine-extension-inc",
"wine-extension-odh", "wine-extension-i", "wine-extension-tlh",
"org.kde.kate", "wine-extension-txt", "okularApplication_txt",
"writer", "org.gnome.gedit")
xdp-kde-app-chooser:     options:  QMap(("content_type",
QVariant(QString, "application/x-yaml"))("filename", QVariant(QString,
"VoyageScheduleAPI.yaml"))("uri", QVariant(QString,
"file:///home/u1/Downloads/VoyageScheduleAPI.yaml")))
```

xdg-desktop-portal should ask which app to open url or directory with, as it does for regular files.

**Comment by Erick555** [comment]
See https://github.com/flatpak/xdg-desktop-portal/issues/306#issuecomment-532240015

**Comment by matthiasclasen** [comment]
We special-case http and https and directly open such urls in the default browser.
