### ISSUE TITLE
screen cast is broken with pipewire 0.2.6

### ISSUE THREAD

**Issue by michaelolbrich** [flatpak/xdg-desktop-portal#342]
Pipewire changed the permission handling in the latest release (Commit PipeWire/pipewire@83bc033837f7525d898f1de91119f669f9bf97f5).

Now the permissions of all parent nodes are checked as well. Because of this screen casting fails because the parent node of the node factory is not accessible.

See also: PipeWire/pipewire#158

**Comment by matthiasclasen** [comment]
@jadahl can you have a look at this ?

**Comment by jadahl** [comment]
What version of xdg-desktop-portal are you using? It should have been fixed with https://github.com/flatpak/xdg-desktop-portal/pull/331.

**Comment by michaelolbrich** [comment]
I'm using 1.4.2. #331 is incomplete but it showed me how to fix it.
