### ISSUE TITLE
Document portal test intermittently fails

### ISSUE THREAD

**Issue by smcv** [flatpak/xdg-desktop-portal#349]
In x-d-p 1.2.0 and 1.4.2, the document portal test intermittently fails with:

```
tests/test-doc-portal.c:695:test_add_named: assertion failed (error == NULL): Can't open .../add-named-1 (g-file-error-quark, 23)
```

GFileError 23 is basically `ENOSYS`.

This was initially hard to reproduce (I had to run the tests 1000 times in a loop to see it happen locally), but I'm seeing it a lot more often now for some reason.

By adding more logging, I was able to track this down to this error code path in `xdp_inode_create_file()` intermittently being hit:

```
      if (truncate)
        {
          /* TODO: Handle extra truncate for existing file */
          errno = ENOSYS;
          return NULL;
        }
```

so presumably something has changed in the test's file access pattern to make it truncate the virtual file more than once?

**Comment by smcv** [comment]
I'm still seeing this sometimes with 1.6.0.

**Comment by GeorgesStavracas** [comment]
Simon, can you still reproduce this with 1.15?

**Comment by GeorgesStavracas** [comment]
Simon, can you reproduce these intermitent failures with xdg-desktop-portal 1.18.0?

**Comment by GeorgesStavracas** [comment]
After an year without response, I'll take the liberty to assume timeout and close this.

Please reopen if it's still reproducible with 1.18.2+
