### ISSUE TITLE
Make it possible to override org.gnome.desktop.interface enable-animations

### ISSUE THREAD

**Issue by jadahl** [flatpak/xdg-desktop-portal#361]
Currently the xsettings plugin in gnome-settings-daemon overrides the `org.gnome.desktop.interface enable-animations` setting whenever a Vino VNC connection is active, effectively disabling animations session wide. Well. Almost; it only works for Xsettings clients listening for `Gtk/EnableAnimations`.

The idea is to make this work again by having the `org.gnome.Mutter.RemoteDesktop` session ask for it instead of relaying on specific services. What is needed for xdg-desktop-portal is a way for the desktop environment (i.e. GNOME Shell) to override the mentioned setting temporarly, similarly to how the xsettings plugin in gnome-settings-daemon did via Xsettings.

I suppose either it should be a D-Bus API in the portal service to allow overriding, or we need a way to outsource overriding to xdg-desktop-portal-gtk and call into GNOME Shell some how from there.

**Comment by TingPing** [comment]
`xdg-desktop-portal` forwards along GSettings so nothing has to change there, GTK just needs to respect it. This is probably something to be handled along with https://gitlab.gnome.org/GNOME/gtk/issues/2029

**Comment by jadahl** [comment]
Right, the GSetting is forwarded, but it should be possible to override it, just as it was temporarly overridden via Xsettings via the xsettings gnome-setting-daemon plugin.

What we don't want to do is to fiddle back and forth with the actual gsetting.

**Comment by TingPing** [comment]
> Right, the GSetting is forwarded, but it should be possible to override it, just as it was temporarly overridden via Xsettings via the xsettings gnome-setting-daemon plugin.

I'm not sure I follow TBH. `gsd-xsettings` converts `gsettings` into `xsettings`, this is not really relevant to the conversation.

Your problem is simply that GTK itself does not respect the setting directly and that should be reported to GTK, probably in the bug I already linked saying it doesn't respect all settings as it should.

**Comment by jadahl** [comment]
gsd-xsettings doesn't only convert gsettings into Xsettings, it override certain gsettings depending on various state, for example the `enable-animations` which is changed to false whenever there is a Vino connection active, meaning the Xsetting for `enable-animations` may be false, while the gsetting is true. In this case, gtk respects the Xsetting instead of the gsetting. This is what needs to be supported by the Settings portal, but to support this, I need a way to communicate this from the Shell, which is the one who will know when or when not to override.

**Comment by TingPing** [comment]
> meaning the Xsetting for enable-animations may be false, while the gsetting is true.

Why is this desired?

**Comment by hadess** [comment]
> Why is this desired?

It's explained in the first comment.

The XSettings plugin in gnome-settings-daemon overrides the exported value of `enable-animations` when a remote computer is connected to the display:
https://gitlab.gnome.org/GNOME/gnome-settings-daemon/blob/master/plugins/xsettings/gsd-xsettings-manager.c#L1075

This was written a long time ago, and probably doesn't work any more with 1) Wayland 2) Portalification of those settings

**Comment by jadahl** [comment]
> This was written a long time ago, and probably doesn't work any more with 1) Wayland 2) Portalification of those settings

X11 Gtk applications probably work still, and gnome-shell up until 3.32, but 3.34 will no longer listen to the Xsetting no matter what session, so we just regressed there a bit this cycle.

**Comment by TingPing** [comment]
> The XSettings plugin in gnome-settings-daemon overrides the exported value of enable-animations when a remote computer is connected to the display:
gitlab.gnome.org/GNOME/gnome-settings-daemon/blob/master/plugins/xsettings/gsd-xsettings-manager.c#L1075

OK but is it not reasonable for all of this logic to just happen in the toolkit? If so we are back to my comment, this is a GTK issue.

**Comment by jadahl** [comment]
> OK but is it not reasonable for all of this logic to just happen in the toolkit? If so we are back to my comment, this is a GTK issue.

It is not reasonable for the toolkit to be able to introspect the session itself to detect if there are any services or requests that should override the gsetting. It's not only unreasonable, it simply can't.

**Comment by TingPing** [comment]
> It is not reasonable for the toolkit to be able to introspect the session itself to detect if there are any services or requests that should override the gsetting. It's not only unreasonable, it simply can't.

I'm really sorry for this back and forth, I'm not trying to be difficult and I don't think I'm an idiot but I seriously do not understand what complication you are talking about.

I don't know what introspection or detection complexity you are talking about and it seems extremely simple to me. Please correct me if I'm missing something.

There are two settings that gsd-xsettings reads:

- A global animations setting
- A GsdRemoteDisplayManager animation setting that:
  - Disables animations when Vino is running
  - Disables animations when llvmpipe is used
  - Disables animations when XVnc is detected

And GsdRemoteDisplayManager when disabled has priority over the global setting.

So my thoughts would be (and not all of these need to be done but they all accomplish similar things):

- GNOME-Shell can detect llvmpipe and set a global setting or just disable it for itself
- GTK can detect llvmpipe itself and disable its animations
- We don't care about the Vino interface anymore since the VNC bits are in GNOME-Shell now right? But anyway even if we do why can't Vino just set a global GSetting when its running. GNOME-Shell again can set a global setting when its internal VNC is in use.

I don't understand why a daemon has to be involved with this on Wayland which doesn't use XSettings.

**Comment by jadahl** [comment]
> * GNOME-Shell can detect llvmpipe and set a global setting or just disable it for itself

It can disable it itself, but it cannot set a global setting. As I wrote in https://github.com/flatpak/xdg-desktop-portal/issues/361#issuecomment-528728361 we do *not* want to fiddle with users actual settings here.

> * GTK can detect llvmpipe itself and disable its animations

Sure it can. But then it'd have to open a OpenGL context every time even though it will only be used to disable animations.

> 
> * We don't care about the Vino interface anymore since the VNC bits are in GNOME-Shell now right? But anyway even if we do why can't Vino just set a global GSetting when its running. GNOME-Shell again can set a global setting when its internal VNC is in use.

GNOME Shell has no VNC code; what it has is functionality that streams the desktop or windows via PipeWire. gnome-remote-desktop has VNC code that turns said PipeWire stream into VNC magic. What gnome-remote-desktop would do is to let gnome-shell know it would prefer if there were no animations, then gnome-shell can take that into account and try to propagate this to the desktop as a whole. We could have it talk to xdg-desktop-portal directly too of course, but I think GNOME Shell is in a better position to decide such things.

As reiterated above, we should *not* mess with users setting by poking around in dconf directly for overriding this, we should solve it in the same way as as it was in the past by using something equivalent of Xsettings. That, in the sandboxed Wayland world is org.freedesktop.portal.Settings. We just need a way to do it.

**Comment by TingPing** [comment]
> As I wrote in #361 (comment) we do not want to fiddle with users actual settings here.

Is every setting in DConf "user settings" because gnome can certainly create one and consider it a private one.

> Sure it can. But then it'd have to open a OpenGL context every time even though it will only be used to disable animations.

For GTK3 yeah its not worth doing but GTK4 gets the check for free.

**Comment by matthiasclasen** [comment]
https://github.com/flatpak/xdg-desktop-portal-gtk/pull/230

**Comment by matthiasclasen** [comment]
Once this is merged, we can remove the gsettings code from the frontend
