### ISSUE TITLE
Document portal fails to start on ubuntu 18.04

### ISSUE THREAD

**Issue by evan-a-a** [flatpak/xdg-desktop-portal#369]
I'm running on Ubuntu 18.04, and the document portal will not start. The following error is printed in the journal:

```
Oct 01 16:18:26 cube-63 xdg-document-portal[5234]: error: Failed to load db: Error opening file /home/eanderson/.local/share/flatpak/db/documents: No such file or directory
Oct 01 16:18:26 cube-63 systemd[29198]: xdg-document-portal.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Oct 01 16:18:26 cube-63 systemd[29198]: xdg-document-portal.service: Failed with result 'exit-code'.
Oct 01 16:18:26 cube-63 systemd[29198]: Failed to start flatpak document portal service.
```

The output of `flatpak run -v org.keepassxc.KeePassXC` is as follows. Notice the point where it hangs for some amount of time.
```
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/eanderson/.local/share/flatpak
F: Opening user flatpak installation at path /home/eanderson/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/eanderson/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Cleaning up unused container id 2907156221
F: Allocated instance id 1375140701
F: Add defaults in dir /org/keepassxc/KeePassXC/
F: Add locks in dir /org/keepassxc/KeePassXC/
<HANG HERE FOR 10-20s>
F: Allowing host-fs access
F: Allowing wayland access
F: Allowing x11 access
F: Running '/usr/libexec/flatpak-bwrap --args 35 /usr/libexec/flatpak-dbus-proxy --args=37'
F: Running '/usr/libexec/flatpak-bwrap --args 35 command-wrapper.sh'
Gtk-Message: 16:18:57.334: Failed to load module "canberra-gtk-module"
Gtk-Message: 16:18:57.335: Failed to load module "canberra-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
```

This is on a system with home on an NFS share. Interestingly, in my test VM that runs without NFS, xdg-document-portal launches fine. I attempted some step through in gdb, but I need to do so with a proper debug build. It appears that `g_initable_new` at https://github.com/flatpak/xdg-desktop-portal/blob/master/document-portal/permission-db.c#L127 is unable to initialize the database properly.

**Comment by evan-a-a** [comment]
Update, I attempted a build on the up-to-date NFS-based 18.04 and it does fail tests.

```
================================================
   xdg-desktop-portal 1.2.0: ./test-suite.log
================================================

# TOTAL: 10
# PASS:  9
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 1

.. contents:: :depth: 2

ERROR: testdb
=============

**
xdg-desktop-portal:ERROR:tests/testdb.c:160:test_db_open: assertion failed (error == (g-file-error-quark, 4)): Error opening file /home/eanderson/xdg-desktop-portal-1.2.0/tests/dbs/does_not_exist: No such file or directory (g-io-error-quark, 1)
Aborted
# random seed: R02Sa69f9036af1c02a896369c96699ea1aa
1..3
# Start of db tests
Bail out! xdg-desktop-portal:ERROR:tests/testdb.c:160:test_db_open: assertion failed (error == (g-file-error-quark, 4)): Error opening file /home/eanderson/xdg-desktop-portal-1.2.0/tests/dbs/does_not_exist: No such file or directory (g-io-error-quark, 1)
ERROR: testdb - Bail out! xdg-desktop-portal:ERROR:tests/testdb.c:160:test_db_open: assertion failed (error == (g-file-error-quark, 4)): Error opening file /home/eanderson/xdg-desktop-portal-1.2.0/tests/dbs/does_not_exist: No such file or directory (g-io-error-quark, 1)
```

**Comment by matthiasclasen** [comment]
This looks like nfs is giving us an unexpected error.

Curiously, we do have code to handle nfs specially:

https://github.com/flatpak/xdg-desktop-portal/blob/master/document-portal/permission-db.c#L240

**Comment by matthiasclasen** [comment]
A quick and dirty attempt at running the tests on a locally mounted nfs export did not produce a failure here.

**Comment by evan-a-a** [comment]
@matthiasclasen Did you test with the user home living on an NFS export? It seems to be related to where the database is being created.

I may have time tomorrow to do proper debugging of the issue.

**Comment by matthiasclasen** [comment]
I did a quick and dirty test with a manually mount, local export. I see a few issues with the is_on_nfs check - if path I give to it has non-existing directory components, then statfs fails. If I walk up the tree to find an existing directory, and i end up at the mountpoint, statfs succeeds, but gives me the EXT3 magic for the mountpoint

**Comment by evan-a-a** [comment]
Statfs results look fine to me. I did some more looking and I think I figured out the problem.

in the `is_on_nfs` TRUE path in `initable_init`, `g_file_new_for_path` is called to create a GFile object for the path, then it attempts to load the contents of the file with `g_file_load_contents`, which fails because the file doesn't exist on disk. `g_file_new_for_path` doesn't create the file on disk, it just creates the GFile object. Should the permissions DB exist on disk at this point?

**Comment by matthiasclasen** [comment]
No, that is fine and it is handled later, with the fail_if_not_found boolean.

Are you positive that you end up in the is_on_nfs TRUE path ?

statfs is documented to fail with  ENOENT if the file referred to by path does not exist.

**Comment by evan-a-a** [comment]
I'm certain it's in the true path. I set my breakpoint at the `is_on_nfs` call site and followed it into the body of the if.

Statfs is returning zero for me, not ENOENT, so perhaps there's a statfs issue to look into? I will also verify that return code again.

**Comment by evan-a-a** [comment]
`rm`-ing the `~/.local/share/flatpak/db` directory allows the portal to start normally. The directory doesn't get re-created either. When the directory doesn't exist, statfs fails with ENOENT, and the code follows the "not on NFS" path. Not sure what created the empty db directory that lead to this failure, but I think the code should be refactored a bit to not fail when the directory exists but not the db.

**Comment by matthiasclasen** [comment]
Looking at lookup_table, there is a g_mkdir_with_parents, before calling permission_db_new. So we can rely on the directory being there.

Lets take a step back - what makes you think that the problem is with the permission db initialization ?

**Comment by evan-a-a** [comment]
Well, after removing the `db` directory, everything starts up fine. Flatpak applications launch with no delay. If the directory exists, the applications experience the 10-20s delay, and the portal fails to start at all with the documented error.

I'm still not seeing any recreation of the `db` directory by the document portal, so that behavior doesn't match what you're saying should happen.

**Comment by matthiasclasen** [comment]
it will not recreate it until an application uses a portal, and that portal stores a permission.

**Comment by evan-a-a** [comment]
If it creates the `db` directory, should it also always create the database inside of that directory?

**Comment by matthiasclasen** [comment]
no, the database gets saved when its content changes, see ensure_writeout in xdg-permission-store.c

**Comment by evan-a-a** [comment]
Then in the `is_on_nfs` path it should probably check that the file exists before attempting to load from the file, and then fall through to the mem mapped option to initialize data, like it would do when the db/ folder doesn't exist.

**Comment by evan-a-a** [comment]
Or rather, it should fall through if the file load fails instead of killing the entire application.

**Comment by matthiasclasen** [comment]
It doesn't kill the process. If loading fails, we end up in the

```
  if (self->gvdb_contents == NULL)
```

path below and look at self->fail_if_not_found to decide that we should ignore the error.

**Comment by evan-a-a** [comment]
Ahhh I see what's going on. `g_file_load_contents` returns this for its load failure: 

```
$7 = {domain = 0x6c, code = 0x1, message = 0x5555557a6d30}
```

This isn't the the expected error quark/message of G_FILE_ERROR/G_FILE_ERROR_NOENT, this is G_IO_ERROR/G_IO_ERROR_NOT_FOUND

**Comment by bedaro** [comment]
I was having a similar issue with xdg-desktop-portal failing to start and causing extremely slow launch times on snaps in Ubuntu 18.04. In may case, the cause was that ~/.local/share/flatpak had become owned by root with 700 permissions; chown'ing it fixed the problem. It sounds like this is related, but if you want I can create a new issue for it.

**Comment by evan-a-a** [comment]
@bedaro That's defienitely not this issue. The permissions are correct in this failure. I can't think of any way `~/.local/share/flatpak` would become owned by root unless it was launched by root or manually set.

**Comment by bedaro** [comment]
I wasn't trying to suggest xdg-desktop-portal was responsible for the directory ownership being incorrect, just that it was unable to handle the EACCES error in a graceful way. If the way it should be handled is different, then I'd agree that it's a different issue.

**Comment by mbousq** [comment]
Hi. Just had this issue in ubuntu 21.10. I have the impression this happened with a recent update in libxml2 :

`apt-cache policy libxml2`

```
libxml2:
  Installed: 2.9.12+dfsg-4ubuntu0.1
  Candidate: 2.9.12+dfsg-4ubuntu0.1
  Version table:
 *** 2.9.12+dfsg-4ubuntu0.1 500
        500 http://archive.ubuntu.com/ubuntu impish-updates/main amd64 Packages
        500 http://archive.ubuntu.com/ubuntu impish-security/main amd64 Packages
        100 /var/lib/dpkg/status
     2.9.12+dfsg-4 500
        500 http://archive.ubuntu.com/ubuntu impish/main amd64 Packages
```
`/usr/libexec/xdg-desktop-portal`

```
(/usr/libexec/xdg-desktop-portal:265193): GLib-GIO-CRITICAL **: 09:15:33.976: g_dbus_proxy_call_sync_internal: assertion 'G_IS_DBUS_PROXY (proxy)' failed
```
I found the culprit: I have a 0 byte "documents". **Deleting that file solves this bug**. But I don't know how that file was generated, neither if there is a connection with libxml2. Thanks for reading.

 <img src="https://user-images.githubusercontent.com/49107491/158558534-90856cb4-c8ae-4f16-8d08-6162bbb5ca07.png" width="500">

**Comment by smcv** [comment]
> Just had this issue in ubuntu 21.10

I think you had a different issue with a vaguely similar symptom. Please open a new, separate issue report with full details, instead of replying to an issue that was fixed more than 2 years ago.
