### ISSUE TITLE
remove gsettings code from frontend

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/xdg-desktop-portal#371]
We have a settings backend in xdg-desktop-portal-gtk now, so this code is no longer strictly needed.

What we should think about though is a way to merge the returns from the kde and gtk backends.

**Comment by TingPing** [comment]
> What we should think about though is a way to merge the returns from the kde and gtk backends.

The problem is that the settings are toolkit specific not desktop specific. Generally we want all platforms to have access to the same settings and I don't think it makes sense to require installing other platform portals.

**Comment by matthiasclasen** [comment]
I'm not saying we should require it, but there may be a case for merging the settings from all available backends
