### ISSUE TITLE
Support inhibition access

### ISSUE THREAD

**Issue by hadess** [flatpak/xdg-desktop-portal#39]
Applications using GTK+ should be able to use gtk_application_inhibit() as they did before, and GTK+ would poke a portal directly, instead of gnome-session (or org.freedesktop.ScreenSaver).

Note that the fd.o Inhibit API is less featureful than the gnome-session and GTK+ ones.

**Comment by matthiasclasen** [comment]
Pushed a simple inhibit portal in the inhibit branches in matthiasclasen/xdg-desktop-portal and matthiasclasen/xdg-desktop-portal-gtk. Still need to work out the gtk-in-the-sandbox side.

**Comment by matthiasclasen** [comment]
Done now on the portal branch of gtk.

The Inhibit portal looks into the permission store to find the allowed inhibitions for each app.

**Comment by matthiasclasen** [comment]
Bastien, does this look ok to you ?

**Comment by hadess** [comment]
This is overall fine, though I'm concerned that the -gtk implementation is really a -gnome implementation for which the only dependency is GTK+ (it relies on GNOME-only APIs).

It would be nice if this was made clearer. The API matches that of GTK+, so looks good.

**Comment by matthiasclasen** [comment]
Is there a cross-desktop interface that supports all the useful inhibitions? Or should we limit this to just inhibiting idle ? If we do that, we can implement the backend by talking to org.freedesktop.Screensaver

**Comment by hadess** [comment]
I don't think that applications that would end up being sandboxed have a lot of use for the other inhibitions other than "idle". But that would mean that most of the GTK+ API wouldn't have a map outside the sandbox.

As the portal implementation is long running, I'd make it look for gnome-session, and if not present, use the fd.o API and return an error if the flags are != IDLE.

**Comment by matthiasclasen** [comment]
I've done that now
