### ISSUE TITLE
Support PipeWire for sandboxed webcam access

### ISSUE THREAD

**Issue by alexlarsson** [flatpak/xdg-desktop-portal#414]
See:
https://blogs.gnome.org/uraeus/2015/06/30/introducing-pulse-video/

**Comment by xaiki** [comment]
just to keep this issue up to date, now that the Camera portal has been merged, we're missing code in FF itself right ?

**Comment by rmader** [comment]
Apparently this issue can be closed, there is some basic support for it, see https://gitlab.gnome.org/-/snippets/762

**Comment by saivert** [comment]
So there are no plans to offer something like `--socket=pipewire`?

**Comment by matthiasclasen** [comment]
Lets track better pipewire support separately.

**Comment by muelli** [comment]
Okay. Where can I subscribe to for getting updates on getting webcam access through gstreamer without having to pass `--device=all`?

**Comment by rmader** [comment]
@muelli: the snipped linked above (https://gitlab.gnome.org/-/snippets/762) does just that.
