### ISSUE TITLE
Allow custom ui in the print portal

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/xdg-desktop-portal#45]
The GTK+ print dialog has this feature, and it is in use e.g. in gedit.
We can do something in the same style as the combobox support in the file chooser portal.

**Comment by cjao** [comment]
Since GTK+ print dialog allows one to add arbitrary custom widgets (see the dialog for eog for example), would it be better to render the print dialog in the application process and just send the final print job through d-bus?

**Comment by matthiasclasen** [comment]
Lets close this, its not going to happen
