### ISSUE TITLE
Add "Select Folder" support to file chooser

### ISSUE THREAD

**Issue by hadess** [flatpak/xdg-desktop-portal#455]
Requires:
- documenting and allowing "directory" option in xdg-desktop-portal: https://github.com/flatpak/xdg-desktop-portal/pull/456
- implementing "directory" option in xdg-desktop-portal-gtk: https://github.com/flatpak/xdg-desktop-portal-gtk/pull/284
- wiring up GTK's native file chooser: https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/1523

**Comment by hadess** [comment]
I haven't finished the xdg-desktop-portal-gtk implementation, so I'll need to finish that up first and thoroughly test it.

**Comment by matthiasclasen** [comment]
thanks for working on this!

**Comment by hadess** [comment]
> I haven't finished the xdg-desktop-portal-gtk implementation, so I'll need to finish that up first and thoroughly test it.

It's done, but untested.
