### ISSUE TITLE
FileChooser portal should return the selected filter in its response

### ISSUE THREAD

**Issue by jhenstridge** [flatpak/xdg-desktop-portal#458]
At present, file choosers presented by xdg-desktop-portal do not make the user's filter selection available to the calling application.  This makes certain UI patterns where the filter choice changes behaviour impossible.

Some real world examples:

* Inkscape's save dialog includes the filters "Inkscape SVG (*.svg)" and "Plain SVG (*.svg)", with the latter omitting Inkscape specific metadata from the file to be saved.  As both formats share the same file extension, it can not infer the user's choice from the chosen file name.

* Firefox's "Save Page As..." dialog offers "Web Page, complete" and "Web Page, HTML only" filters.  In each case, the user selects a "*.html" file name. (I realise that "complete" mode can not work with document portal proxied paths: I just mention it as another example of the UI pattern).

I propose the following change:

1. That the `OpenFile` and `SaveFile` methods of the `org.freedesktop.impl.portal.FileChooser` add a `current_filter` item to their returned "results" vardict.  The format will be `sa(us)`, using the same serialization as the `current_filter` item accepted in the "options" vardict.

2. That the `OpenFile` and `SaveFile` methods of the `org.freedesktop.portal.FileChooser` be updated such that the results vardict returned via their `Request::Response` signal includes an item `current_filter`.  This value would be copied from the backend impl's result, if provided.

The changes to support this in xdg-desktop-portal-gtk and GTK proper should be fairly simple, and not create much of a problem w.r.t. backwards compatibility.

**Comment by matthiasclasen** [comment]
sounds good to me

**Comment by matthiasclasen** [comment]
This was fixed in 35fca7fae881bdaba1bebccf7775eba84407a488
