### ISSUE TITLE
Document cursor_mode appropriately in the ScreenCast implementation XML

### ISSUE THREAD

**Issue by danshick** [flatpak/xdg-desktop-portal#468]
The AvailableCursorModes property is defined at the top level, but the comment for the SelectSources results vardict only specifies "types" and "multiple" [here](https://github.com/flatpak/xdg-desktop-portal/blob/master/data/org.freedesktop.impl.portal.ScreenCast.xml#L70).

The comment should be amended to detail the "cursor_mode" key to aid developers in properly implementing the SelectSources handler.

**Comment by matthiasclasen** [comment]
@jadahl can you write a sentence ?
