### ISSUE TITLE
Secrets portal should have a secrets migrator

### ISSUE THREAD

**Issue by mcatanzaro** [flatpak/xdg-desktop-portal#483]
I've just accepted that I lost access to all my old Epiphany passwords when the secrets portal was released, due to the lack of migration. [Now Authenticator users are starting to complain too.](https://gitlab.gnome.org/World/Authenticator/-/issues/173) We might want to reconsider whether it was wise to deploy the secrets portal without any migration process.

**Comment by bersace** [comment]
Hi, I just hit the bug while upgrading to Debian bookworm. I think that bookworm release will produce tons of such issues.

Can anyone share a way to migrate secrets for flatpak apps ?

**Comment by RJVB** [comment]
> We might want to reconsider whether it was wise to deploy the secrets portal without any migration process.

Instead you just waited for the flak to die out?

**Comment by mcatanzaro** [comment]
Seems so.

I think this was a pretty awful choice, but it's been 4 years. A migration now would far too late. Time to move on.

**Comment by RJVB** [comment]
>I think this was a pretty awful choice, but it's been 4 years. A migration now would far too late. Time to move on.

It wouldn't be too late of course for those who've remained on LTS/legacy systems for all that time, but maybe by now there are known workarounds? If so it'd be nice to put some pointers here?

Export the existing passwords (how/with what? I'm a KDE user ;) ) and then import them again into the emptied/reset keyring (again, how/with what)?
