### ISSUE TITLE
notifications: Support inline-reply?

### ISSUE THREAD

**Issue by fmuellner** [flatpak/xdg-desktop-portal#485]
This is currently under discussion for the `org.freedesktop.Notifications` spec:

https://gitlab.freedesktop.org/xdg/xdg-specs/-/merge_requests/24

I'm sympathetic to the idea, but want to discuss this in the portal context first to not create an incentive for apps to use the underlying freedesktop API over the portal.

In my opinion the worst bit in the proposal is piggybacking the reply on the action, which luckily wouldn't be a problem with the portal API where actions have proper parameters.

So does this look like a worthwhile addition?

**Comment by TingPing** [comment]
Worth mentioning that `xdg-desktop-portal-gtk` uses the `org.gtk.Notifications` interface so it must support this also.

**Comment by fmuellner** [comment]
But `org.gtk.Notifications` is a private protocol that is undocumented as far as I can tell, and the proposal doesn't require any changes to the D-Bus API. We only need to agree on a new possible `a{sv}` entry, and the easiest option is to just use whatever the portal ends up with.

**Comment by matthiasclasen** [comment]
I think allowing responses is fine. 

I admit that the talk of serialization and deserialization in that proposal makes me anticipate the interoperability and robustness issues we're going to see...

**Comment by ZanderBrown** [comment]
Ideally like org.freedesktop.portal.Notification and org.freedesktop.Application we'd have parameter support in org.freedesktop.Notifications, but we don't

**Comment by kbroulik** [comment]
Any progress here?

**Comment by Mikenux** [comment]
There is now a proposal to talk about it: https://github.com/flatpak/xdg-desktop-portal/issues/983
