### ISSUE TITLE
fd leak prevents removable media from being ejected

### ISSUE THREAD

**Issue by ptomato** [flatpak/xdg-desktop-portal#487]
I opened a file residing on removable media, through the portal, in the org.mozilla.Thunderbird app. Even after closing the app I couldn't eject the drive because it was "busy".

relevant entry from `lsof` (repeated many times):
```
xdg-docum  7925 14911 pool-/usr  ptomato   17u      REG                8,2 (file size redacted)       2282 /run/media/ptomato/(filename redacted)
```
Process 7925 is:
```
   7925 ?        Ssl    0:23 /usr/libexec/xdg-document-portal
```

**Comment by sophie-h** [comment]
Very similar to #509. It seems like somehow nobody cared about closing fds returned by `g_unix_fd_list_append()`

**Comment by matthiasclasen** [comment]
I will take a look at this soon

**Comment by hadess** [comment]
https://github.com/flatpak/xdg-desktop-portal/pull/530 might be the fix (on top of the other fixes in https://github.com/flatpak/xdg-desktop-portal/pull/515).

**Comment by orowith2os** [comment]
@ptomato can you reproduce this now?

**Comment by ptomato** [comment]
I don't know if I recreated the exact circumstances, but this does not seem to be a problem any longer in xdg-desktop-portal 1.16.0.

**Comment by GeorgesStavracas** [comment]
Thanks. Let's assume it was fixed then, but if you spot it again, please reopen

**Comment by hfiguiere** [comment]
I thought this was #689 

Looks a lot like it.
