### ISSUE TITLE
nuvolactl unknown report for all actions

### ISSUE THREAD

**Issue by ivanchgeek** [flatpak/xdg-desktop-portal#494]
i want to play/pause tracks in yandex music apps from command line, but if i use nuvolactl pausem it reports, that pause is unknown command. --help, track-info, api-master /nuvola/core/list_apps and other works well

**Comment by TingPing** [comment]
Why is this reported here?

**Comment by ivanchgeek** [comment]
> Why is this reported here?

because i found some issues about nivola player in this repo

**Comment by ivanchgeek** [comment]
Sorry, the problem was in bad syntax, i should use novolactl action pause, not nuvolactl pause
