### ISSUE TITLE
Make portals into their own modules

### ISSUE THREAD

**Issue by SoniEx2** [flatpak/xdg-desktop-portal#497]
So that you can only install what you need. This can be useful to e.g. encourage developers to use the file chooser portal in non-flatpak applications, simply so they can use the native file chooser. Additionally this'd also mean something like zenity should provide the file chooser portal, which it currently doesn't. Nevertheless I hate flatpak and I just want native UI integration without needing all the bloat of flatpak to get it done. (this should've been done ages ago, and not through flatpak. if you want flatpak, go use genode, not linux.)

**Comment by TingPing** [comment]
The portal is already just a DBus interface anything can implement if it wants and `xdg-desktop-portal` has few non-optional dependencies. I think splitting this into small pieces is neither helpful or productive.

Also ranting about hating a project isn't a healthy way to discuss an idea.
