### ISSUE TITLE
Add a geolocation portal

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/xdg-desktop-portal#50]
GNOME shell already has the right dialog, and we use the permission store for it. But I think we should have a portal api in line with all the other portals for it. Can of course reuse all the existing infrastructure.

**Comment by matthiasclasen** [comment]
Zeeshan pointed at  https://www.freedesktop.org/software/geoclue/docs/libgeoclue/GClueSimple.html as a minimal example for api.

**Comment by hadess** [comment]
Isn't this a good case for the GClueSimple library API to figure out it's inside the sandbox and do the right thing?

**Comment by matthiasclasen** [comment]
If anybody is using GClueSimple, that would be a nice thing to do

**Comment by matthiasclasen** [comment]
I've put my work on this on branch for now: https://github.com/matthiasclasen/xdg-desktop-portal/tree/geolocation

Not quite happy with some aspects of it:
 - currently geoclue enforces one client per dbus connection, which means I can't give different apps different accuracy levels
- gcluesimple seems to have bugs in its client handling which means as soon as I drop and recreate a GClueSimple object, I don't get location-updated signals as expected
- now that I'm showing the access dialog directly instead of letting geoclue talk to the shell, I need to figure out how to make the shell show its 'location in use' icon

**Comment by matthiasclasen** [comment]
Note that I changed the Location api from properties to a signal carrying all the information, since the properties are harder to make properly per-app (we don't want other sandboxed apps to catch PropertyChanged signals, etc...

**Comment by matthiasclasen** [comment]
For comparison, here is the web api

https://developer.mozilla.org/en-US/docs/Web/API/Geolocation

**Comment by hadess** [comment]
I'll looked into this again, and wanted to explain why I don't think a portal is necessary for geolocation.

- It duplicates an API that was already thought out with multiple individual clients that shouldn't talk to each other. There could surely be bugs, but I think that the architecture is correct.
- It's pretty easy to see applications needing more than what GClueSimple (or the portal version) offers, including permissions to update in the background, or wake up the application when crossing a certain threshold. The D-Bus API was already modelled after the iOS GeoLocation API, so there's really not any features to trim there, we'd need them all, plus a bunch that haven't been implemented yet. GClueSimple is nice for a one-shot location, but nothing advanced would want to use it.
- There's only one implementation of GeoClue. Here we wouldn't be swapping out implementations in the backend, and we don't really need a layer of API to make it swappable.
- We want to also use the same permission store for sandboxed and unsandboxed, for applications that haven't yet migrated, but especially for system components.
- Holes punched in the sandbox make it easy to know which apps might use the location services.

There's also a number of reasons we could want to use this layer of portal:
- We don't want to punch any holes other than one for `org.freedesktop.portal` by default, and would consider application sandboxing incomplete until we do.
- There's unfixable bugs in Geoclue's architecture that we need to work around with a trusted middle-man
- We want to simplify the gnome-shell code and use a single "agent" API there.

Obviously, for any of those latter ones, "citation needed".

**Comment by hadess** [comment]
CC: @zeenix

**Comment by zeenix** [comment]
I agree with @hadess last comments. GClueSimple is only for making it easy to interface with Geoclue, not replace the D-Bus interface completely.

**Comment by matthiasclasen** [comment]
Well, I don't.

**Comment by zeenix** [comment]
@matthiasclasen I'm confused, did you editted my comment by mistake?

**Comment by zeenix** [comment]
Actually, having read the comment again, I don't agree with this point either:

> We want to also use the same permission store for sandboxed and unsandboxed, for applications that haven't yet migrated, but especially for system components.

https://bugs.freedesktop.org/show_bug.cgi?id=97776#c3

**Comment by hadess** [comment]
> I don't know who the 'we' in "We want to use the same permission store for sandboxed and unsandboxed" is, but it does not include me. We should not use anything to store permissions for unsandboxed apps, since we can't control what they use, so we shouldn't pretend that we can.

Should we remove the filtering of notifications for unsandboxed apps? Because you can't control them either.

How would you differentiate, and expose in the configuration, well-behaved, non-sandboxed system parts in a way that allows a more robust blocking than each app having their own toggle or setting?

**Comment by zeenix** [comment]
> Should we remove the filtering of notifications for unsandboxed apps? Because you can't control them either.

Maybe not a bad idea.

**Comment by hadess** [comment]
> Maybe not a bad idea.

No, it's a bad idea made to show how not doing any filtering of system apps, whether for location or notification, doesn't actually solve use cases.

**Comment by zeenix** [comment]
> No, it's a bad idea made to show how not doing any filtering of system apps, whether for location or notification, doesn't actually solve use cases.

Pretending that we can handle "I don't want this app to access my location", is even worse IMO.

**Comment by matthiasclasen** [comment]
https://github.com/matthiasclasen/xdg-desktop-portal/tree/location is a current version of my portal branch. It can mostly coexist with the existing geoclue code, as I get the ability to create multiple clients from the same connection.

**Comment by matthiasclasen** [comment]
https://github.com/flatpak/xdg-desktop-portal/pull/242
