### ISSUE TITLE
Can't print from Evolution (CUPS)

### ISSUE THREAD

**Issue by Johnnii360** [flatpak/xdg-desktop-portal#504]
Hi Guy's,

I'm not able to print from Evolution via CUPS (LAN-Printer). I got only the option to save or print via LPR. How can I fix this?

Ah btw. it's Ubutnu 18.04 LTS, Flatpak 1.7.3, CUPS 2.2.7.

**Comment by GeorgesStavracas** [comment]
This is a tool old version of Flatpak, and Ubuntu. Please reopen if you can still reproduce this with xdg-desktop-portal 1.18, and Flatpak 1.15
