### ISSUE TITLE
consider backend priorities

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/xdg-desktop-portal#51]
I just added an AccessDialog interface, and xdg-desktop-portal-gtk provides a gtk-based implementation. We can make it talk to gnome-shell (once it provides a similar interface) to use system-modals instead. Or we could just make gnome-shell provide this portal backend itself; but then we need priorities to make the gtk implementation the fallback that only gets used if gnome-shell is not around.

**Comment by matthiasclasen** [comment]
I'm now loading .portal files in alphabetic order, and make the first one win.

**Comment by alexlarsson** [comment]
gnome-shell implementing portals? Be very very careful then, because sandboxed apps will be able to talk to *any* objpath/iface in that client.

**Comment by matthiasclasen** [comment]
gnome-shell is implementing a portal _backend_, not a portal itself. That would be dangerous indeed.
