### ISSUE TITLE
Executable bits are not retained with FileChooser portal

### ISSUE THREAD

**Issue by merlijn-sebrechts** [flatpak/xdg-desktop-portal#517]
When I select an executable script using the FileChooser portal, the file I get access to does not have the same executable bits as the original file.

This is the file I get from the portal:

```shell
$ ls -al /run/user/1000/doc/fc52dd3/test-script.sh
-rw-rw-r-- 1 merlijn merlijn 32 Jul 27 21:00 /run/user/1000/doc/fc52dd3/test-script.sh
```

This is the original file:

```shell
$ ls -al test-script.sh 
-rwxrw-r-- 1 merlijn merlijn 32 Jul 27 21:00 test-script.sh
```

I'm running Ubuntu 20.04 using xdg-desktop-portal 1.6.0-1 on Gnome. The application is running inside of a snap.

[Original discussion on the snapcraft forum](https://forum.snapcraft.io/t/kde-neon-sets-home-to-run-user-1000/19103/10?u=galgalesh).

**Comment by matthiasclasen** [comment]
From irc: 

```
mclasen: alexlarsson: is there any reason we don't preserve permissions in the document portal ?
alexlarsson: I thought we did, at least for the user. so, sounds like a bug
```

**Comment by hfiguiere** [comment]
```
% flatpak document-export --app org.gnome.TextEditor.Devel ./test.sh 
/run/user/1000/doc/52d9c540/test.sh
% ls -l /run/user/1000/doc/52d9c540/test.sh
-rwxr-xr-x. 1 hub hub 28 Nov  9 21:34 /run/user/1000/doc/52d9c540/test.sh
```

Changing the permission is also reflected.

**Comment by hfiguiere** [comment]
Same when I open using the document portal.

Digging further, commit ecc0af3b1f4ade0f89f67ed8291c96bf703c3c1b seems to be the overhaul that added chmod, and that's post 1.6.0....


Closing as already fixed.
