### ISSUE TITLE
Slack won't find user-installed web browser

### ISSUE THREAD

**Issue by DamienCassou** [flatpak/xdg-desktop-portal#531]
Hi,

Slack opens links in the system-installed Chromium (installed with `dnf`) instead of the user-installed Firefox (installed with Nix).
On the contrary, `xdg-open https://www.gnu.org` correctly opens Firefox. As you can see below, firefox.desktop is reachable from XDG_DATA_DIRS.

I would like links to open in Firefox instead of Chromium.  If I remove Chromium, clicking on a link will show:

![2020-09-27-152355](https://user-images.githubusercontent.com/217543/94366010-8091b980-00d5-11eb-9952-4322cf8162e2.png)

```
$ strings /proc/$(pidof xdg-desktop-portal-gtk)/environ | grep XDG
XDG_RUNTIME_DIR=/run/user/1000
XDG_DATA_DIRS=/home/cassou/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/nix/var/nix/profiles/default/share:/home/cassou/.nix-profile/share:/usr/share:/usr/local/share
XDG_SESSION_ID=5

$ strings /proc/$(pidof xdg-desktop-portal)/environ | grep XDG
XDG_RUNTIME_DIR=/run/user/1000
XDG_DATA_DIRS=/home/cassou/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/nix/var/nix/profiles/default/share:/home/cassou/.nix-profile/share:/usr/share:/usr/local/share
XDG_SESSION_ID=2

$ cat /home/cassou/.nix-profile/share/applications/firefox.desktop 
[Desktop Entry]
Type=Application
Exec=firefox %U
Terminal=false
Name=Firefox
Icon=firefox
Comment=
GenericName=Web Browser
MimeType=text/html;text/xml;application/xhtml+xml;application/vnd.mozilla.xul+xml;x-scheme-handler/http;x-scheme-handler/https;x-scheme-handler/ftp
Categories=Network;WebBrowser;

$ flatpak run --log-session-bus com.slack.Slack
...
C17: -> org.freedesktop.portal.Desktop call org.freedesktop.portal.OpenURI.OpenURI at /org/freedesktop/portal/desktop
B397: <- :1.33 return from C17
B-1: <- org.freedesktop.DBus signal org.freedesktop.DBus.NameOwnerChanged at /org/freedesktop/DBus
```

System:
- Fedora 32 
- Flatpak is installed with `dnf`

**Comment by hadess** [comment]
What's the output of `gio mime x-scheme-handler/https` ?

**Comment by DamienCassou** [comment]
@hadess:

```session
$ gio mime x-scheme-handler/https
Default application for “x-scheme-handler/https”: firefox.desktop
Registered applications:
        firefox.desktop
Recommended applications:
        firefox.desktop
```

**Comment by hadess** [comment]
Are you using `xdg-desktop-portal-1.8.0-1.fc32` ?

**Comment by hadess** [comment]
And don't forget to restart your system after that.

**Comment by DamienCassou** [comment]
@hadess I just updated my system, got version 1.8.0-1.fc32 and rebooted. The problem persists.

**Comment by hadess** [comment]
> @hadess I just updated my system, got version 1.8.0-1.fc32 and rebooted. The problem persists.

Can you also check the `PATH` is set appropriately for xdg-desktop-portal to find the `firefox` binary?

Can you reproduce the problem after running `/usr/libexec/xdg-desktop-portal -r -v`?

If you can, then the debug output would be useful, otherwise, it's a setup problem with nix, which expects xdg-desktop-portal to be launched in an environment which isn't applied to auto-start D-Bus services.

**Comment by DamienCassou** [comment]
> Can you also check the PATH is set appropriately for xdg-desktop-portal to find the firefox binary?

Apparently, the PATH variable *isn't* correctly set in systemd services:

```
$ systemctl --user show-environment | grep PATH
PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin
```

> Can you reproduce the problem after running /usr/libexec/xdg-desktop-portal -r -v?

No. Running `xdg-desktop-portal` manually solves the problem.

What would be the recommended way to add directories to the PATH of the `xdg-desktop-portal`?

**Comment by hadess** [comment]
> What would be the recommended way to add directories to the PATH of the `xdg-desktop-portal`?

I don't know I'm afraid, but we now know that xdg-desktop-portal isn't buggy, and that Nix doesn't setup its environment correctly for D-Bus activated services.

**Comment by DamienCassou** [comment]
You are right, xdg-desktop-portal isn't to blame so the issue should indeed be closed.

But it's also not Nix fault in my opinion because Nix is not responsible for creating the `xdg-desktop-portal` service, this one comes from Fedora. The problem lies in between :-).

**Comment by hadess** [comment]
It's Nix's problem if it relies on environment variables and for every app started by the user to be descendants of the shell in which it modified the environment variables. Look for `systemctl --user import-environment`.
