### ISSUE TITLE
strange appearance under wayland

### ISSUE THREAD

**Issue by rhjdvsgsgks** [flatpak/xdg-desktop-portal#533]
i'm using kde under wayland, if i enable portal for a gtk program with wayland support, appearance will become very strange like this 
![under wayland](https://user-images.githubusercontent.com/26178113/95302548-9f304700-0871-11eb-8414-6c97b16ac9fd.png)
but under xorg there is no such problem
![under xorg](https://user-images.githubusercontent.com/26178113/95302757-e585a600-0871-11eb-8a36-6bc5cb39dc86.png)

**Comment by matthiasclasen** [comment]
Sorry, I can't really make out what is going on in these screenshots. You'll have to describe in more detail what you think is strange

**Comment by rhjdvsgsgks** [comment]
the picture showed that what will a file picker be like under wayland and xorg, my desktop environment is kde, and program which i ran is a gtk based program. if everything works, behaviour of them(under wayland or xorg) should be same, but at least right now they're not. under xorg, gtk program will use kde appearance and file picker, that's ok. under wayland, gtk program will use gtk(or wayland?) default appearance and gtk file picker, so that's why i think it's strange.

**Comment by GeorgesStavracas** [comment]
This should be fixed the the new config file mechanism in 1.18. Please reopen if still reproducible after updating to that.
