### ISSUE TITLE
missing org.freedesktop.portal.Request Interface in the portal introspection

### ISSUE THREAD

**Issue by Fak3** [flatpak/xdg-desktop-portal#539]
xdg-desktop-portal version: 1.6.0-5.2.x86_64

When I execute introspection request of the `org.freedesktop.portal.Desktop`, it is misssing [org.freedesktop.portal.Request](https://flatpak.github.io/xdg-desktop-portal/portal-docs.html#gdbus-org.freedesktop.portal.Request) Interface:

```bash
$ dbus-send --session  --dest=org.freedesktop.portal.Desktop  --type=method_call  --print-reply /org/freedesktop/portal/desktop   org.freedesktop.DBus.Introspectable.Introspect | grep Request
 
   <method name="RequestBackground">
```

full output of the call: https://gist.github.com/Fak3/0f2c262d09d00bbdd348d7cd6635a3fa

**Comment by matthiasclasen** [comment]
I think that is because org.freedesktop.portal.Request is not an interface that implemented by that object path

**Comment by TornaxO7** [comment]
Hi! I'm encountering this issues as well. According to this page, `org.freedesktop.portal.Desktop` [should have `org.freedesktop.portal.Request`](https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.portal.Request.html)
