### ISSUE TITLE
Mouse from wrong screen

### ISSUE THREAD

**Issue by darkdragon-001** [flatpak/xdg-desktop-portal#540]
I have two screens connected. When I select one screen to share, it works, but the mouse pointer is only moving when my mouse is located on the _other_ screen.

I am on Fedora 33 using Wayland.

Tested on https://www.webrtc-experiment.com/Pluginfree-Screen-Sharing/ .

**Comment by TheJackiMonster** [comment]
I can also confirm this. I think it only needs to relocate the shared mouse pointer relative to the shared screen instead of using absolute positions.

I am on Archlinux, also using Wayland.

**Comment by hadess** [comment]
This is implemented in the various compositors, such as gnome-shell, not in xdg-desktop-portal, so closing.
