### ISSUE TITLE
Portal documentation at docs.flatpak.org is pretty outdated

### ISSUE THREAD

**Issue by ntninja** [flatpak/xdg-desktop-portal#541]
The documentation of available portal APIs at https://docs.flatpak.org/en/latest/portal-api-reference.html is pretty outdated. I had checked there if it is finally possible to open directories (instead of just files) and thought that there still wasn't any such support. Only by accident did I later stumble upon https://github.com/flatpak/xdg-desktop-portal/commit/c616b491fe0ac67f78a14bcaf0d3a150bfadfd82 and related things.

Maybe this can be updated?

**Comment by dreua** [comment]
I couldn't find anything on drag and drop / copy and paste. Having better documentation, maybe even links to example code, would go a long way in promoting portals. At the moment it feels like sticking with `--filesytem=host/home` is the only option in many cases.

**Comment by hfiguiere** [comment]
It was recently overhauled and updated: https://flatpak.github.io/xdg-desktop-portal/docs/

**Comment by ntninja** [comment]
@hfiguiere: Thank you! This resolved the reported issue: https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.portal.FileChooser.html
