### ISSUE TITLE
Screen sharing dialog should provide screen / window preview 

### ISSUE THREAD

**Issue by stransky** [flatpak/xdg-desktop-portal#544]
Web browsers tend to provide preview of a resource which is going to be shared to confirm the actual resource.
If the shared resource (screen/window) is selected by portal dialog, it makes more sense to generate the preview were the resource is actually selected.

**Comment by jadahl** [comment]
Indeed, but it's up to the component implementing the UI. E.g. for gnome, that's xdg-desktop-portal-gtk.

**Comment by stransky** [comment]
Okay, filed as https://github.com/flatpak/xdg-desktop-portal-gtk/issues/333
Thanks.
