### ISSUE TITLE
OpenURI.OpenFile() fails when used with document portal paths

### ISSUE THREAD

**Issue by jhenstridge** [flatpak/xdg-desktop-portal#545]
We received a bug report with the Thunderbird snap related to launching files via xdg-desktop-portal.  The steps the user took were:

1. add an attachment to an email (picked via a `GtkFileChooserNative` dialog)
2. try to launch the attachment from the compose window (handled [via `gtk_show_uri`](https://dxr.mozilla.org/mozilla-central/source/toolkit/system/gnome/nsGIOService.cpp#120), which in turn calls `g_app_info_launch_default`).

I was able to reproduce this with a simplified test program:

https://gist.github.com/jhenstridge/34a1813b69df7a486e509db71675f09b

When run within snap confinement, I can reproduce the error.  Based on what I found, I'd assume the same would be true for Flatpak confinement.

The file name returned by the chooser will be something like `$XDG_RUNTIME_DIR/doc/$docid/$filename`.  The test application then opens this path to create a file descriptor to pass in the `OpenFile` D-Bus call.  Due to the document portal bind mount, the file opened is equivalent to `$XDG_RUNTIME_DIR/doc/by-app/$appid/$docid/$filename` outside of the sandbox.

When x-d-p receives the file descriptor, it uses `xdp_app_info_get_path_for_fd` to map it back to a host system file name.  This determines the path the confined app opened via `/proc`, then checks to see whether the file descriptor refers to the same file in the host file system by comparing stat information.

The problem arises because the `.../doc/$docid/$filename` and `.../doc/by-app/$appid/$docid/$filename` files provided by the document portal file system have different inode numbers, leading to the OpenFile request being rejected.

There are two possible solutions to this:

1. Have `xdp_app_info_get_path_for_fd` special case document portal paths some how.
2. Have `xdg-document-portal` use the same inode numbers for files exported through the by-app hierarchy.

**Comment by alexlarsson** [comment]
Ugh, this is fallout from when we changed xdg-document-portal to support directories. They *used* to have the same inode, but that is not really realistic anymore.

I guess we need some special casing...

**Comment by alexlarsson** [comment]
@jhenstridge I'm quite busy with some other stuff, any chance you could take a look at this?

**Comment by jhenstridge** [comment]
I'll see if I can have a go.  I had a quick look when I initially filed this and realised the fuse code was a lot more complicated than before.

From what I can see, sharing inodes should be safe for leaf files, but a security hole if done for directories (since the confined app could potentially escape their subtree, depending on what the kernel thinks ".." is.

I'll see how difficult it is to fix it for the normal file case.

**Comment by alexlarsson** [comment]
@jhenstridge Sharing inodes is maybe not illegal, but given how the portal works it is hard.

**Comment by alexlarsson** [comment]
I think maybe just detecting the document portal mount dev-ino and doing a quick check on the specific two possible paths (by app id and toplevel) is good enough.

**Comment by jhenstridge** [comment]
Okay, so you're suggesting to deal with it on the xdg-desktop-portal side?  I'll see what I can do.

**Comment by alexlarsson** [comment]
@jhenstridge yeah

**Comment by mcatanzaro** [comment]
[More fallout here.](https://gitlab.gnome.org/GNOME/epiphany/-/issues/1427) Seems the 1.6 branch is OK, because directory support was new in 1.8, and so 1.8.0 is the only broken release. Could we get a 1.8.1 release with this commit included, please?
