### ISSUE TITLE
Problems to select a folder in com.eclipse.Java

### ISSUE THREAD

**Issue by christianbueno1** [flatpak/xdg-desktop-portal#546]
**System**
```
neofetch
             `..---+/---..`                joe@joe-pc 
         `---.``   ``   `.---.`            ---------- 
      .--.`        ``        `-:-.         OS: KDE neon User Edition 5.20 x86_64 
    `:/:     `.----//----.`     :/-        Kernel: 5.4.0-53-generic 
   .:.    `---`          `--.`    .:`      Uptime: 43 mins 
  .:`   `--`                .:-    `:.     Packages: 1676 (dpkg), 11 (flatpak) 
 `/    `:.      `.-::-.`      -:`   `/`    Shell: zsh 5.8 
 /.    /.     `:++++++++:`     .:    .:    Resolution: 1920x1080 
`/    .:     `+++++++++++/      /`   `+`   DE: Plasma 
/+`   --     .++++++++++++`     :.   .+:   WM: KWin 
`/    .:     `+++++++++++/      /`   `+`   Theme: Breeze [Plasma], Breeze [GTK2/3] 
 /`    /.     `:++++++++:`     .:    .:    Icons: breeze [Plasma], breeze [GTK2/3] 
 ./    `:.      `.:::-.`      -:`   `/`    Terminal: konsole 
  .:`   `--`                .:-    `:.     CPU: Intel i5-4430 (4) @ 3.200GHz 
   .:.    `---`          `--.`    .:`      GPU: NVIDIA GeForce GT 610 
    `:/:     `.----//----.`     :/-        Memory: 3312MiB / 15805MiB 
      .-:.`        ``        `-:-.
         `---.``   ``   `.---.`                                    
             `..---+/---..`                                        
```
tested with
Click behavior: Single-click to open files and folders
Click behavior: Double-click to open files and folders

---
Trying to import a project to eclipse-ide

**Steps to reproduce this issue**
`File> Open Project from File System...>`
In `Import Source` select `Directory` button
Search your folder, click in your folder (you will be inside the folder) and click in `Open` button
Then impossible to select that folder, [link to a  gif 1](https://imgur.com/da0WqXq)

One way to do select is go back to the father folder and write the folder in the Name input.
[link to a gif 2](https://imgur.com/EYnczs6)

**Comment by hadess** [comment]
That looks like a dialogue provided by Eclipse, not the one provided by the xdg-desktop-portal (whether it's the Qt or the GTK choosers). What makes you believe that this is a problem with xdg-desktop-portal?

**Comment by Mikenux** [comment]
On Fedora Workstation 38, Eclipse seems to use xdg-desktop-portal because I can select a folder when I remove `filesystem=host` with Flatseal. The sandbox path appears.

Looking at the gifs and given the description, it might be a bug with the KDE file chooser (maybe since fixed?) as no selection takes place (so no name is put in the "Name" field) because a single click navigates through the folders.

**Comment by GeorgesStavracas** [comment]
Mikenux is probably right, this looks *a lot* like a bug in the KDE filechooser itself, not on the portal. Please report this issue to KDE developers.
