### ISSUE TITLE
xdg-desktop-portal... portal for Flatpak and Snap v 1.7.2-flatpak1~bionic won't update on elementary

### ISSUE THREAD

**Issue by brandoncote** [flatpak/xdg-desktop-portal#547]
In the Elementary OS appcentre, no matter how many times I click Update, this keeps reappearing:
 • xdg-desktop-portal desktop integration portal for Flatpak and Snap Version: 1.7.2-flatpak1~bionic

I've tried sudo apt update and sudo apt upgrade and restarted the computer several times. It just won't update / it won't disappear. Why is this?
![image](https://user-images.githubusercontent.com/15098728/99916461-478e5380-2cd8-11eb-85ce-587349f4cbc4.png)

**Comment by vrolijken** [comment]
I tried changing the mirrors in /etc/apt/sources.list to no avail

**Comment by GammaGames** [comment]
The version of this package on eOS might be managed by them:

```
jlieberg@jl-eos:~$ sudo apt-get install --print-uris xdg-desktop-portal
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be DOWNGRADED:
  xdg-desktop-portal
0 upgraded, 0 newly installed, 1 downgraded, 0 to remove and 0 not upgraded.
Need to get 247 kB of archives.
After this operation, 0 B of additional disk space will be used.
'http://ppa.launchpad.net/elementary-os/os-patches/ubuntu/pool/main/x/xdg-desktop-portal/xdg-desktop-portal_1.7.2-flatpak1~bionic_amd64.deb' xdg-desktop-portal_1.7.2-flatpak1~bionic_amd64.deb 247456 MD5Sum:ee86d32eee74f8ab641d10a0fc698476
```

**Comment by hadess** [comment]
You'll want to tell your distribution about the problem. The upstream `xdg-desktop-portal` project isn't the one shipping those packages.

**Comment by GammaGames** [comment]
To anyone with the issue, remove the `alexlarsson/flatpak` ppa. Elementary has their own ppa that was introduced in 5.1. The issue I mentioned this thread in has a little more info.
