### ISSUE TITLE
Media tracks are imported to Celluloid in reversed order 

### ISSUE THREAD

**Issue by fabriciojardim** [flatpak/xdg-desktop-portal#548]
When you open multiple file tracks with Celluloid they are imported in reversed order as sorted by the file chooser interface.
I'm not sure if this is really a xdg-desktop-portal issue but celluloid maintainers seems to think so. 
More details on celluloid-player/celluloid#315. 

**Steps to Reproduce:**
1. Open Celluloid
2. Import multiple audio tracks sorted by some order.
3. See them imported in reversed order

**Actual Results:**
Reversed order

**Expected Results:**
Sorted order

**System**
Fedora 33 
Flatpak 1.8.3
Celluloid 0.20

**Comment by hadess** [comment]
I don't see where in the API documentation it says that any particular order is respected, however inconvenient the problem ends up being. If Celluloid relies on an undocumented behaviour, then we'd best document it so we can be sure to avoid problems like this in the future.

**Comment by hadess** [comment]
I couldn't find any place in xdg-desktop-portal where this behaviour could have been implemented. Maybe this GTK patch would help? You'll need to build your own GTK inside the Flatpak to test it, to replace the runtime one.

```patch
diff --git a/gtk/gtkfilechoosernativeportal.c b/gtk/gtkfilechoosernativeportal.c
index a401ec970b..0b3c6b6d17 100644
--- a/gtk/gtkfilechoosernativeportal.c
+++ b/gtk/gtkfilechoosernativeportal.c
@@ -157,6 +157,7 @@ response_cb (GDBusConnection  *connection,
   self->custom_files = NULL;
   for (i = 0; uris[i]; i++)
     self->custom_files = g_slist_prepend (self->custom_files, g_file_new_for_uri (uris[i]));
+  self->custom_files  = g_slist_reverse (self->custom_files);
 
   switch (portal_response)
     {
```

**Comment by GeorgesStavracas** [comment]
Proposed this as a patch here: https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/6482

**Comment by GeorgesStavracas** [comment]
Closing as there's nothing really to do on XDG desktop portal side (AFAIU)
