### ISSUE TITLE
The (loud)speakers stays mute within flatpak app com.microsoft.Teams

### ISSUE THREAD

**Issue by bitstreamout** [flatpak/xdg-desktop-portal#562]
Don't know what the problem is as I can access all type of speakers, that is switch to builtin audio, headphone if plugged in, and also to raop sinks.  Also if the app is started I can change into the namespace/sandbox with ``flatpak enter <ID>`` and play therein with ``paplay`` a test wav placed into my ``~/Downloads/`` directory.  Within teams the microphone is working, the test call seems to work, the devices are accessible from personal settings including all sinks and sources, but entering a chat always results in the fakt the the choosen output device aka speaker is muted and stays muted even if clicked on the speaker symbol ... also trying to increase the speaker volume results into immediate switching back to zero.  The notebook (N15_17RD,RD2 also know from Tuxedo) here has hardware keys which can also control the volumen and mute/unmute state of the speaker but this also has no influence on the teams flatpak app.

The app org.pulseaudio.pavucontrol also works out of the box as well as the local pavucontrol  and paprefs

**Comment by hadess** [comment]
This doesn't use portals at all, it's likely a problem with either the Flatpak, the original software, or with your distribution. File a bug against the Flatpak in Flathub to start with.
