### ISSUE TITLE
Select the file when opening file manager with OpenDirectory

### ISSUE THREAD

**Issue by ilya-fedin** [flatpak/xdg-desktop-portal#564]
OpenDirectory method of the OpenURI portal accepts a fd of a file, so it theoretically can use https://www.freedesktop.org/wiki/Specifications/file-manager-interface/ to open a directory with file selected. There are sadly no analogue of the FileManager service for sandboxed apps and this makes "show file in folder" feature of applications less convenient :(

**Comment by YaLTeR** [comment]
There is, actually, if I understand correctly what you mean: https://flatpak.github.io/xdg-desktop-portal/portal-docs.html#gdbus-method-org-freedesktop-portal-OpenURI.OpenDirectory but it currently doesn't work properly, fix is in https://github.com/flatpak/xdg-desktop-portal/pull/552.

**Comment by ilya-fedin** [comment]
My post starts with mentioning the OpenDirectory method...

**Comment by YaLTeR** [comment]
> My post starts with mention of the OpenDirectory method...

Oh, sorry, looks like I jumped straight to the URL and somehow ignored the mention before... Anyway my reply is still valid I think?

**Comment by ilya-fedin** [comment]
Your PR fixes path to the file, while this issue is about the fact that file is not selected when file manager is opened. It's really hard to find needed file if file manager opens in e.g. download directory with a lot of files.

**Comment by YaLTeR** [comment]
Ah, I see what you mean. I think for portal's `OpenDirectory` it indeed makes sense to highlight the file.

**Comment by ilya-fedin** [comment]
Wow, when will it get into release?
