### ISSUE TITLE
[PermissionStore] consider GetPermission inclusion?

### ISSUE THREAD

**Issue by tchx84** [flatpak/xdg-desktop-portal#583]
We currently have `SetPermission` and `DeletePermission` which operate with specific apps, but we don't have a `GetPermission` that does the same. Instead, we rely on `LookUp` which brings all `(table, id, app)` tuples.

From what I have seen, in GNOME Control Center, and what I needed to do for Flatseal, we call `LookUp`, check if the app is present among all tuples, to then access the permission data (e.g., ["yes"], etc).

As more UI tools ala-flatseal appear, I believe a `GetPermission` would make more sense for such tools as these operate per-app basis. Another reason is that the permission store data tends to grow, which means that `LookUp` will keep bringing more and more unnecessary data for the case I am describing here (but I haven't really measure the impact of this).

Turning this question around, Is there a specific reason why there ins't `GetPermssion`?

**Comment by matthiasclasen** [comment]
> Turning this question around, Is there a specific reason why there ins't GetPermssion?

No specific reason that I can think of.

**Comment by tchx84** [comment]
Working on it :+1:
