### ISSUE TITLE
feature request: option to trigger custom scripts e.g. when screensharing starts/ends

### ISSUE THREAD

**Issue by jokeyrhyme** [flatpak/xdg-desktop-portal#584]
Howdie, thanks so much for sharing this work

xdp-wlr has a settings file that allows a user to configure custom scripts to run when screensharing starts and ends: https://github.com/emersion/xdg-desktop-portal-wlr/blob/master/xdg-desktop-portal-wlr.5.scd

I find this very useful for being able to disable/enable notifications, automate changes to window layouts, etc when presenting to others

It would be terrific if, more generally, xdg-desktop-portal offered a way to configure scripts that could be triggered at the beginning and end of each type of portal request

I suppose a workaround/alternative could be to monitor dbus directly for portal requests

**Comment by matthiasclasen** [comment]
Unlikely to happen. The portal apis are not meant as extension points for user scripting, but as apis that provide well-defined functionality.
