### ISSUE TITLE
Allow direct print with supplied print settings

### ISSUE THREAD

**Issue by xhorak** [flatpak/xdg-desktop-portal#585]
Firefox has own print dialog now to set the print settings which is from the flatpak POV actually good for us since portal does not support extending print settings from the application (to set if the headers should be printed, etc). Firefox is getting printer info from the cups directly, so it's able to set the settings like duplex printing, color or B&W and others. 

Problem is that the portal does not deal with the situation where the printing UI is not needed and rather expect the use of PreparePrint to return the token later used by the Print method. 

If the token is not present the print dialog is shown, which does not make a sense for our usecase. Also the print settings from the Firefox UI is not honored.

Upstream bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1688720

**Comment by xhorak** [comment]
This is how the print dialog looks like now:
![Screenshot from 2021-05-27 13-26-32](https://user-images.githubusercontent.com/2932697/119818274-48a27680-beef-11eb-91b0-4fb41e347c0b.png)

**Comment by matthiasclasen** [comment]
> Firefox is getting printer info from the cups directly

If you are talking to cups directly, why is the print portal involved ?

**Comment by Mikenux** [comment]
Is this bug still valid? The upstream bug is closed...

**Comment by xhorak** [comment]
This is no longer valid.
