### ISSUE TITLE
Portal for getting screen coordinates based on a selection

### ISSUE THREAD

**Issue by SeaDve** [flatpak/xdg-desktop-portal#588]
Similar to gnome shell screenshot's SelectArea method

**Comment by matthiasclasen** [comment]
What would you do with such coordinates?

**Comment by SeaDve** [comment]
for screen recording etc. 

it is related to #582, but allowing individual screen selection gives more granular control

**Comment by kirbykevinson** [comment]
So what you're proposing is delivering compositor-local coordinates to the client after the user selected an arbitrary area of the screen? I fail to find a use case for such a feature, especially considering compositor-local coordinates of something would be completely useless on Wayland unless the compositor supports a protocol that allows something useful to be done with the coordinates (such as `
wlr-foreign-toplevel-management` or `
wlr-virtual-pointer-unstable`), in which case you could just use a tool specific for such compositor (such as slurp). I don't think such a specific feature belongs in a portal.

**Comment by SeaDve** [comment]
thanks for explaining, i understood, i think i should close it

**Comment by SeaDve** [comment]
btw @kirbykevinson doesn't slurp has x11 backend?
