### ISSUE TITLE
Add ActionActivated signal to Notification portal

### ISSUE THREAD

**Issue by grulja** [flatpak/xdg-desktop-portal#59]
Notification portal expects that each application implements org.freedesktop.Application interface and actions triggered from a notification will call this interface. In KDE not all applications handle response from notifications that way as we can simply just watch actionActivated(int action) signal from created notification (using KNotification framework). The way KDE notifications work we will need a signal we can send back to an application running in sandbox.

**Comment by matthiasclasen** [comment]
I've pushed some work here: https://github.com/matthiasclasen/xdg-desktop-portal/tree/notification-actions

Feedback would be appreciated, in particular: does this look implementable for qt inside the sandbox ?

**Comment by matthiasclasen** [comment]
The gtk backend implementation is here: https://github.com/matthiasclasen/xdg-desktop-portal-gtk/tree/notification-actions

**Comment by grulja** [comment]
This look implementable, it just needs to be implemented in KDE Frameworks and not in Qt (same applies probably for other portals except the FileChooser and OpenURI).

**Comment by grulja** [comment]
Already merged and implemented on my side.
