### ISSUE TITLE
Very slow start due to timeout on org.freedesktop.impl.portal.desktop.wlr

### ISSUE THREAD

**Issue by Gochkin** [flatpak/xdg-desktop-portal#607]
I have noticed that the first application, that utilize `xdg-desktop-portal` after the boot, takes a lot of time (about 40 secs), but after that all aplications start fast. It seems that when the `xdg-desktop-portal.service` is launched by the application there is some failure related to `org.freedesktop.impl.portal.desktop.wlr`. Systemd status reports this:

```
Jul 27 19:49:20 go4a-xps systemd[1096]: Stopped Portal service.
Jul 27 19:49:20 go4a-xps systemd[1096]: Starting Portal service...
Jul 27 19:49:45 go4a-xps xdg-desktop-por[3435]: Failed to create screenshot proxy: Error calling StartServiceByName for org.freedesktop.impl.portal.desktop.wlr: Timeout was reached
Jul 27 19:49:45 go4a-xps xdg-desktop-por[3435]: No skeleton to export
Jul 27 19:50:10 go4a-xps xdg-desktop-por[3435]: Failed to create screen cast proxy: Error calling StartServiceByName for org.freedesktop.impl.portal.desktop.wlr: Timeout was reached
Jul 27 19:50:10 go4a-xps xdg-desktop-por[3435]: No skeleton to export
Jul 27 19:50:10 go4a-xps systemd[1096]: Started Portal service.
```
If the issue is not with `xdg-desktop-portal`, please direct me to where to search for a solution or to report the issue.

**Comment by Gochkin** [comment]
Nevermind, the issue was with xdg-desktop-portal-wlr.service failing to start due to misconfiguration, resulted in some sway related env vars not being imported into systemd.

**Comment by hadess** [comment]
Yeah, sway doesn't integrate, and doesn't want to integrate properly into the session bus, resulting in problems like this:
https://github.com/swaywm/sway/issues/5777#issuecomment-719931295
