### ISSUE TITLE
Add a microphone portal

### ISSUE THREAD

**Issue by rmader** [flatpak/xdg-desktop-portal#615]
Analogous to the [camera portal](https://github.com/flatpak/xdg-desktop-portal/pull/331), it would be great if applications could ask for microphone access on demand. Optimally, it would support choosing a microphone, if multiple are available (compare https://github.com/flatpak/xdg-desktop-portal/pull/490).

---

Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1726218

**Comment by rmader** [comment]
See https://github.com/flatpak/xdg-desktop-portal/pull/659

**Comment by hfiguiere** [comment]
Related: #1129

**Comment by GeorgesStavracas** [comment]
Let's please have any discussions about it at https://github.com/flatpak/xdg-desktop-portal/discussions/1142
