### ISSUE TITLE
Documentation is out of date - still on 1.7.1

### ISSUE THREAD

**Issue by whot** [flatpak/xdg-desktop-portal#620]
Looks like the [documentation pages](https://flatpak.github.io/xdg-desktop-portal/portal-docs.html) are no longer updated. The version listed there is 1.7.1 and I only noticed this because the `Secrets` portal documentation is missing, which led me on a bit of a goose chase.

Seems like a job for the CI to build this?

**Comment by vchernin** [comment]
I think this is fixed, 1.10.0 is listed now.

**Comment by whot** [comment]
yep, thanks.
