### ISSUE TITLE
A portal for sending email

### ISSUE THREAD

**Issue by muelli** [flatpak/xdg-desktop-portal#63]
I intend to have my application send an email. As of now, we have `xdg-email` which is supposed to be handling that.  Within a flatpak app, we cannot call that on the host, though.

Currently, `xdg-email` claims to support the following arguments:

```
xdg-email [--utf8] [--cc address] [--bcc address] [--subject text] [--body text
] [--attach file] [ mailto-uri | address(es) ]
```

So I guess a compatible DBus API would support these (i.e. to, cc, bcc, subject, body, attachment), too.

FWIW: `xdg-open "mailto:foo@bar.baz?subject=foosubject&body=foobody&attach=/tmp/file"` seems to work with Evolution, but I doubt that Thunderbird gets it right.

**Comment by hadess** [comment]
The xdg utilities are junk, as far as I'm concerned.

In any case, this is likely going to be a job for the "Sharing" portal, which would allow passing files between applications. This would then be used by nautilus-sendto for example. You could also use nautilus-sendto right now, if you're out of the sandbox.

**Comment by muelli** [comment]
I'm confused. Are you saying that I could send an email using nautilus-sendto? Or rather an attachment s.t. the user still needs to fill out the recipients, subject, etc.?

And yeah, the usefulness of xdg-email is somewhat limited. AFAIU it supports Evolution and Thunderbird only. I read that gmail might also work if the desktop is configured accordingly.  I'm not a big fan myself, but it seems the best we currently have to send out email programmatically.

Properly implementing such a portal would probably be best by making the MUAs offer DBus services themselves. I'm not aware of any efforts in this direction, though.

**Comment by matthiasclasen** [comment]
So the use case here is that you have an email address, and you want to send a mail to it ?

I wonder if this fits in the sharing portal, where the normal case is that the app only has the content to share, and the portal lets the user pick a) the transport and b) the destination.

**Comment by muelli** [comment]
I have the full email, i.e. address, subject, body, and attachment,  and I need something to actually send it. So both the content and recipient have already been determined.

**Comment by matthiasclasen** [comment]
There's org.freedesktop.portal.Email.ComposeEmail now

**Comment by muelli** [comment]
cool. Any chance we can link here to the commits that made the portal? If only to make historians' jobs easier in the future ;-)

**Comment by matthiasclasen** [comment]
Historians get payed to do that work...

**Comment by hadess** [comment]
See PR #88
