### ISSUE TITLE
Trashing directories doesn't work

### ISSUE THREAD

**Issue by gasinvein** [flatpak/xdg-desktop-portal#630]
xdg-desktop-portal build as of f64fb01fd2368c89ae3d88b0841f7b415803411d spits the following error when trying to trash a directory in a flatpak sandbox via `gio trash some-folder/`:
```
XDP: Handling TrashFile
XDP: Cannot trash file with invalid fd: O_PATH fd was opened O_NOFOLLOW
```

**Comment by ebassi** [comment]
GLib uses `O_NOFOLLOW` for all fd's it passes to the portal, as the result of #412. Additionally, GLib uses `O_PATH` when passing the file descriptor of a directory.

**Comment by GeorgesStavracas** [comment]
@matthiasclasen has fixed this with commit https://github.com/GNOME/glib/commit/724df43616
