### ISSUE TITLE
Can't open file with `writable` option

### ISSUE THREAD

**Issue by liferooter** [flatpak/xdg-desktop-portal#632]
# Tested software
- **OS**: Fedora Linux 34 and GNOME OS Nightly
- **xdg-desktop-portal version**: 1.8.1

# Description
When I call `org.freedesktop.portal.OpenURI`'s method `OpenFile` with `writable` option as `true`, I get response code `2` and file isn't opened.

**Comment by mwleeds** [comment]
There's not enough information here to debug. In the future please provide all the parameters of the D-Bus call you made, how you made it (e.g. `gdbus call ...`), and if the issue is reproducible with more than one file.
