### ISSUE TITLE
Broken font rendering on KDE without GNOME/GTK portal

### ISSUE THREAD

**Issue by vchernin** [flatpak/xdg-desktop-portal#642]
Some KDE Plasma users are installing `xdg-desktop-portal-gnome` in order to fix GTK app’s font rendering on KDE Wayland. The settings portal is apparently necessary for the GTK app to receive the correct font configuration. The GNOME portal implementation is necessary because `xdg-desktop-portal-gtk` no longer builds with support for the settings portal by default.

Apparently `xdg-desktop-portal-gtk` is an acceptable thing for KDE Plasma users to install. Fedora KDE ships it out of the box, but not `xdg-desktop-portal-gnome`.

Should the settings portal (and potentially others) be re-enabled in `xdg-desktop-portal-gtk` by default? Are there any GNOME settings that need to be moved out of it still?

See: 
https://bugs.kde.org/show_bug.cgi?id=415933 
https://github.com/flatpak/xdg-desktop-portal-gtk/issues/355
Example:
https://github.com/wwmm/easyeffects/issues/1050#issuecomment-889626226

**Comment by mcatanzaro** [comment]
This is an xdg-desktop-portal-gtk bug, introduced by https://github.com/flatpak/xdg-desktop-portal-gtk/pull/350.

I'm not sure if it's possible to move GitHub issues across different projects, but it's not an xdg-desktop-portal bug and cannot be fixed here.

**Comment by mcatanzaro** [comment]
I missed that you reported https://github.com/flatpak/xdg-desktop-portal-gtk/issues/355. That issue should be reopened, and this issue should be closed. There's nothing to be done here.

**Comment by Erick555** [comment]
Apparently because x-d-p-kde didn't implement portal to read gtk settings.
