### ISSUE TITLE
Background run and autostart portals don't work for unsandboxed apps

### ISSUE THREAD

**Issue by BrainBlasted** [flatpak/xdg-desktop-portal#650]
I'd been operating under the assumption that all portals work sandboxed and unsandboxed, since most portals I've used do. So in [GNOME Clocks](https://gitlab.gnome.org/GNOME/gnome-clocks/-/merge_requests/179) I recommended that a contributor use the portal, not knowing that [it doesn't work for unsandboxed apps](https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/3699).

Ideally these portal APIs should work outside of the flatpak sandbox.

**Comment by vchernin** [comment]
I believe background and autostart not working are all consequences of https://github.com/flatpak/xdg-desktop-portal/issues/579

**Comment by pearsche** [comment]
hopefully this can be implemented for non-flatpak apps soon

**Comment by GeorgesStavracas** [comment]
For the Background portal in particular, so far nobody proposed a meaningful mechanism to identify apps - in contrast to services and arbitrary executables - when they're not executing under a sandbox. The good practice around portals is that we cannot simply rely on sensitive information generated by the app (e.g. we cannot use the app-id *reported by the app*). I think for now it's okay to consider the unsandboxed case as out-of-scope for the Background portal. Of course, if someone is able to come up with a reliable mechanism to detect such cases on the host system, and implements that on xdg-desktop-portal, it would be accepted.
