### ISSUE TITLE
Add a share portal

### ISSUE THREAD

**Issue by Aurnytoraink** [flatpak/xdg-desktop-portal#651]
It would be interesting to have a portal that allow to share text, photos, musics, files between apps.

All apps should have a config file that includes what type of file they support, and the actions they do when they received the file.
For example, you have a picture, so you can publish it on Twitter or send it to your friend.

Also, you can directly bind contact or devices (e.g., via Bluetooth)

Here is a visual
PS: I'm not a professional designer
![share-portal](https://user-images.githubusercontent.com/28545669/139096867-43429e93-18e3-4308-b1c6-4af3485099d8.png)

**Comment by jadahl** [comment]
Closing since #12 already covers this.
/close
