### ISSUE TITLE
Extremely High Memory Usage

### ISSUE THREAD

**Issue by lvfrazao** [flatpak/xdg-desktop-portal#657]
Hello :wave:,

I recently noticed `xdg-desktop-portal` consuming a very high amount of memory (28gb rss) without any indication as to why. 
```
$ ps xao pid,ppid,rss,cmd | awk '(NR==1 || /xdg-desktop/) && !/awk/'
  PID  PPID   RSS CMD
31087     1 28958400 /usr/libexec/xdg-desktop-portal
31168     1 19784 /usr/lib64/libexec/xdg-desktop-portal-kde
```

![image](https://user-images.githubusercontent.com/31864869/141241471-ca2a9c41-f928-46f0-bbf8-ca496a7efb61.png)

Environment:
```
OS: Gentoo/Linux x86_64 
Kernel: 5.10.61-gentoo-x86_64 
Uptime: 2 days, 21 hours, 33 mins 
Packages: 1316 (emerge) 
Shell: bash 5.1.8 
DE: Plasma 
WM: KWin 
Theme: Breeze Dark [Plasma], Breeze [GTK2/3] 
Icons: breeze-dark [Plasma], breeze-dark [GTK2/3] 
Terminal: konsole 
CPU: AMD Ryzen 9 3900X (24) @ 3.800GHz 
GPU: NVIDIA GeForce RTX 2080 SUPER 
Memory: 36465MiB / 64291MiB 
```

Is this user error? Can I provide any additional content to help investigate this?

**Comment by lvfrazao** [comment]
And this is an output of attaching to proc 31087 and its children with strace for about 60 seconds:
```
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ------------------
 83.84   73.102145         114    640957     62480 futex
 14.02   12.224701          24    502628           poll
  0.88    0.763145           2    340644           write
  0.46    0.402326           2    174869           read
  0.42    0.362993           2    179304           recvmsg
  0.39    0.338413       26031        13         8 restart_syscall
  0.00    0.000222           3        63           brk
  0.00    0.000163          10        15        15 inotify_add_watch
  0.00    0.000112           3        37           mprotect
------ ----------- ----------- --------- --------- ------------------
100.00   87.194220          47   1838530     62503 total
```

**Comment by mwleeds** [comment]
@lvfrazao maybe a backtrace from gdb would help

**Comment by lvfrazao** [comment]
@mwleeds after a reboot the problem went away and I cannot reproduce it. I'll close it for now, if I can reproduce it I'll reopen the issue.

**Comment by A-UNDERSCORE-D** [comment]
Im sitting on this as well -- appears to happen after long games of minecraft using a flatpak'd launcher. While Ive got reprod I dont have a specific or fast one. But if someone can give me some pointers on what exactly would help here I'd be happy to provide it

**Comment by evpix** [comment]
This memory leak issue is still relevant.

**Comment by MurzNN** [comment]
Have this issue on Ubuntu 25.04 with KDE too - the `xdg-desktop-portal` in time starts to use several gigabytes of RAM and swap with no reason. Just killing the process resolves the issue, but it's better to find the root cause of this. Could anyone describe how can I provide more useful debug info to find the source of this issue?

**Comment by swick** [comment]
https://github.com/flatpak/xdg-desktop-portal/issues/1416#issuecomment-2939164073
