### ISSUE TITLE
Error with Epiphany

### ISSUE THREAD

**Issue by Tarch1** [flatpak/xdg-desktop-portal#661]
Hi,
I'm running Epiphany browser that work very great in most sites but it will become unusable in those sites: youtube and generic newspaper sites
I'm running a i5-8300h paired an nvidia 1050.
The system is Artix, linux kernel 5.14.16, with gnome-shell, mutter and relative gnome packages, I've used it with Wayland.
With one tab open on google.com uses 180 MB and webkitwebprocess uses 500 MB, resource monitor used is bpytop
App version: epiphany 41.0 - webkitgtk 2.34.1 - mutter 41.1 - gnome-shell 41.1
The error I've getting from terminal is:

(WebKitWebProcess:2): Gdk-WARNING **: 08:38:48.700: Settings portal not found: Could not connect: Connection refused

(WebKitWebProcess:2): Gtk-WARNING **: 08:38:48.728: Theme parsing error: gtk.css:2:123: Failed to import: Error opening file /home/tarch1/.local/share/gnome-shell/extensions/unite@hardpixel.eu/styles/gtk3/buttons-right/maximized.css: No such file or directory

Hopeful this will be useful

**Comment by Tarch1** [comment]
Guy, I've changed the laptop, now I have one with i5-11400H and RTX 3060, of previus bugs i have only one with youtube that with working audio but doesn't reproduce video, it instead shows only a white window

**Comment by GeorgesStavracas** [comment]
Hi, please report this to https://gitlab.gnome.org/GNOME/epiphany/ - nothing here looks like a portals bug
