### ISSUE TITLE
Applications opened from Flatpak apps get killed some seconds after getting launched

### ISSUE THREAD

**Issue by marcingold22** [flatpak/xdg-desktop-portal#664]
Hello everyone! I'm new to Linux and I'm in love with it!
I use the KDE Neon distro and I have an issue since 1-2 months ago.
Whenever I open an application from a Flatpak app the former gets killed some seconds after getting launched.

I have already asked for help on KDE's subreddit, and one kind user sent me here.
This is the error message I get from the logs:

```
nov 11 23:28:40 ******** systemd[1119]: Started Konsole - Terminale.
nov 11 23:28:49 ******** dbus-daemon[1142]: [session uid=1000 pid=1142] Activating via systemd: service name='org.freedesktop.portal.Desktop' unit='xdg-desktop-portal.service' requested by ':1.564' (uid=1000 pid=25043 comm="xdg-dbus-proxy --args=40 " label="unconfined")
nov 11 23:28:49 ******** systemd[1119]: Starting Portal service...
nov 11 23:28:49 ******** dbus-daemon[1142]: [session uid=1000 pid=1142] Successfully activated service 'org.freedesktop.portal.Desktop'
nov 11 23:28:49 ******** systemd[1119]: Started Portal service.
nov 11 23:28:49 ******** okular[25274]: Unable to open QuickAnnotatingTools XML definition
nov 11 23:28:50 ******** kwin_x11[1251]: qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 42860, resource id: 15778910, major code: 3 (GetWindowAttributes), minor code: 0
nov 11 23:28:50 ******** kwin_x11[1251]: qt.qpa.xcb: QXcbConnection: XCB error: 9 (BadDrawable), sequence: 42861, resource id: 15778910, major code: 14 (GetGeometry), minor code: 0
nov 11 23:29:19 ******** xdg-desktop-portal-kde[1557]: xdp-kde-background: GetAppState called: no parameters
nov 11 23:29:19 ******** kernel: xdg-desktop-por[25271]: segfault at 0 ip 00007fc5472e65f4 sp 00007fc537ffec78 error 4 in libglib-2.0.so.0.6400.6[7fc5472c2000+84000]
nov 11 23:29:19 ******** kernel: Code: f8 5b 5d c3 66 90 f3 0f 1e fa 48 83 ec 08 e8 33 ce fd ff 85 c0 0f 94 c0 48 83 c4 08 0f b6 c0 c3 66 0f 1f 44 00 00 f3 0f 1e fa <0f> be 07 41 b8 05 15 00 00 84 c0 74 1d 0f 1f 80 00 00 00 00 44 89
nov 11 23:29:19 ******** systemd[1119]: xdg-desktop-portal.service: Main process exited, code=killed, status=11/SEGV
nov 11 23:29:19 ******** systemd[1119]: xdg-desktop-portal.service: Failed with result 'signal'.
nov 11 23:29:19 ******** kwin_x11[1251]: qt.qpa.xcb: QXcbConnection: XCB error: 3 (BadWindow), sequence: 55073, resource id: 121634822, major code: 15 (QueryTree), minor code: 0
```
This is a video showing the issue with Calibre from Flatpak and Okular (non-Flatpak):
<video src="https://user-images.githubusercontent.com/94906648/143022873-d4eb6a72-b0e2-448f-aaf9-fab13be60bf4.mp4">
</video>

Thank you very much for your support and your work!

**Comment by GeorgesStavracas** [comment]
I've seen this being triggered by the Background portal kicking in and killing a process.

**Comment by vchernin** [comment]
Yes, there is a prompt in GNOME that asks if you want to let an app run in the background. If you select force quit it will remember your preference and subsequently kill the app in the future. 

I assume Plasma has something similar. The solution is to give the app background permission, you can use Flatseal if you want a GUI. 

I really think the background portal needs better discoverability. Issues like https://github.com/flatpak/xdg-desktop-portal/issues/478 are very frustrating if you don't know what's happening.

**Comment by marcingold22** [comment]
Thank you for caring! I don't know how I can help, but if you need any other info I'm available to collaborate!

**Comment by vchernin** [comment]
This is a more or less known issue, so I’m not sure what new information could be provided, but it’s a nice offer :)

For the sake of completeness did giving the apps background permission solve your particular issue?

**Comment by DennaGherlyn** [comment]
I did have the same problem for an app and allowing it to run in background solved it for me. It was just weird for me that KDE asked for permissions for some apps to run in background by itself and others not.

**Comment by marcingold22** [comment]
> For the sake of completeness did giving the apps background permission solve your particular issue?

Unfortunately I have never received any prompt to give background permission 🙄 according to @DennaGherlyn it's a common thing I guess. @DennaGherlyn might you let me know which apps asked for permission (if it's not too personal to know)?

The main Flatpaks I use that give me this problem are:
- Calibre
- Telegram
- Thunderbird

**Comment by marcingold22** [comment]
I'll try using Flatseal and will let you know in a moment

**Comment by DennaGherlyn** [comment]
I switched to KDE today, so I haven't opened that many apps yet.
For now I just had a problem with FreeTube. I just opened Calibre and it's working fine for me. 😕 Then I tried to provoke it with apps that didn't have the "run in background" enabled and the KDE notification appeared. Simultaneously the flag for "run in background" got ticked. So maybe before that some process that should be running crashed and this automatism didn't happen. I can't get it reproduced by removing the flags for FreeTube either. 
Regardless I don't think an app that's active and plays a video should be considered as an app running in background.

**Comment by vchernin** [comment]
Some [relevant discussion](https://gitlab.gnome.org/Teams/Design/os-mockups/-/issues/153) on background portal prompts in GNOME (also relevant for KDE etc).

**Comment by marcingold22** [comment]
Hi! I wanted to let you know that this problem doesn't occur anymore on my KDE machine! Thank you for your work! @DennaGherlyn can you confirm it doesn't happen to you?

@vchernin @GeorgesStavracas thank you for your support!

**Comment by DennaGherlyn** [comment]
I haven't encountered an app getting killed instead of setting the "allow run in background" flag any more.

**Comment by GeorgesStavracas** [comment]
https://github.com/flatpak/xdg-desktop-portal/pull/901 (which implements #899) will pretty much sidestep this whole issue.

**Comment by GeorgesStavracas** [comment]
Those landed. Let's close this one too.
