### ISSUE TITLE
The portal for opening URIs does not do anything

### ISSUE THREAD

**Issue by aleb** [flatpak/xdg-desktop-portal#68]
Using org.gnome.Platform 3.22:
```
(sandbox) $ gtk-launch --version
3.22.0
```

Out of the flatpak sandbox, running this opens the picture viewer, but in the sandbox nothing happens: no error, no picture viewer.
```
$ identify file:///tmp/x.png
file:///tmp/x.png=>/tmp/x.png PNG 129x100 2560x1600+436+519 8-bit sRGB 6.08KB 0.000u 0:00.000

$ python3 -c "from gi.repository import Gio; Gio.AppInfo.launch_default_for_uri('file:///tmp/x.png', None)"
```

Is this the proper way to do it?

**Comment by TingPing** [comment]
You have `xdg-desktop-portal-gtk` installed?

**Comment by aleb** [comment]
I installed `xdg-desktop-portal-gtk` and it works now. Thanks!
I was having the impression it should be integrated with the runtime, but obviously not.

**Comment by TingPing** [comment]
It has to run on the host so it cannot be in the runtime.
