### ISSUE TITLE
xdg-desktop-portal 1.12.1 breaks WebRTC Screesharing for FF/Chrome 

### ISSUE THREAD

**Issue by rstrube** [flatpak/xdg-desktop-portal#685]
Hello, I hope this is the right location to post this issue.  I've already opened up a bug report with my distro that can be found here: https://bugs.archlinux.org/task/73117?project=1&opened=33846

Since upgrading to **xdg-desktop-portal 1.12.1** and **xdg-desktop-portal-gtk 1.12.0** I have been unable to screenshare via WebRTC in Chrome and FF.  There is an immediate crash.

Downgrading back to **xdg-desktop-portal 1.10.1** and **xdg-desktop-portal-gtk 1.10.0** restored screensharing functionality via WebRTC.

I'm not sure if this is an upstream browser issue and they just need to build against the latest interface, similar to what happened with 1.10?  Perhaps my distro was a bit to aggressive to release updates and hasn't allowed browsers to catch up?

**Comment by GeorgesStavracas** [comment]
This crash was fixed with the 1.12.1 release. Did you restart your computer after installing it?

**Comment by rstrube** [comment]
Hello @GeorgesStavracas yes I did.  I never installed 1.12.0 and went directly to 1.12.1.  There are several others that are reporting similar issues.  Would you be interested in a core dump?

**Comment by rstrube** [comment]
OK... I must be going crazy.  I believe you're right, and perhaps I thought I had 1.12.1 installed when I really only had 1.12.0 installed.  I just performed a test using the Mozilla gUM test page, and screensharing via WebRTC worked fine...

I'm going to close this issue for now.  I apologize for misreporting.
