### ISSUE TITLE
Add API to know whether a certain portal is really available

### ISSUE THREAD

**Issue by nielsdg** [flatpak/xdg-desktop-portal#686]
There's a ton of different APIs that is part of xdg-desktop-portal. This means that some DEs might not have always implemented the complete set that is part of the latest XDG portals release.

As an application developer, I'm interested in knowing which APIs specifically are supported by the current session, so that I may deal with it in an appropriate way (e.g. making a "Screenshot"-button insensitive, or trying a X11-based fallback if we're running in an X11 session).

Some use cases I can think of when checking for support of a specific XDG portal feature:

1. I can check if the `org.freedesktop.portal.Desktop` name is claimed on the session bus (and ping it), to know that xdg-desktop-portal is installed on the system, and that it's running
2. I can introspect the `org.freedesktop.portal.Desktop` service, to make sure e.g. the screenshot portal exists in the version that is installed
3. I can't query if the impl of a specific portal exists, as the name on the bus is specific per implementation, and I ideally don't have to care about internal implementation of portals
4. I can't query if a certain feature of a portal exists (e.g. having a restore token available in the screencast portal)

At this point, I'm mostly (only) interested in solving point 3

**Comment by mwleeds** [comment]
> I can't query if a certain feature of a portal exists (e.g. having a restore token available in the screencast portal)

I think you can by checking the `version` attribute: https://github.com/flatpak/xdg-desktop-portal/blob/9aad2ffc5b3da8af0f6fa842ca7121f69f1740d8/data/org.freedesktop.portal.ScreenCast.xml#L314

**Comment by mwleeds** [comment]
I was asking about this functionality the other day and @TingPing said "I'm not against new API to query this" but it's not clear to me if that API should be in x-d-p or libportal. The use case I'm interested in is Epiphany being able to hide UI based on whether a dynamic launcher portal is available (#681).

**Comment by TingPing** [comment]
libportal has no way of knowing on its own, xdp has to expose it somehow.

**Comment by GeorgesStavracas** [comment]
Time for a meta-portal that allows querying which portals are implemented? :slightly_smiling_face:

**Comment by TingPing** [comment]
The API I was thinking of was something like (don't focus on the name): 

`bool org.freedesktop.portal.PortalInfo.IsPortalSupported(string portal_name, uint portal_version)`

This might be annoying to implement, like we don't want to just hardcode a list that gets outdated, and have to be in each backend.

**Comment by mwleeds** [comment]
> The API I was thinking of was something like (don't focus on the name):
> 
> `bool org.freedesktop.portal.PortalInfo.IsPortalSupported(string portal_name, uint portal_version)`
> 
> This might be annoying to implement, like we don't want to just hardcode a list that gets outdated, and have to be in each backend.
> 
> (It also means we might treat the version number differently in the future to represent feature-sets not just API breaks)

If we make the portal version an out parameter rather than an in parameter, then applications that can work with more than one version will only have to make one call to know the supported version.

**Comment by hadess** [comment]
Does this need to be a new API, rather than a convention that portals must export their versions in a specific format, combined with a helper function?

**Comment by nielsdg** [comment]
The problem is that the version that is exported by a portal is not necessarily the one (if any) that is implemented. For example, `org.freedesktop.portal.Screenshot` currently unconditionally exports a `Version` property which equals to 2, regardless of implementation (which is what I'm trying to figure out here)

**Comment by hadess** [comment]
> The problem is that the version that is exported by a portal is not necessarily the one (if any) that is implemented. For example, `org.freedesktop.portal.Screenshot` currently unconditionally exports a `Version` property which equals to 2, regardless of implementation (which is what I'm trying to figure out here)

Seems like a problem in that part of the code rather than something requiring new API, no?

**Comment by nielsdg** [comment]
Possibly, I don't know the internals of the code well enough :)

**Comment by mwleeds** [comment]
Looking at `xdg-desktop-portal.c` in `on_bus_acquired`, we only call `export_portal_implementation` (which does `g_dbus_interface_skeleton_export`) when an implementation is available, for those portals that need an implementation. So it seems applications _can_ check for the existence of an interface like `org.freedesktop.portal.FileChooser` to check if an implementation is available, with a C equivalent of `gdbus introspect -o /org/freedesktop/portal/desktop -d org.freedesktop.portal.Desktop --session`, unless I'm missing something?

Then the question of checking the available version is separate. I guess if portals need to support older versions of their implementation interface (and the only existing evidence I can find is `impl_version` in `screen-cast.c`), they should export an `impl_version` property in addition to the `version` property? It looks like the only portals that have a version property on their `impl` interface are PermissionStore, RemoteDesktop, ScreenCast, Secret, Session, and Settings.

**Comment by TingPing** [comment]
@mwleeds Ah I didn't realize it conditionally exported them. Yes all of that sounds right and more simple.

**Comment by mwleeds** [comment]
For reference, here's code I'm working on for Epiphany that checks if a portal is available by getting the version property. I assume it would also be possible to use `org.freedesktop.DBus.Introspectable` instead, but I haven't tried. I checked that this returns FALSE both for an interface unknown to `xdg-desktop-portal` and an interface with no implementation.
```
gboolean
ephy_can_install_web_apps (void)
{
  static gsize portal_available = 0;
  enum {
    LAUNCHER_PORTAL_MISSING = 1,
    LAUNCHER_PORTAL_FOUND = 2
  };

  if (!ephy_is_running_inside_sandbox ())
    return TRUE;

  if (g_once_init_enter (&portal_available)) {
    g_autoptr(GDBusProxy) proxy = NULL;
    g_autoptr(GVariant) version = NULL;
    g_autoptr(GVariant) version_child = NULL;
    g_autoptr(GVariant) version_grandchild = NULL;

    proxy = g_dbus_proxy_new_for_bus_sync (G_BUS_TYPE_SESSION, G_DBUS_PROXY_FLAGS_NONE, NULL,
                                           "org.freedesktop.portal.Desktop",
                                           "/org/freedesktop/portal/desktop",
                                           "org.freedesktop.DBus.Properties",
                                           NULL, NULL);
    if (proxy)
      version = g_dbus_proxy_call_sync (proxy, "Get",
                                        g_variant_new ("(ss)", "org.freedesktop.portal.DynamicLauncher", "version"),
                                        G_DBUS_CALL_FLAGS_NONE,
                                        -1, NULL, NULL);
    if (version) {
      version_child = g_variant_get_child_value (version, 0);
      version_grandchild = g_variant_get_child_value (version_child, 0);
      g_debug ("Found version %d of the dynamic launcher portal", g_variant_get_uint32 (version_grandchild));
      g_once_init_leave (&portal_available, LAUNCHER_PORTAL_FOUND);
    } else {
      g_once_init_leave (&portal_available, LAUNCHER_PORTAL_MISSING);
    }
  }

  return portal_available == LAUNCHER_PORTAL_FOUND;
}
```

(Of course if you just want to check portal availability regardless of whether you're under Flatpak or not, you'd remove the `ephy_is_running_inside_sandbox()` block)
