### ISSUE TITLE
Add `viewport` attribute in docs

### ISSUE THREAD

**Issue by TheEvilSkeleton** [flatpak/xdg-desktop-portal#691]
Is it possible to add `<meta name="viewport" content="width=device-width, initial-scale=1.0">` in the HTML? I have no idea how to add tags.

I wish to improve the docs by making it mobile-friendly.

**Comment by GeorgesStavracas** [comment]
I have no idea either. Somebody with web knowledge, please help.

**Comment by bilelmoussaoui** [comment]
i don't think you can easily do that as the html is generated by xmlto from the xml file
so you would have to add some post processing stage that would modify the html output and append the meta tag
