### ISSUE TITLE
Chrome and Electron applications showing multiple portal dialogs for screen sharing

### ISSUE THREAD

**Issue by szszoke** [flatpak/xdg-desktop-portal#692]
As the title says, Chrome and Electron applications all seem to show at least two portal dialogs when screen sharing is started.

After the initial round of dialogs are closed (by selecting a screen and pressing the confirm button) several additional dialogs pop up. By this point the preview in the application usually shows the screen in real-time.

I noticed this behavior with Chromium, Slack and Teams for Linux (which likely uses Electron). Firefox just shows one popup.

All Chromium-based applications have the PipeWire capturer enabled.

I used this website to test on Chromium and Firefox: https://www.webrtc-experiment.com/Pluginfree-Screen-Sharing

On Chrome, I get one portal dialog when I press the `Share you screen` button. At this point the source selector from Chromium is displayed below the portal dialog. After I select the screen (in Chromium) and press the `Share` button, the portal dialog is shown again.

Slack shows a similar behavior but with more dialogs opened.

I suppose this happens because the application first requests screen access to show a preview for their source selection and then again for the actual share but I don't know for sure.

I am wondering if this issue is known. Is it a problem with how Chromium is handling screen sharing or it is an issue with `xdg-desktop-portal`.

**Comment by GeorgesStavracas** [comment]
I'm afraid this is entirely a Chromium problem, there's nothing to be done in xdg-desktop-portal to prevent that. Chromium uses the portal to get a preview, and then uses it *again* to stream. I've already done the ground work on xdg-desktop-portal for Chromium not to do that, but they didn't start using the new APIs on their side.

**Comment by szszoke** [comment]
Thanks for clearing it up.
