### ISSUE TITLE
Examining failed when downloading file in Chromium

### ISSUE THREAD

**Issue by cgku** [flatpak/xdg-desktop-portal#699]
Hopefully, this is right place to post this.  For several weeks now, whenever I attempt to download a file from Chromium a desktop message appears, shows "Examining" briefly, then fails with the message "xdg-desktop-portal-kde Examining failed".  The save dialog box appears immediately afterward and the file can be saved without any further problem.

Chromium:  97.0.4692.99 (Official Build) snap (64-bit)
Operating System: Kubuntu 21.10
KDE Plasma Version: 5.22.5
KDE Frameworks Version: 5.86.0
Qt Version: 5.15.2
Kernel Version: 5.13.0-27-generic (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i5-3570K CPU @ 3.40GHz
Memory: 31.2 GiB of RAM

**Comment by smcv** [comment]
I don't think this message is coming from xdg-desktop-portal. I don't know where it's coming from, but x-d-p doesn't do anything that it describes as "examining".

> a desktop message appears, shows "Examining" briefly, then fails with the message "xdg-desktop-portal-kde Examining failed"

You say "fails". What do you mean by that? Is there any symptom that makes you believe something is not working correctly, other than the message "Examining failed"?

**Comment by smcv** [comment]
I think you're more likely to find out what is going on if you report this to Kubuntu's support channels. If you are able to save the file successfully, then it seems like xdg-desktop-portal and xdg-desktop-portal-kde are working as expected.

Bug tracking for xdg-desktop-portal-kde is on https://bugs.kde.org/ rather than here (see https://community.kde.org/Get_Involved/Issue_Reporting for more details), but from the symptoms you describe, I'm not sure that this is a bug in x-d-p-kde either.

**Comment by cgku** [comment]
Event sequence:

1. Perform a right click "Save as..", or click a download link, or any other action that prompts the user to save something.

2. A pop-up message appears stating "Examining":
![image](https://user-images.githubusercontent.com/54686681/150901593-c1ed9745-2839-4fc0-950d-8c1cdcd2e35d.png)

3. A few seconds pass, then this pop-up message appears "Examining (Failed)" and the path to the most recently saved file:
![image](https://user-images.githubusercontent.com/54686681/150902205-c8a871db-5ec6-4b86-bb75-ae7591672be2.png)

4. The save dialog box immediately appears.  I can select the path and enter the file name, click [Save] and the file is successfully saved.

This happens on every download.

I'm not sure where you are getting x-d-p. My report concerns x-d-g and that is the name of this page (unless I'm completely missing something).  Regardless, if you think this is not the page for this issue, then I can open a bug report on the KDE page.  

Thanks for your time.

**Comment by cgku** [comment]
Sorry, I failed to realized that this page is for xdg-desktop-portal and not xdg-desktop-portal-KDE.  I'll report the problem on the their site.

FYI: here is the detailed explanation of what's happening:
Event sequence:

1. Perform a right click "Save as..", or click a download link, or any other action that prompts the user to save something.

    

2. A pop-up message appears stating "Examining":

    
![image](https://user-images.githubusercontent.com/54686681/150903492-4c77d907-20eb-46e9-83e3-d5094ce43b08.png)


3. A few seconds pass, then this pop-up message appears "Examining (Failed)" and the path to the most recently saved file:

![image](https://user-images.githubusercontent.com/54686681/150903515-27d8c4a8-b7c0-4e94-beff-0ff244cef275.png)

4. The save dialog box immediately appears. I can select the path and enter the file name, click [Save] and the file is successfully saved.

This happens on every download.

Thanks for your time.

**Comment by smcv** [comment]
That description makes it a lot clearer what is happening and will be useful to maintainers of other components.

I'm pretty sure that can't be coming from xdg-desktop-portal, which is non-GUI (it talks to x-d-p-kde, x-d-p-gtk or some similar backend for anything involving GUI interactions), so I'm going to close this.

**Comment by kayrus** [comment]
@cgku this issue was fixed with the https://invent.kde.org/plasma/xdg-desktop-portal-kde/-/merge_requests/122/diffs

if you'd like have a patched version, you can create a patched package yourself, e.g. in docker container.

<details><summary>example</summary>
run docker container: docker run --rm -ti -v $(pwd):/mnt ubuntu:22.04

```sh
apt update && apt dist-upgrade -y
apt install -y wget cmake debhelper-compat extra-cmake-modules gettext kirigami2-dev libcups2-dev libepoxy-dev libgbm-dev libkf5config-dev libkf5coreaddons-dev libkf5declarative-dev libkf5i18n-dev libkf5kio-dev libkf5notifications-dev libkf5plasma-dev libkf5wayland-dev libkf5widgetsaddons-dev libkf5windowsystem-dev libpipewire-0.3-dev libqt5waylandclient5-dev libwayland-dev pkg-kde-tools plasma-wayland-protocols qtbase5-dev qtbase5-private-dev qtdeclarative5-dev qtwayland5-dev-tools

cd /mnt
wget http://archive.ubuntu.com/ubuntu/pool/universe/x/xdg-desktop-portal-kde/xdg-desktop-portal-kde_5.24.7-0ubuntu0.1.dsc http://archive.ubuntu.com/ubuntu/pool/universe/x/xdg-desktop-portal-kde/xdg-desktop-portal-kde_5.24.7.orig.tar.xz http://archive.ubuntu.com/ubuntu/pool/universe/x/xdg-desktop-portal-kde/xdg-desktop-portal-kde_5.24.7-0ubuntu0.1.debian.tar.xz
dpkg-source -x xdg-desktop-portal-kde_5.24.7-0ubuntu0.1.dsc
cd xdg-desktop-portal-kde-5.24.7
patch -p1 src/filechooser.cpp <(curl -s https://invent.kde.org/plasma/xdg-desktop-portal-kde/-/merge_requests/122/diffs.patch)
dpkg-buildpackage -b -rfakeroot -us -uc -nc -j8
```

as a result you'll get patched `xdg-desktop-portal-kde_5.24.7-0ubuntu0.1_amd64.deb`, which can be installed with `sudo dpkg -i xdg-desktop-portal-kde_5.24.7-0ubuntu0.1_amd64.deb`
</details>
