### ISSUE TITLE
Adding xdg-desktop-portal to graphical-session-pre.target deadlocks GNOME 41 login

### ISSUE THREAD

**Issue by smcv** [flatpak/xdg-desktop-portal#734]
After upgrading xdg-desktop-portal from 1.12.2 to 1.14.0, rebooting and logging in, my GNOME session failed to start, with a blank screen with an immovable mouse pointer.

This is on Debian testing/unstable (GNOME 41 and parts of GNOME 42, GLib 2.72.0).

This appears to be linked to commit f200147d "Make x-d-p start on session start". Starting x-d-p "eagerly" on session start results in it trying to start a backend such as x-d-p-gnome, which fails to connect to the display server and times out; this appears to result in the GNOME session getting stuck.

```
Mar 18 11:07:41 momentum dbus-daemon[25966]: [session uid=1000 pid=25966] Activating via systemd: service name='org.fre
edesktop.portal.Documents' unit='xdg-document-portal.service' requested by ':1.15' (uid=1000 pid=26025 comm="/usr/libex
ec/xdg-desktop-portal")
Mar 18 11:07:41 momentum dbus-daemon[25966]: [session uid=1000 pid=25966] Successfully activated service 'org.gtk.vfs.U
Disks2VolumeMonitor'
Mar 18 11:07:41 momentum systemd[25930]: Starting flatpak document portal service...
Mar 18 11:07:41 momentum systemd[25930]: Started Virtual filesystem service - disk device monitor.
Mar 18 11:07:41 momentum dbus-daemon[25966]: [session uid=1000 pid=25966] Activating via systemd: service name='org.gtk
.vfs.MTPVolumeMonitor' unit='gvfs-mtp-volume-monitor.service' requested by ':1.10' (uid=1000 pid=26005 comm="/usr/libex
ec/tracker-miner-fs-3")
Mar 18 11:07:41 momentum systemd[25930]: Starting Virtual filesystem service - Media Transfer Protocol monitor...
Mar 18 11:07:41 momentum dbus-daemon[25966]: [session uid=1000 pid=25966] Activating via systemd: service name='org.fre
edesktop.impl.portal.PermissionStore' unit='xdg-permission-store.service' requested by ':1.16' (uid=1000 pid=26037 comm
="/usr/libexec/xdg-document-portal")
Mar 18 11:07:41 momentum systemd[25930]: Starting sandboxed app permission store...
Mar 18 11:07:41 momentum dbus-daemon[25966]: [session uid=1000 pid=25966] Successfully activated service 'org.gtk.vfs.M
TPVolumeMonitor'
Mar 18 11:07:41 momentum systemd[25930]: Started Virtual filesystem service - Media Transfer Protocol monitor.
Mar 18 11:07:41 momentum dbus-daemon[25966]: [session uid=1000 pid=25966] Successfully activated service 'org.freedeskt
op.impl.portal.PermissionStore'
Mar 18 11:07:41 momentum systemd[25930]: Started sandboxed app permission store.
Mar 18 11:07:41 momentum dbus-daemon[25966]: [session uid=1000 pid=25966] Successfully activated service 'org.freedeskt
op.portal.Documents'
Mar 18 11:07:41 momentum systemd[25930]: Started flatpak document portal service.
Mar 18 11:07:41 momentum dbus-daemon[25966]: [session uid=1000 pid=25966] Activating via systemd: service name='org.gtk
.vfs.GPhoto2VolumeMonitor' unit='gvfs-gphoto2-volume-monitor.service' requested by ':1.10' (uid=1000 pid=26005 comm="/u
sr/libexec/tracker-miner-fs-3")
Mar 18 11:07:41 momentum systemd[25930]: Starting Virtual filesystem service - digital camera monitor...
Mar 18 11:07:41 momentum dbus-daemon[25966]: [session uid=1000 pid=25966] Activating via systemd: service name='org.fre
edesktop.impl.portal.desktop.gnome' unit='xdg-desktop-portal-gnome.service' requested by ':1.15' (uid=1000 pid=26025 co
mm="/usr/libexec/xdg-desktop-portal")
Mar 18 11:07:41 momentum systemd[25930]: Starting Portal service (GNOME implementation)...
Mar 18 11:07:41 momentum dbus-daemon[25966]: [session uid=1000 pid=25966] Successfully activated service 'org.gtk.vfs.G
Photo2VolumeMonitor'
Mar 18 11:07:41 momentum systemd[25930]: Started Virtual filesystem service - digital camera monitor.
Mar 18 11:07:41 momentum dbus-daemon[25966]: [session uid=1000 pid=25966] Activating via systemd: service name='org.gtk
.vfs.GoaVolumeMonitor' unit='gvfs-goa-volume-monitor.service' requested by ':1.10' (uid=1000 pid=26005 comm="/usr/libex
ec/tracker-miner-fs-3")
Mar 18 11:07:41 momentum systemd[25930]: Starting Virtual filesystem service - GNOME Online Accounts monitor...
Mar 18 11:07:41 momentum dbus-daemon[25966]: [session uid=1000 pid=25966] Activating service name='org.gnome.OnlineAcco
unts' requested by ':1.20' (uid=1000 pid=26065 comm="/usr/libexec/gvfs-goa-volume-monitor")
Mar 18 11:07:41 momentum xdg-desktop-por[26057]: cannot open display: 
Mar 18 11:07:41 momentum systemd[25930]: xdg-desktop-portal-gnome.service: Main process exited, code=exited, status=1/F
AILURE
Mar 18 11:07:41 momentum systemd[25930]: xdg-desktop-portal-gnome.service: Failed with result 'exit-code'.
Mar 18 11:07:41 momentum systemd[25930]: Failed to start Portal service (GNOME implementation).
```

For now, I'm going to revert that commit.

**Comment by smcv** [comment]
I think the problem here is something like this:

* `WantedBy=graphical-session-pre.target` in x-d-p translates to the equivalent of `Wants=xdg-desktop-portal.service` in `graphical-session-pre.target`
* For targets, `Wants=x` implies `After=x` unless `DefaultDependencies=no`
* `org.gnome.Shell@wayland.service` has `After=gnome-session-manager.target`
* `gnome-session-manager.target` has `After=gnome-session-pre.target`
* `gnome-session-pre.target` has `After=graphical-session-pre.target`
* So we won't start gnome-shell until after x-d-p has reported success
* x-d-p doesn't report success until after it has communicated with its backend
* Its backend can't start because the Wayland compositor isn't up yet, because we won't start gnome-shell until after x-d-p has reported success

... and this might be exacerbated by failure to start a D-Bus-activated service not being signalled back to dbus-daemon (systemd/systemd#21520). (dbus-broker might avoid this by doing its systemd activation differently.)

**Comment by smcv** [comment]
@mwleeds, is it strictly necessary that x-d-p starts up before the compositor, or would it be OK to defer x-d-p startup (and hence renaming of dynamic launchers for EOL'd apps) until some later point like `default.target`?

**Comment by smcv** [comment]
With hindsight, I should probably have insisted on a 1.13.x development release before declaring this new interface to be stable.

**Comment by smcv** [comment]
I've reverted f200147dd4121585114f1e4bb4b1963bf18ceb2d in the Debian packaging (as version 1.14.0-2) and that seems to work a lot better.

**Comment by mwleeds** [comment]
Sorry about that. Clearly I should've tested it more; I was starting `x-d-p` manually for testing not via systemd.

> @mwleeds, is it strictly necessary that x-d-p starts up before the compositor, or would it be OK to defer x-d-p startup (and hence renaming of dynamic launchers for EOL'd apps) until some later point like `default.target`?

If we delay the startup until after the user has a chance to launch applications, there would be a chance the launcher wouldn't work since it hadn't been rewritten by `x-d-p` yet. Not sure where `default.target` stands in relation to that?

**Comment by GeorgesStavracas** [comment]
@mwleeds an alternative is to move the code that is supposed to run on session startup into a separate binary. How does it sound?

**Comment by mwleeds** [comment]
> @mwleeds an alternative is to move the code that is supposed to run on session startup into a separate binary. How does it sound?

That sounds like a good approach. I'll work on it.
