### ISSUE TITLE
xdg_app_info_map_pids() returns incorrect PID

### ISSUE THREAD

**Issue by TingPing** [flatpak/xdg-desktop-portal#747]
I'm not certain I understand everything that is happening but I believe this is roughly what is going on.

1. `xdp_invocation_lookup_app_info_sync()` is how an `XdpAppInfo` is associated with any DBus method.
1. It calls `org.freedesktop.DBus.GetConnectionUnixProcessID()` on the sender.
1. This returns the pid of the proxies in the middle (`flatpak-portal`, `xdg-dbus-portal`, etc)
1. We then use that pid's namespace for pid mapping

This is most reproducable with WebKit. When it makes its own sandbox the PID returned is for `xdg-dbus-proxy`. When it uses `flatpak-spawn` subsandboxes the PID returned is for `flatpak-portal`.

CC @mcatanzaro

**Comment by TingPing** [comment]
@alexlarsson Maybe you could help me understand how this is expected to work?

The structure of WebKit's sandbox is:

```
BrowserProcess
  - bwrap
    - xdg-dbus-proxy
  - bwrap
    - WebKitWebProcess
```

All DBus traffic goes through `xdg-dbus-proxy` so `xdg-desktop-portal` just reads the root filesystem of it, instead of the web process.

**Comment by swick** [comment]
> We then use that pid's namespace for pid mapping

We lookup the pid namespace of the app sandbox, not the pid namespace of the calling process.

https://github.com/flatpak/xdg-desktop-portal/blob/main/src/xdp-utils.c#L2098-L2111

TBH I still don't understand what problem you're running into exactly.

**Comment by TingPing** [comment]
> https://github.com/flatpak/xdg-desktop-portal/blob/main/src/xdp-utils.c#L2098-L2111

The XdpAppInfo is wrong.

`xdp_invocation_lookup_app_info_sync()` returns AppInfo for the DBus proxy not for the web process. So everything process specific is wrong for WebKit atm.

**Comment by swick** [comment]
`xdp_invocation_lookup_app_info_sync` eventually calls `parse_app_info_from_flatpak_info` with the PID of the DBus proxy which looks at `/proc/$pid/root/.flatpak-info`. That file should contain the information about the correct appid, not something about the DBus proxy.

If `XdpAppInfo` is actually wrong there is something fishy going on in `parse_app_info_from_flatpak_info`. But it's expected (even required to avoid PID races) that the PID is from the proxy.

**Comment by mcatanzaro** [comment]
See also: https://bugs.webkit.org/show_bug.cgi?id=238403

**Comment by hfiguiere** [comment]
Didn't this get fixed part of #837. tid (and pid) get remapped for RTKit.

**Comment by TingPing** [comment]
Closing this as this issue was likely incorrect and with https://github.com/WebKit/WebKit/pull/23052 and #837 everything should work in WebKit.

**Comment by swick** [comment]
Why does WebKit create bwrapinfo.json? If the portal doesn't work with host programs, we should fix that.

**Comment by TingPing** [comment]
> Why does WebKit create bwrapinfo.json? If the portal doesn't work with host programs, we should fix that.

It isn't a host program. WebKitWebProcesses have a custom bwrap sandbox and want to use portals.

**Comment by swick** [comment]
Right, but it's still a host program which spawns its own bwrap sandbox and not a sandboxed app!

This leaks implementation details of flatpak into a host program to be able to use portals. We can and should fix the portal instead.

**Comment by swick** [comment]
Yikes, that's cursed. There is no way to do the pid mapping without help there. Never mind then.

With the Containers1 thing I'm working on the pid mapping (and everything really) in x-d-p won't rely on .flatpak-info or bwrapinfo.json eventually for everything, so be aware.
