### ISSUE TITLE
xdg-permission-store consumes most of RAM after "flatpak remove --delete-data" command

### ISSUE THREAD

**Issue by rezad1393** [flatpak/xdg-desktop-portal#748]
flatpak Version 1:1.12.7-1
xdg-desktop-portal 1.14.1-1

I see that recently this process "xdg-permission-store" consumes almost 8GB (which actually fiils up my memory so maybe it can consumed more)

**Comment by rezad1393** [comment]
this may have occurred after playing dota in steam from flatpak.

**Comment by rezad1393** [comment]
UPDATE:
I can reproduce the bug.

if I install ,for example, a simple app like Kamoso webcam app.
and not even open it. 
then uninstall it with "flatpak remove --delete-data Kamoso" command , the delete-data part is the culprit and just uses most RAM for a long time. 
after finishing the command, most of the time the  xdg-permission-store process stays in memory with a huge size, like most of my memory size , almost 12GB.

**Comment by GeorgesStavracas** [comment]
This bug is technically older than https://github.com/flatpak/xdg-desktop-portal/issues/833, but seems like discussions are happening there already, so let's mark this one as duplicated instead.

Duplicated of https://github.com/flatpak/xdg-desktop-portal/issues/833

**Comment by GeorgesStavracas** [comment]
Duplicated of https://github.com/flatpak/xdg-desktop-portal/issues/833

**Comment by incloxe** [comment]
Still an issue. Memory leak at 11.8GB for xdg-permission-store process on my system.
