### ISSUE TITLE
Add portal / permission for recording system audio

### ISSUE THREAD

**Issue by jadahl** [flatpak/xdg-desktop-portal#751]
Some apps may want to record the audio output of the session, for example when screen sharing while playing a video with sound. Right now this requires manual work done by the user to re-route audio, e.g. via pavucontrol.

Instead of a "all-in" permission for completely arbitrary audio-rerouting ability a permission for recording the system audio alone could be useful when complete control is not necessary.

For reference: https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/1636

**Comment by doubledge-spec** [comment]
Any update about this issue?

**Comment by hfiguiere** [comment]
Related: #1129
