### ISSUE TITLE
Allow adding to the Menu with DynamicLauncher Portal

### ISSUE THREAD

**Issue by JakobDev** [flatpak/xdg-desktop-portal#755]
The documentation of the new DynamicLauncher Portal currently says:

> Portal for installing application launchers onto the desktop

It would be nice, if applications also could be added to the menu (~/.local/share/applications) and not only the Desktop.

**Comment by mwleeds** [comment]
All launchers created with the dynamic launcher portal have a symlink created in `~/.local/share/applications` so it sounds like this is just an issue of the wording in the docs being confusing. Do you want to propose better wording?

**Comment by JakobDev** [comment]
This is definitive a issue with the documentation. It should be mentioned. This Portal is new, so I haven't tried it out yet. I read only the documentation.

But on the other Hand, this implementation is far from optional. It currently creates a entry on the desktop and in the menu, but there are cases where users wants to add a Program only to the Menu or only to the Desktop, what isn't supported yet.

**Comment by mwleeds** [comment]
> This is definitive a issue with the documentation. It should be mentioned. This Portal is new, so I haven't tried it out yet. I read only the documentation.
> 

Opened #765 to clarify the short description. I think the long description below it makes it pretty clear what the behavior is.

> But on the other Hand, this implementation is far from optional. It currently creates a entry on the desktop and in the menu, but there are cases where users wants to add a Program only to the Menu or only to the Desktop, what isn't supported yet.

No, the launcher is only created in the menu, not on the desktop.
