### ISSUE TITLE
RFC: python test suite?

### ISSUE THREAD

**Issue by whot** [flatpak/xdg-desktop-portal#761]
I'm just leaving this here because otherwise it'll go under: in #714 I've implemented a python-dbusmock-based test suite for portal testing. It's not a 100% overlap to the existing test suite (it's a bit hard to decipher what that all does, I'd need more time for this). But writing actual tests against a portal is significantly simpler than the current glib test suite approach.

See [this commit](https://github.com/flatpak/xdg-desktop-portal/pull/714/commits/3d9ccdae5c51c9857fca7c85ea145c0a212cb855) for the addition of the test suite + the InputCapture portal tests. Executed via `pytest` in the git tree.

I'd love to hear some comments about viability, etc.

**Comment by jadahl** [comment]
A big +1 on using python-dbusmock to mock impl portals for testing.

Some portals directly interact with the permission store to get/set/update things; should the permission store get a bock implementation too for this? Or perhaps the real one can be launched some way to make it store things in a temporary database.

**Comment by whot** [comment]
I'd say as an intermediate solution, just launching through `subprocess` (like `test-portals.c` currently does) should provide the same functionality current tests have. Then later the rest can be mocked so we don't have to do that.
