### ISSUE TITLE
Permission request dialog text is trimmed

### ISSUE THREAD

**Issue by mimi89999** [flatpak/xdg-desktop-portal#763]
![Screenshot from 2022-04-03 12-30-13](https://user-images.githubusercontent.com/8530546/161424624-33403ab7-e0c8-4114-9ef1-27222f4f2e90.png)

Version: `1.14.1`

**Comment by vchernin** [comment]
`xdg-desktop-portal` doesn't create those dialogs, the backend does. This should be reported at https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/.

**Comment by hadess** [comment]
> `xdg-desktop-portal` doesn't create those dialogs, the backend does. This should be reported at https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/.

The backend doesn't either, gnome-shell does (https://gitlab.gnome.org/GNOME/gnome-shell/blob/main/js/ui/accessDialog.js)

Please file a bug against gnome-shell at https://gitlab.gnome.org/GNOME/gnome-shell/-/issues
