### ISSUE TITLE
`org.freedesktop.portal.Settings.Read` ("color-scheme") returns `Variant[Variant[uint]]`, while `*.impl.*.Read` returns just `Variant[uint]`

### ISSUE THREAD

**Issue by SerVB** [flatpak/xdg-desktop-portal#789]
This can be seen in the log in the following picture:

![grafik](https://user-images.githubusercontent.com/20105593/166912322-4b200fd1-d5a4-4f51-9940-646d0d511164.png)

First call was made to:
```
Bus name: org.freedesktop.portal.Desktop
Object path: /org/freedesktop/portal/desktop
Interface: org.freedesktop.portal.Settings
Method: Read
Args: "org.freedesktop.appearance", "color-scheme"
```

Reply: `Variant: [Variant(uint): 2]`.

Second call was made to:
```
Bus name: org.freedesktop.impl.desktop.kde   <-- different
Object path: /org/freedesktop/portal/desktop
Interface: org.freedesktop.impl.portal.Settings   <-- different
Method: Read
Args: "org.freedesktop.appearance", "color-scheme"
```

Reply: `Variant(uint): 2`.

I don't understand why results are different since XMLs look equal to me ([org.freedesktop.portal.Settings.xml](https://github.com/flatpak/xdg-desktop-portal/blob/d7a304a00697d7d608821253cd013f3b97ac0fb6/data/org.freedesktop.portal.Settings.xml) and [org.freedesktop.impl.portal.Settings.xml](https://github.com/flatpak/xdg-desktop-portal/blob/d7a304a00697d7d608821253cd013f3b97ac0fb6/data/org.freedesktop.impl.portal.Settings.xml)). The second reply looks OK, the first one doesn't (I would say it doesn't match the docs). Probably it's a bug in the first case?

Just in case, OS info:
```
Operating System: Manjaro Linux
KDE Plasma Version: 5.24.4
KDE Frameworks Version: 5.92.0
Qt Version: 5.15.3
Kernel Version: 5.17.1-3-MANJARO (64-bit)
Graphics Platform: X11
```

**Comment by robert-ancell** [comment]
The bug is in `settings_handle_read` - it reads the value as a variant from the backend, and instead of passing it directly back the caller it puts it inside another variant first.

**Comment by grulja** [comment]
I can reproduce and I think it explains why sometimes when using QGnomePlatform it gets the light theme even though the dark variant is set.
