### ISSUE TITLE
[feature request] announcing a portal implementation via dbus

### ISSUE THREAD

**Issue by mahkoh** [flatpak/xdg-desktop-portal#803]
I am writing a wayland compositor that, in the future, will ship an in-process protal implementation for screenshots and screencasts. I would like the compositor to be plug-and-play, that is, after compiling the compositor it can be run immediately and everything works.

Unfortunately xdg-desktop-portal currently seems to require the user to additionally move a portal file to a dedicated location for the compositor's portal to be picked up. Instead, I would like my compositor to be able to announce its portals to xdg-desktop-portal via some dbus api. The compositor would call a dbus method on xdg-desktop-portal which would contain all of the information that is currently stored in portal files. xdg-desktop-portal would then add this portal to its lists of known portals.

**Comment by GeorgesStavracas** [comment]
Sorry, this is out of scope for xdg-desktop-portals for now.

**Comment by jadahl** [comment]
https://github.com/flatpak/xdg-desktop-portal/issues/906 might be related/help.
