### ISSUE TITLE
[feature request] portal definitions stored under $HOME

### ISSUE THREAD

**Issue by mahkoh** [flatpak/xdg-desktop-portal#804]
It appears that xdg-desktop-portal currently only checks `/usr/share/xdg-desktop-portal/portals` for available portals. This means that a user trying to install a new portal must have root on the system. I would like for xdg-desktop-portal to additionally check a location under $HOME e.g. `~/.config/xdg-desktop-portal/portals`.

**Comment by GeorgesStavracas** [comment]
This would make it trivial for sandboxed applications to hijack a security-sensitive session service, that cannot be allow to happen.

**Comment by swick** [comment]
Sandboxed applications do not have access to that directory and there is no security related reason (I can think of) why we could not look in there as well.

**Comment by swick** [comment]
So you don't have to modify your system to test your code. On silverblue for example I can only write things to /usr temporarily.

**Comment by GeorgesStavracas** [comment]
So let me be a bit blunter then: I will not accept code that allows users without elevated permissions to break xdg-desktop-portal. This is, at best, convenience for developers, and even then, a dubious convenience.

**Comment by GeorgesStavracas** [comment]
Okay. Still a no though.

**Comment by mahkoh** [comment]
The solution for the user is to recompile xdp with the portal path set to something under HOME. He can then replace the OS's xdp version by creating a dbus service definition also under HOME. Obviously none are f that s requires root and it fixes the problem.

**Comment by swick** [comment]
> So let me be a bit blunter then: I will not accept code that allows users without elevated permissions to break xdg-desktop-portal.

Why not? Portals are user services. They can be broken in any number of ways.

**Comment by Isti115** [comment]
This thread has such weird, unfounded and conflicting responses to these perfectly reasonable comments. 🤔
Could someone else take a look at this please, maybe @jadahl or @smcv? (I picked you two from recent commit activity, but feel free to refer other relevant people if you can!)

I am running into this on NixOS, where I'd like to avoid touching the system folders directly.
Having the same list of possible configuration locations as for the `portals.conf` file would seem consistent and logical to me:
https://github.com/flatpak/xdg-desktop-portal/blob/66464504ad7210219f7a98511e0dfad4ae337d75/doc/portals.conf.rst.in#L17-L27
