### ISSUE TITLE
[feature request] portal definition overrides

### ISSUE THREAD

**Issue by mahkoh** [flatpak/xdg-desktop-portal#805]
My wayland compositor currently exposes a wlroots-compatible interface that allows it to work with xdg-desktop-portal-wlr. My compositor's name has not yet been added to the portal's UseIn list so users have to modify the portal file itself. I would like for xdg-desktop-portal to have an override functionality similar to what [systemd](https://www.freedesktop.org/software/systemd/man/systemd.unit.html) (C-f override) offers. This would allow users to change the UseIn definition of `wlr.portal` without having to modify wlr.portal itself.

**Comment by GeorgesStavracas** [comment]
The new config file mechanism should be enough to do this.
