### ISSUE TITLE
Show normal folder instead of sandboxed one

### ISSUE THREAD

**Issue by Mikenux** [flatpak/xdg-desktop-portal#807]
Firefox and Evince both have an option to open the folder where a file is located. In Firefox, it's when we click the "Show in Folder" button next to a downloaded file. In Evince, it is when we click on "Open Containing Folder".

When these apps are sandboxed, these options open the sandboxed folder (e.g. `/run/user/1000/doc/a1b23c4d`), whereas we might expect it to be the normal folder which opens in the file manager (e.g. `/home/user/Documents/MyFiles`).

Having a way for sandboxed apps to show normal folders instead of sandboxed ones would be nice.

One idea is to have something that translates sandbox paths (for sandboxed folders) to normal paths (normal folders). Maybe it could be useful for other cases (I don't have any examples).

**Comment by rusty-snake** [comment]
Related: #475

**Comment by hadess** [comment]
This is already do-able using the OpenDirectory portal API:
```
Asks to open the directory containing a local file in the file browser.
```
which is also available through libportal.

For evince in particular, this is already implementable:
https://gitlab.gnome.org/GNOME/libdazzle/-/issues/65

**Comment by Mikenux** [comment]
Thanks!

**Comment by Mikenux** [comment]
@GeorgesStavracas: Could you reopen this one? This is what is asked in other issues, but there was confusion between "chooser" and "manager". Maybe it's better to let the portal translate paths rather than apps using another library (libdazzle: https://github.com/flatpak/xdg-desktop-portal/issues/807#issuecomment-1135567300)?
