### ISSUE TITLE
Add short command line aliases

### ISSUE THREAD

**Issue by fenryxo** [flatpak/xdg-desktop-portal#82]
Nowadays, when users wants to interact with Nuvola Player in command line, they have to type long commands such as `flatpak run --command=nuvolactl eu.tiliado.Nuvola track-info` instead of plain `nuvolactl track-info`. If would be useful if there was a Flatpak portal that would let Nuvola to create the `nuvolactl` alias upon user's request.

**Comment by TingPing** [comment]
They would have to be prefixed with the app-id to be remotely secure. so `eu.tiliado.Nuvola.nuvolactl` or something. At that point it makes more sense for the user to just make an alias in their shell.

**Comment by matthiasclasen** [comment]
This doesn't seem like a portal feature to me. The recommendation to just make a shell alias seems right.
