### ISSUE TITLE
xdg-desktop-portal fails when selecting a remote URI from a Flatpak/Snap

### ISSUE THREAD

**Issue by sergio-costas** [flatpak/xdg-desktop-portal#820]
If the user has a remote drive mounted using Gvfs (using SFTP or SMB, for example), and a containerized application calls any of the methods in `org.freedesktop.portal.FileChooser`, the file chooser do show the remote units:

![Captura desde 2022-06-23 15-30-59](https://user-images.githubusercontent.com/105285003/175357855-e332e7dd-9348-4dc4-8431-36c5f55bf696.png)

If the user chooses a local file, the xdg-desktop-portal works as expected and "tunnels" the file:

![Captura desde 2022-06-23 15-36-21](https://user-images.githubusercontent.com/105285003/175358217-db76c9c3-2105-4fb9-b519-c3573d58be95.png)

But if the user chooses a file in the remote drive, the portal returns no URI:

![Captura desde 2022-06-23 15-33-53](https://user-images.githubusercontent.com/105285003/175358345-c1255a04-4011-4c9d-bd5f-13cf739ee350.png)

Also, `xdg-desktop-portal` shows an error in the terminal where it is running (of course, this requires to kill it previously and launch it from a terminal):

![Captura desde 2022-06-23 15-32-36](https://user-images.githubusercontent.com/105285003/175358562-4671d229-1ea4-44df-a7c6-2286650097fd.png)

The test code used (a python program that calls directly to the DBus API) and the JSON file to build a Flatpak is here:

[test_portal_python.zip](https://github.com/flatpak/xdg-desktop-portal/files/8969425/test_portal_python.zip)

But it also happens with Firefox in Flatpak: trying to save a page or a PDF in a remote drive mounted using Gvfs fails, and shows the same error in `xdg-desktop-portal`.

**Comment by sergio-costas** [comment]
A proposed solution was to manually map any remote file to the corresponding Gvfs FUSE mount. This code is available at https://github.com/flatpak/xdg-desktop-portal/pull/814

With this code, it is possible to save PDF files from Firefox (both in Flatpak and Snap containers) in remote drives, without having to enable VFS in `xdg-desktop-portal`.

**Comment by GeorgesStavracas** [comment]
The work moved to xdg-desktop-portal-gnome so let's track it there
