### ISSUE TITLE
Add Portal for adding data outside ~/.var

### ISSUE THREAD

**Issue by JakobDev** [flatpak/xdg-desktop-portal#825]
Sometimes Apps needs to store Data outside it's directory in ~/.var for different reason. But Flatpak considers only the data in ~/.var as Data of the App. It would be nice, if you could add a Portal, which allows Apps to mark files or directories outside ~/.var as their data, so they also get deleted when running --delete-data.

**Comment by JakobDev** [comment]
I'm not talking about user dater. I'm talking about program data. e.g. the new DynamicLauncher portal does not allowing creating launchers on the Desktop. If a program wants the create launchers o the Desktop, it needs to write the .desktop files on it's own. This files are not removed with --delete-data of course. The requested portal can be used to mark such files as program data. While creating launcher on the Desktop will eventually be added in the future to the DynamicLauncher portal, there will be still more edge cases where programs are forced to create data files outside it's own directory.

**Comment by rusty-snake** [comment]
I see.

**Comment by GeorgesStavracas** [comment]
The Documents portal should cover this already
