### ISSUE TITLE
Proposal:  Add Clipboard Control to RemoteDesktop

### ISSUE THREAD

**Issue by maxhbooth** [flatpak/xdg-desktop-portal#843]
I am interested in adding clipboard control to the RemoteDesktop api.  There is a relevant discussion in #743 , where it suggests the RemoteDesktop might be a good place for this stuff to live. If there isn’t anyone working on something similar already, I’d be happy to submit a draft of it.  As an initial thought, I think we could elevate what already exists inside mutter’s RemoteDesktop api.  E.g. the following endpoints would be added:
    EnableClipboard
    DisableClipboard
    SetSelection
    SelectionWrite
    SelectionWriteDone
    SelectionRead
    SelectionOwnerChanged (signal)
    SelectionTransfer (signal)

Does anyone have any thoughts?

**Comment by jadahl** [comment]
One thing that comes to mind is, IMO it makes sense to allow the remote desktop portal to hook into the clipboard, but might be a good idea to split the API itself into a separate interface, that'll re-use the same `org.freedesktop.portal.Session` object - much like the RemoteDesktop and ScreenCast API share the same session. E.g. it could be a property sent via the CreateSession method on the remote desktop indicating that the application wants to integrate with the clipboard, and if allowed by the user, the session can be used together with a `org.freedesktop.portal.Clipboard` API.

It'd allow us to e.g. extend the `InputCapture` portal to deal with clipboard too, if that would ever be something we want, without needing to duplicate the API.
