### ISSUE TITLE
Extend persist/restore_token concept to RemoteDesktop

### ISSUE THREAD

**Issue by bjaraujo** [flatpak/xdg-desktop-portal#850]
File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.freedesktop.portal.Error.InvalidArgument: Remote desktop sessions cannot persist

It would be important to remotely access unattended machines.

**Comment by marler8997** [comment]
This would be a welcome addition to a "pair programming" application I work on.  It aims to make pair programming remotely as seamless as possible.  Having to give permission to our app each time the "host user" (the one sharing their screen) changes makes the transition less seamless.  Using a restore token means users could switch who is sharing their screen multiple times without having to ask the user for the same permissions each time.

**Comment by jadahl** [comment]
I'm currently looking into how it can be done. The idea I have now is to use the same restore token like API that ScreenCast has, but make it part of SelectDevices. When used with SelectDevices, it'd also restore the screen cast source, in addition to devices, and and store the permission/source data in a `remotedesktop` permission store table, in contrast to the `screencast` table.

**Comment by jadahl** [comment]
See https://github.com/flatpak/xdg-desktop-portal/pull/1004.
