### ISSUE TITLE
Post-release version bumping

### ISSUE THREAD

**Issue by GeorgesStavracas** [flatpak/xdg-desktop-portal#855]
I'd like to open for discussion a small (all things considered) change to xdg-desktop-portal releases. Currently we bump the project version at the release commit, which is generally okay, but has two annoying side effects:

 1. Current `main` is holding the development of 1.15.0, and yet it reports `1.14.1`. This is incorrect.
 2. Applications cannot depend on unreleased unstable snapshots

I'd like to start bumping the project version number right after cutting a release. The commit log would look like this:

```
release A → bump project version to B → [...] commits [...] → release B → bump project version to C →  ...
```

I think this should fix the pair of issues above. The project version numbers and the branching scheme would continue to be the same as they are today.

Admittedly, allowing external projects depend on unreleased versions is risky for these projects, which can be seen as a con of this proposal. But overall I don't think this is a problem - we can instruct projects with fixed release schedules to not depend on unreleased versions - and I think post-release version bumping would make things a bit more organized for xdg-desktop-portal.

CC @smcv @jadahl @TingPing @matthiasclasen

**Comment by GeorgesStavracas** [comment]
Sorry, I should have been clearer: the CC carpet-bombing is for you to :+1: or :-1: this proposal, and share your thoughts about it

**Comment by ebassi** [comment]
> Admittedly, allowing external projects depend on unreleased versions is risky for these projects, which can be seen as a con of this proposal.

It's way too late to bolt the doors: the horses have left the stable, found their way on a ship, and sailed halfway around the world. In other words: if you are developing free software, and you have reverse dependencies, some of those dependencies **will** inevitably depend on the bleeding edge code you just checked into the source revision control. This is **especially** true if those reverse dependencies are also the ones that are driving most feature work in your library/service.

At the end of the day, you only have two options:

- pre-release version bumps, followed by post-release version bumps—AKA the Cairo versioning scheme. Even micro version means "release archive", odd micro version means "revision control". You couple this with even minor version for stable releases, and odd minor version for development cycles. Additionally, you skip zero during development cycles; this leads to:
  - 1.1.1: first version in Git, opens the 1.1 development cycle
  - 1.1.2: first development snapshot of the 1.1 development cycle
  - 1.2.0: first stable release of the 1.2 stable cycle
  - 1.2.1: first version in Git, opens the 1.2 stable cycle
  - ...
- post-release version bump only. The code in source revision control is **always** going to have a higher version than the code you just released as a tarball.

In both cases, people will be able to choose whether to depend on a release archive or the bleeding edge. The former case is fairly standardised, but requires some work. The latter case is pretty simple, and just requires a single commit after a release is tagged.

**Comment by chergert** [comment]
Generally speaking, I'd just go for the `post-release` form because it is significantly less to mess up on accident.

**Comment by TingPing** [comment]
I'm in favor of the post-release bump as well. :+1:

**Comment by jadahl** [comment]
No objections to any post-release bumps from me.

**Comment by GeorgesStavracas** [comment]
Thanks everyone for sharing your thoughts, this seems uncontroversial then
