### ISSUE TITLE
Add previous-version: 5.72.1

### ISSUE THREAD

**Issue by Bmw397** [flatpak/xdg-desktop-portal#866]
Add previous-version: 5.72.1
Add new version: 5.73.0

**What kind of change does this PR introduce?**

I fixed the broken compatibility score badge.

**Did you add tests for your changes?**

I read the dependabot documentation.
In order to fix the existing broken badge, I applied dependabot's new method.
`https://api.dependabot.com/badges/compatibility_score?dependency-name=${name}&package-manager={package-manger}&previous-version=${previous}.1&new-version=${newversion}`
  - name: webpack
  - package-manger: npm_and_yarn
  - pervious: 5.72.1 (latest old version)
  - newversion: 5.73.0 (latest version)

**Does this PR introduce a breaking change?**

Nope

**What needs to be documented once your changes are merged?**

Nope

__Originally posted by @devinan in https://github.com/webpack/webpack/pull/16071__

**Comment by smcv** [comment]
I think you've mixed this up with a different project. xdg-desktop-portal's newest version number is 1.15.0. It has never had a version 5.

**Comment by hadess** [comment]
> I think you've mixed this up with a different project. xdg-desktop-portal's newest version number is 1.15.0. It has never had a version 5.

Same person that posted this:
https://github.com/flatpak/xdg-desktop-portal/pull/858

Might be time to ban them from the org (I don't have the rights).
