### ISSUE TITLE
Login screen freezes after sleep

### ISSUE THREAD

**Issue by Wambug** [flatpak/xdg-desktop-portal#888]
Login screen freezes after sleep or hibernationg
`
           PID: 1248 (xdg-desktop-por)
           UID: 973 (sddm)
           GID: 973 (sddm)
        Signal: 6 (ABRT)
     Timestamp: Thu 2022-09-22 16:58:49 EAT (40s ago)
  Command Line: /usr/lib/xdg-desktop-portal-kde
    Executable: /usr/lib/xdg-desktop-portal-kde
 Control Group: /user.slice/user-973.slice/user@973.service/session.slice/plasma-xdg-desktop-portal-kde.service
          Unit: user@973.service
     User Unit: plasma-xdg-desktop-portal-kde.service
         Slice: user-973.slice
     Owner UID: 973 (sddm)
       Boot ID: 45f8d53aa59c42e7bba85b54a46da84d
    Machine ID: 5cb90a56d6394fffbdb7a4884e62ca53
      Hostname: arch-steve
       Storage: /var/lib/systemd/coredump/core.xdg-desktop-por.973.45f8d53aa59c42e7bba85b54a46da84d.1248.1663855129000000.zst (inaccessible)
       Message: Process 1248 (xdg-desktop-por) of user 973 dumped core.
                
                Module linux-vdso.so.1 with build-id 470aeef6a3210409cf2b0582837c4c424c4c36f4
                Module libuuid.so.1 with build-id 9057a530e6b3b0e71f24602a0039c490c9a0b5a1
                Module libxcb-util.so.1 with build-id b1e4c01b388a3bd7a0a9ad384865b61f5f1d4a24
                Module libxkbcommon-x11.so.0 with build-id 90654f41d9fe91c74bef6672a8b57ab34418b27a
                Module libICE.so.6 with build-id a78252e65631a98d7935f1bca668c2fe1d6bbb53
                Module libSM.so.6 with build-id 66cef8ae9a7848679be78dd26fd47e05110d03b5
                Module libxcb-xinput.so.0 with build-id 409ee697e2b16243bf1fc6429e672f2359033388
                Module libxcb-xkb.so.1 with build-id bad7e1eb65df04a6b2d676a08f68844856edaace
                Module libxcb-xinerama.so.0 with build-id 5d2ab2683447d9bb7bcc49c058dfa06bcb65560d
                Module libxcb-xfixes.so.0 with build-id e231a68d00ee4cfa12a2c31e755a9e2c1e7be450
                Module libxcb-sync.so.1 with build-id 13025f6de23a271636ad321c77eda98801e62e8e
                Module libxcb-shape.so.0 with build-id f9aab9846b5e3523bd534f8a845f36a37d42b3fa
                Module libxcb-render.so.0 with build-id b1ca498d665807ab0ccdafbe8070853efd058173
                Module libxcb-render-util.so.0 with build-id 32609134bf1b73183d07a66f6bd65c94b4542460
                Module libxcb-randr.so.0 with build-id c914473ab7592ed5cf5c191200faaac1089c12ad
                Module libxcb-shm.so.0 with build-id 828fec4d856e2710e732ea8d92c3f250c807b1c2
                Module libxcb-image.so.0 with build-id 0e6feae23e34658646dbd63d11f899c92c5d3c79
                Module libxcb-icccm.so.4 with build-id 5eb9288df14c7f50af1e8db26c37e19d78bf0978
                Module libX11-xcb.so.1 with build-id f92352eae0a30aea89d11beb22367fa985288925
                Module libQt5XcbQpa.so.5 with build-id 22a26a78db099a7a86274c88f67252ec78b8cc41
                Module libqxcb.so with build-id 1fdbc58e0182862fe58a8b652b794def082a3ca0
                Module libdl.so.2 with build-id 414d1d630bc04818a150b9c73e4493f3395e8869
                Module libgmp.so.10 with build-id 26cec2ebe94cc5c4cb99e6988717347222b324fd
                Module libhogweed.so.6 with build-id 5c4a99ad0aabe13bd9b517f92ab339436a2bc1f2
                Module libnettle.so.8 with build-id 6a26cbe6819abc8c57668f80ca8c8160fd85e29e
                Module libunistring.so.2 with build-id 617dbf3d3d6f85d6556a7a036e23845e95490158
                Module libidn2.so.0 with build-id b16e7570b102789b13ff77289762dbfe3f8f46bc
                Module libbrotlienc.so.1 with build-id 74adbc62e4fbb5da9d37b5aa458471f4130862ff
                Module libp11-kit.so.0 with build-id cc372ea3c28c4d3dfc633b4d2e933c8584d2af16
                Module libbrotlicommon.so.1 with build-id acfd597a977c8087bb6184383daae2e828a9ce42
                Module libgpg-error.so.0 with build-id 4738b8a9478177c202cccd64e0eb65d3dea2bfae
                Module libresolv.so.2 with build-id ed3c4c5cad9fbf3f1efed876025e0dbbf80059af
                Module libkeyutils.so.1 with build-id ac405ddd17be10ce538da3211415ee50c8f8df79
                Module libkrb5support.so.0 with build-id 15f223925ef59dee4379ebbc0fcd14eda9ba81a2
                Module libcom_err.so.2 with build-id 3360a28740ffbbd5a5c0c21d09072445908707e5
                Module libk5crypto.so.3 with build-id cc77a742cb62447a53d98285b41558b8acd92866
                Module libkrb5.so.3 with build-id 371cc767dacb17cb42c9c44b88eebbed5ee9a756
                Module libpthread.so.0 with build-id 3954d7fd57fa4db438d0ccdd8e2c6f7cc97c2e46
                Module libusbmuxd-2.0.so.6 with build-id fd9f05e7f5b0da4e15972f75b61fd9b4b9f06dbe
                Module libtasn1.so.6 with build-id fa2f7a5bfbcda1481ab5875d5744730ea1be8fb1
                Module libgnutls.so.30 with build-id 509d52b11320a5492b06215b816e4f65d26c15d5
                Module libbrotlidec.so.1 with build-id 66c54e9301f7e102ecc1d88547e5f0e8a056fe22
                Module libexpat.so.1 with build-id 113bb5a3e9ad856801bfcfc029102c9bdc13d67e
                Module libogg.so.0 with build-id ca0cae30a809f10db1f16e54a23b4e5ff7b2c54c
                Module libvorbis.so.0 with build-id f4e086347f6c1a66eb73cfe13974a29bd39aabca
                Module libpcre.so.1 with build-id 10d377210d07112c78388fd15b6c25f2bf4110c4
                Module libicudata.so.71 with build-id 4fef196388e678deb881978139e125e20ee2d94d
                Module liblz4.so.1 with build-id 84ea95d811dad359e94e100ebe6a746294ffe8a7
                Module libgcrypt.so.20 with build-id 8bf3cb884124273640de797a3e77d86c98434ea4
                Module libcap.so.2 with build-id 1f87347b85b55db2f75a2ecea5cb45d846dc7093
                Module libblkid.so.1 with build-id fb2c5d3c17aac74758a3eb80a2bc1c16bcf183b1
                Module libgraphite2.so.3 with build-id ce58945ebb55b86d3a4e717b6eae29efc4720d8e
                Module libGLX.so.0 with build-id d2c37fb8ec3bc53c67c013b0c6ac63ec086c8883
                Module libGLdispatch.so.0 with build-id 7879a881271650eff97c35aff7a8674859c5ae94
                Module liblzma.so.5 with build-id d08f5868cd5adcc6b7c53bf1725aac65bd4539cd
                Module libbz2.so.1.0 with build-id 919597c477c9b2cb9cdbb7745ed6494ac0e6da60
                Module libXdmcp.so.6 with build-id d864159ab0008415667db8d5f251696d75c90df2
                Module libXau.so.6 with build-id d9d5e8277140f1a86d3a07d9b52b1703c0a2f9a8
                Module libcrypto.so.1.1 with build-id 7981ea3d69f3c28e46ee312a815af96eab93775c
                Module libssl.so.1.1 with build-id e6b1f97a5b60b4248c49dfc5b11f53f281b507d0
                Module libgssapi_krb5.so.2 with build-id 292f1ce32161c0ecc4a287bc8494d5d7c420a03f
                Module libplist-2.0.so.3 with build-id f16bdd42b3d750ba0a150d286248f5dc50cc76cb
                Module libimobiledevice-1.0.so.6 with build-id bc258677480403cc2df4f0efcfc97e06af826ddc
                Module libudev.so.1 with build-id 1f457961ef76f7611df7b6f687f645266cee359c
                Module libKF5GlobalAccel.so.5 with build-id dfc766d1818cc24b9e82d7dc6977bff57162e616
                Module libxkbcommon.so.0 with build-id 6cf66eead3fcc20fe5df10162bfbcdcdc8b2a183
                Module libfreetype.so.6 with build-id f89dd5502e75aca28fb5c3ccd0dbd26fe822bfef
                Module libfontconfig.so.1 with build-id 36be6951b8c1e42a7dd05684a37400fc8ef9147c
                Module libwayland-cursor.so.0 with build-id 46a637dbcbb02d6712a201f177377b66598b9121
                Module libXext.so.6 with build-id 17beadf1cb40d41ab36629db3b4eed74110678a7
                Module libltdl.so.7 with build-id 6a619e7b85ea9702e595881863bc9e599565e8a0
                Module libtdb.so.1 with build-id f2bdb5ac97b6addf2026d93b08c8d15defcd9bb8
                Module libvorbisfile.so.3 with build-id 45d2551167a616d448beb033ba49394831992887
                Module libglib-2.0.so.0 with build-id 898773b9f59cbaa435131f67db1ce0537d75647a
                Module libzstd.so.1 with build-id ab54c2881f53ab314e134f3e08c76d504376dd5d
                Module libpcre2-16.so.0 with build-id ffb3a35bbc7fad130db0847a339b151365293044
                Module libicuuc.so.71 with build-id 633fdc0c5385d916571f6140e7a978ad0630ef55
                Module libicui18n.so.71 with build-id 6fd5c97fd2808ee29958bf809656d5885e7e8963
                Module libdouble-conversion.so.3 with build-id 74bfa78f70f9ae1f759f0ae383fbc7f6f7faf6f8
                Module libsystemd.so.0 with build-id a664cbc6b724392704b96360284c40664d8d4c99
                Module libdbus-1.so.3 with build-id 7f4b16b4b407cbae2d7118d6f99610e29a18a56a
                Module libKF5DBusAddons.so.5 with build-id 5eb888d8927faddb8d56c8ff6a693e2cce655e5c
                Module ld-linux-x86-64.so.2 with build-id e7420ab1d031e8b3fa3a6916ae2fd0c3b58f6fdb
                Module libmount.so.1 with build-id 9064fc3620c42e6f7aed38119f0a3ec39fca9a37
                Module libacl.so.1 with build-id 27869ed0219ade5d2ffd50eaee11f967187faa8b
                Module libKF5AuthCore.so.5 with build-id da9ff08c6e52c1ef73cfb30a8c37201731c688fc
                Module libKF5Crash.so.5 with build-id 5ab2ca0fc5fa2dea833bb39525117bf40b85d137
                Module libmd4c.so.0 with build-id 2151dba72cdc9960097e6e960a58a2f03c8bb96e
                Module libharfbuzz.so.0 with build-id 0083e085bcb9cb3869e5cb05fbcd9736c41434ab
                Module libz.so.1 with build-id fefe3219a96d682ec98fcfb78866b8594298b5a2
                Module libpng16.so.16 with build-id 14d3b3cc9d61ec1b7c1f86bdf108218a99364945
                Module libGL.so.1 with build-id 6f65953140bc8a2aba47c9d492658dc61891393e
                Module libQt5QmlModels.so.5 with build-id 75ac4ba2a588a639d18be70e47f2b106930ac1a5
                Module libgcc_s.so.1 with build-id 85db482c4585a328d95ec41124337a967bb24d8f
                Module libKF5Archive.so.5 with build-id 819ae3371588dfb743e88c23a417bcbcc2a94694
                Module libQt5Svg.so.5 with build-id 7db0284946e4871e7f9effc797f1dee6b7cb1be6
                Module libxcb-keysyms.so.1 with build-id 507bdc94868b9b1f9d95e31c492694f2513da88d
                Module libxcb.so.1 with build-id 13d677412a71468381b11092915d231f664d18d3
                Module libm.so.6 with build-id 2c8ff1d29b255da5b7371efd5caf57444d622838
                Module libQt5Xml.so.5 with build-id f67bcabb5df91d3dd74fb54fd53421bcd089b9f4
                Module libKF5Codecs.so.5 with build-id bf96c60657188e783178682f28ba9db0ea507aa2
                Module libKF5WidgetsAddons.so.5 with build-id f0abc3bee1fad21ec45b3188ce079b852e2fee80
                Module libKF5GuiAddons.so.5 with build-id d02d92f5bdc155cea56f6c8a709ad60fa56b9317
                Module libKF5ConfigWidgets.so.5 with build-id 60a779885da8389a2d94e258c09a9877b10c4b23
                Module libQt5Network.so.5 with build-id 4ef4fd4a75511783248e62c378fe446cfa4ccc91
                Module libKF5Completion.so.5 with build-id 0b50881b27f40a463706296b458b6f68c99f672d
                Module libKF5JobWidgets.so.5 with build-id 58ac1e987656afcbecf92a8400a13f4dbd458a92
                Module libKF5KIOGui.so.5 with build-id 15fb3141a045d1d4c63535c25cebe7332ee72efe
                Module libKF5Solid.so.5 with build-id e74245c3a71b508d6d27dd5c30fef851c784d4ae
                Module libKF5XmlGui.so.5 with build-id 12dbceba1d2c8b4024175f04c32c7ce59921c767
                Module libKF5Bookmarks.so.5 with build-id 6008e6c2825cba8cea47c90aa66622d0c7006a57
                Module libffi.so.8 with build-id f0a9586cf0f42d2b9971bd1065ca3a6b19f4a2c2
                Module libQt5WaylandClient.so.5 with build-id 75b26fc27cfb228e7ec777cc9528d3f8ab61bfb9
                Module libdbusmenu-qt5.so.2 with build-id 346cd54093968d3de9e61cc329e9512d248dce18
                Module libXtst.so.6 with build-id 35c7f3daf454834acb724e6bd1664b0a2e9a6494
                Module libQt5X11Extras.so.5 with build-id 78547956b3be2e12eece7fa5e9fa9f161b022c50
                Module libX11.so.6 with build-id 21e886e968772b7964d646f54c1faecc56734de9
                Module libQt5TextToSpeech.so.5 with build-id 593099f8617753c871f48e5951f368c3a863e1cf
                Module libcanberra.so.0 with build-id 8ddef69c9b84a86062c88a59510639cd908fc6d3
                Module libc.so.6 with build-id 26c81e7e05ebaf40bac3523b7d76be0cd71fad82
                Module libstdc++.so.6 with build-id 735a3d0cc7699fd69337361cba4aedb644b2a7ed
                Module libQt5Core.so.5 with build-id 10f403c84cef570e5302c7b1f0d8db34f8293f71
                Module libQt5DBus.so.5 with build-id 80839ec0184277ea0382ce3fdc7f84eaebb4dff9
                Module libKF5CoreAddons.so.5 with build-id 0c1e61a987dcc5a413145ce6f4b3e9130d478885
                Module libKF5I18n.so.5 with build-id 8b01b131521ee05f8dd1cdc649e8989a403f89e2
                Module libKF5ConfigCore.so.5 with build-id 3a7aadabb9f7166cacb72f765b328e10c66fbfa8
                Module libKF5Service.so.5 with build-id 9aa3259c2748aaa0c6bb8ad3a2d2a5c2a12264d5
                Module libKF5KIOCore.so.5 with build-id 259587c6684343e9bd0ea1b998e84d57033cad09
                Module libQt5Qml.so.5 with build-id 22231cfcf29a284259109c7862fb6e72406b131a
                Module libQt5Gui.so.5 with build-id c3306c1f059a4d83b3ece5ca28ce2a147fc154e3
                Module libQt5Quick.so.5 with build-id 7943b27c49d44215357f6219398a7b376dcf4cbd
                Module libQt5Widgets.so.5 with build-id 7948b4cf67a2e204665689ba69adedcb6ec9f7e7
                Module libKF5ConfigGui.so.5 with build-id 7ceed534598952ecd8bf33ad51b7d0b6db177d07
                Module libKF5ItemViews.so.5 with build-id 056d51112983ee6da4ebeab5da319f58b3543f3f
                Module libQt5PrintSupport.so.5 with build-id c2adb3cc1c1891fbd2099b4285dc59e045edfe1c
                Module libKF5IconThemes.so.5 with build-id 4df7a5f6480a88fd05d6643cdf07638b2c76d4cc
                Module libKF5WindowSystem.so.5 with build-id afc9a1c136b0d640c853e1f451c15bcda90d0575
                Module libKF5KIOWidgets.so.5 with build-id 7c732f0ef6ac9a794468dd6562bcb4fe50bc60fe
                Module libKF5KIOFileWidgets.so.5 with build-id 65786d4c4e326b7284b114c610ddbaf28610c974
                Module libwayland-client.so.0 with build-id 515c72111400d7bdbfbdfcec78d597e4986a5943
                Module libKF5WaylandClient.so.5 with build-id a0342fd911091e14da427e9f7a9afe17f45367b8
                Module libKF5Notifications.so.5 with build-id b80091b385d6d74d1492928b2c465a0bc6822772
                Module xdg-desktop-portal-kde with build-id 27e57ac12655c1d88c4f219fb1d0fa5d2f87403c
                Stack trace of thread 1248:
                #0  0x00007fd00896c49c n/a (libc.so.6 + 0x8849c)
                #1  0x00007fd00891c958 raise (libc.so.6 + 0x38958)
                #2  0x00007fd00890653d abort (libc.so.6 + 0x2253d)
                #3  0x00007fd008da1ede _ZNK14QMessageLogger5fatalEPKcz (libQt5Core.so.5 + 0x9fede)
                #4  0x00007fd009b34aa5 _ZN22QGuiApplicationPrivate25createPlatformIntegrationEv (libQt5Gui.so.5 + 0x13caa5)
                #5  0x00007fd009b35109 _ZN22QGuiApplicationPrivate21createEventDispatcherEv (libQt5Gui.so.5 + 0x13d109)
                #6  0x00007fd008f941ab _ZN23QCoreApplicationPrivate4initEv (libQt5Core.so.5 + 0x2921ab)
                #7  0x00007fd009b351b9 _ZN22QGuiApplicationPrivate4initEv (libQt5Gui.so.5 + 0x13d1b9)
                #8  0x00007fd00a711e0e _ZN19QApplicationPrivate4initEv (libQt5Widgets.so.5 + 0x175e0e)
                #9  0x000055894971a0c6 n/a (xdg-desktop-portal-kde + 0x1e0c6)
                #10 0x00007fd008907290 n/a (libc.so.6 + 0x23290)
                #11 0x00007fd00890734a __libc_start_main (libc.so.6 + 0x2334a)
                #12 0x000055894971b535 n/a (xdg-desktop-portal-kde + 0x1f535)
                
                Stack trace of thread 1311:
                #0  0x00007fd0089dee5f __poll (libc.so.6 + 0xfae5f)
                #1  0x00007fd007291ddf n/a (libglib-2.0.so.0 + 0xaaddf)
                #2  0x00007fd007239252 g_main_context_iteration (libglib-2.0.so.0 + 0x52252)
                #3  0x00007fd008fd950c _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2d750c)
                #4  0x00007fd008f8732c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x28532c)
                #5  0x00007fd008de949f _ZN7QThread4execEv (libQt5Core.so.5 + 0xe749f)
                #6  0x00007fd009246cba n/a (libQt5DBus.so.5 + 0x23cba)
                #7  0x00007fd008de62ba n/a (libQt5Core.so.5 + 0xe42ba)
                #8  0x00007fd00896a74d n/a (libc.so.6 + 0x8674d)
                #9  0x00007fd0089ec700 n/a (libc.so.6 + 0x108700)
                ELF object binary architecture: AMD x86-64

`

**Comment by smcv** [comment]
This is an assertion failure in xdg-desktop-portal-kde, which is [a separate project](https://invent.kde.org/plasma/xdg-desktop-portal-kde/). Please report it to the KDE developers or your OS distributor.

xdg-desktop-portal-kde bugs seem to be tracked in [KDE Bugzilla](https://bugs.kde.org/buglist.cgi?bug_status=__open__&component=general&product=xdg-desktop-portal-kde).
