### ISSUE TITLE
Failed to get application states

### ISSUE THREAD

**Issue by thiagovespa** [flatpak/xdg-desktop-portal#891]
When I start the xdg-desktop-portal:

`systemctl --user start xdg-desktop-portal{,-gtk}`

I got this message:

`xdg-desktop-por[3030]: Failed to get application states: GDBus.Error:org.freedesktop.portal.Error.Failed: Could not get window list`

I'm using xfce4 but I have gtk applications.

**Comment by thiagovespa** [comment]
Package versions: 
[xdg-desktop-portal 1.14.6](https://packages.gentoo.org/packages/sys-apps/xdg-desktop-portal)
[xfce-desktop 4.16.0](https://packages.gentoo.org/packages/xfce-base/xfdesktop)
[gtk 4.6.7](https://packages.gentoo.org/packages/gui-libs/gtk)

**Comment by Mikenux** [comment]
Do you have `xdg-desktop-portal-gtk` installed?

**Comment by GeorgesStavracas** [comment]
XFCE does not provide any implementation for window listing, and `xdg-desktop-portal-gtk` does not have XFCE-specific knowledge to do that. The path forward is for XFCE developers to provide `xdg-desktop-portal-xfce` which would use XFCE-specific APIs to provide that.
