### ISSUE TITLE
Improve background apps

### ISSUE THREAD

**Issue by GeorgesStavracas** [flatpak/xdg-desktop-portal#899]
After a long series of discussions on how to improve the handling of background apps, some consensus was reached, and parts of it involve xdg-desktop-portal.

The primary responsibility of xdg-desktop-portal is to determine which applications are considered to be running in background. Currently, this is done through the following steps:

 * x-d-p lists which Flatpak instances are running (let's call it I)
 * x-d-p asks backends for a list of running apps (let's call it R)
 * x-d-p determines that background apps B = I - (I ∩ R)

With that, x-d-p goes ahead and notified the backend about new background apps. The backend potentially shows an UI, and if the user denies that app the permission to run in background, x-d-p kills the application.

While this works, there are a few problems in this approach:

 1. At any point, there is no public, canonical list of background apps. It makes it impossible for backends to list these background apps anywhere in the UI.
 2. The GNOME backend, in particular, shows a notification that is both annoying and not very helpful. Without (1), it's all it can do.

In order to improve this situation, we agreed on the following changes:

 * [x] Stop interacting with the Access portal when apps call `RequestBackground()`
 * [x] Expose the list of background applications
   * [x] It must be in a separate D-Bus connection, we must not leak it to Flatpak sandboxes
 * [x] Add a new `SetStatus()` method to the Background portal
 * [x] Re-evaluate the frequency and heuristics used to poll background apps
 * [x] Notify backends about these changes

**Comment by sophie-h** [comment]
Short question about daemons/monitors: Does "list of background applications" mean that a second process started in the Flatpak is treated as part of the original app?

**Comment by hadess** [comment]
I'll need to review this more next week, but can we allowlist flatpak-builder, and can we find a way to also allowlist debug sessions started with, say, `--command=bash`?

**Comment by GeorgesStavracas** [comment]
The only limit is how many PRs people can open for these QoL improvements. There's plenty on my plate already, but PRs are opened for that, I'll be happy to land.

**Comment by sophie-h** [comment]
I tried to summarize the current approach and a bunch of questions I have. Hope that's okay.

- Every app can just run in the background by default.
- Every app can just activate autostart by default.
- Autostart and 'run in background' can both be disabled and re-enabled in Settings.
- For the re-enabling autostart to work, the portal stores the last autostart instructions on the drive.
- We have a background app list that shells can use.

1. Should we maybe add the simple state description, which is shown in the background app list mockups, as a new function to the background portal?
2. Would it make sense if apps could notify the portal if they go into background or return to get rid of a potential detection delay by portal? Or is it possible to update it once per second or more often?
3. Do we have a way also to list non-Flatpaked apps in the list of background apps? If not, could we trigger listing them if they 'register' via the background portal?
4. We have a reason for 'run in background' that the app gives. If there are no dialogs anymore, we could show it in the app settings in the context of enabling/disabling the 'run in background.' If that's not wanted, we should think about adding a background portal function that does not require a reason. (I will also add this to designer questions)
5. It would make sense to treat 'autostart' more like a service. For example, starting the background process when autostart is enabled again in the settings. However, I see too many practical problems.

**Comment by GeorgesStavracas** [comment]
> * Should we maybe add the simple state description, which is shown in the background app list mockups, as a new function to the background portal? _Probably the `SetStatus()` mentioned above._

https://github.com/flatpak/xdg-desktop-portal/pull/901 adds that.

> * Would it make sense if apps could notify the portal if they go into background or return to get rid of a potential detection delay by portal? Or is it possible to update it once per second or more often?

https://github.com/flatpak/xdg-desktop-portal/pull/901 does that.

> * Do we have a way also to list non-Flatpaked apps in the list of background apps? If not, could we trigger listing them if they 'register' via the background portal?

No, and it's not going to happen. Unsandboxed apps are outside of our control. There's no real concept of "application" that we can map to without a sandbox, there's just an unassorted list of random processes.

> * We have a reason for 'run in background' that the app gives. If there are no dialogs anymore, we could show it in the app settings in the context of enabling/disabling the 'run in background.' If that's not wanted, we should think about adding a background portal function that does not require a reason. (I will also add this to designer questions)

Yeah, this is a question for designers. The mechanisms are in place.

> * It would make sense to treat 'autostart' more like a service. For example, starting the background process when autostart is enabled again in the settings. However, I see too many practical problems.

There is no standard way to spawn an application as a service, so as you point out, we cannot currently "just" bind background running to autostart. Furthermore, I can think of Amberol as an example of an app that may want to run in background, but not be autostarted. So this is a bit out of reach now.

**Comment by swick** [comment]
> No, and it's not going to happen. Unsandboxed apps are outside of our control. There's no real concept of "application" that we can map to without a sandbox, there's just an unassorted list of random processes.

Most of the time apps are still started in a cgroup adhering to the xdg/systemd standard. This seems possible. The question is if it is worth investing time in.

**Comment by GeorgesStavracas** [comment]
I'm *very* skeptical that that's possible, much less that unsandboxed apps can't lie about who they are, but if you think that's possible, you can make your point with code :)

**Comment by swick** [comment]
Oh they can definitely manage to avoid whatever we're trying to enforce but a well-behaving non-sandboxed app which is running in the background could still be shown in the "background apps" UI.

> you can make your point with code :)

Like I said, not sure if it's worth investing time into. Maybe some day :)

**Comment by GeorgesStavracas** [comment]
With https://github.com/flatpak/xdg-desktop-portal/pull/901, the portal side of this has landed. Further improvements should be handled by the respective backend / DE.
