### ISSUE TITLE
add an os information portal

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/xdg-desktop-portal#90]
It would be nice if apps could display basic OS information like name and version in their about dialog.

The kind of information that is normally found in /etc/os-release

**Comment by mariospr** [comment]
Sounds like an useful addition to me, it could be something like a `org.freedesktop.portal.OS` interface with maybe one single `GetOSInformation` method that would return a `G_VARIANT_TYPE_VARDICT` with only the name and the version of the OS for now, when available.

Other option would be to pass flags to the GetOSInformation method to specify what information we'd want to get (something similar to the `attributes` parameter in `g_file_query_info()`), but I get the feeling that it might be a bit too overkill and that simply returning a `a{sv}` here would suit it best.

@matthiasclasen What do you think? Would this be something matching what you have in mind?

**Comment by matthiasclasen** [comment]
sure, just look at org.freedesktop.portal.Account for comparison

**Comment by hadess** [comment]
Why is this useful for applications? For bug reporting, the user should be able to gather information manually. This feature would only serve as a way to leak patch level information (and thus security hole information) about the system, and showing the information would likely need a dialogue to show another dialogue.

**Comment by matthiasclasen** [comment]
You said the same thing when I first added the system tab. I think we will just to agree to disagree about this being a useful thing in applications.

I don't think "Fedora 26 (Workstation)" is exposing patch level information, really.

This may be a case where we would allow-by-default and have control center ui to turn it off per-application, instead of showing a dialog at request time.

**Comment by hadess** [comment]
> You said the same thing when I first added the system tab. I think we will just to agree to disagree about this being a useful thing in applications.

I still don't think it's useful to applications.

> I don't think "Fedora 26 (Workstation)" is exposing patch level information, really.

Yes it does, for 0-day security issues. What about if the system has patch levels in `/etc/os-release`? What about if the OS release is the unsupported-with-no-security-issues kind?

> This may be a case where we would allow-by-default and have control center ui to turn it off per-application, instead of showing a dialog at request time.

If I have anything to do with it, it would be disabled by default.

**Comment by matthiasclasen** [comment]
One of the guiding principles of flatpak has been to have apps integrate in all the expected ways. If it is expected outside the sandbox that an app might want to show e.g. a logo of the host system, then the same thing should be possible inside, with the user being in control.

**Comment by hadess** [comment]
Again, why would the application need to do this? I can't think of any non-system application that would need to know the version of the OS they're running on. Would be glad to read a list of those use cases.

**Comment by smcv** [comment]
I would have expected that if anything, the application would show the version of Flatpak or the version of the runtime that it's running on?

**Comment by matthiasclasen** [comment]
It does show both of those. And maybe that is enough. Maybe the version of the portal service would be useful too.
