### ISSUE TITLE
Replace UseIn with more descriptive declarative keys

### ISSUE THREAD

**Issue by ebassi** [flatpak/xdg-desktop-portal#906]
The backend to use is chosen on a per-interface basis, so it is OK to split functionality between backends. For example, it's fine to choose `foo.portal` for `o.fd.impl.portal.One` and `bar.portal` for `o.fd.impl.portal.Two`.

GNOME is a concrete example of this: GNOME-appropriate behaviour for various interfaces is distributed between x-d-p-gnome (`gnome.portal`), x-d-p-gtk (`gtk.portal`), gnome-shell (`gnome-shell.portal`) and gnome-keyring (`gnome-keyring.portal`).

The current priority/fallback behaviour is:

* First, x-d-p enumerates all portals whose `.portal` file declares that they are suitable for the `$XDG_CURRENT_DESKTOP` via the `UseIn` field.
* If this results in only finding one implementation of an interface, it is used, and we stop here: for example, in a GNOME environment, the only implementation of `o.fd.impl.portal.Secret` is `gnome-keyring.portal`.
* If this results in finding more than one implementation of an interface, the first one in lexicographic order is used, and we stop here.
    * For GNOME users, this happens to do the right thing for `x-d-p-gtk` vs. `x-d-p-gnome`, because `gnome` happens to sort lexicographically lower than `gtk`, but that's more like a lucky accident than by design.
    * For users of non-GNOME GTK-based desktop environments like XFCE, this does not necessarily do the right thing: if `x-d-p-gtk` and `x-d-p-gnome` are both installed, maybe XFCE users would prefer to use `-gtk`? (Although arguably that should be solved by having `UseIn=GNOME;XFCE;etc.;` in `-gtk`.)
* If this results in finding *no* implementations of an interface, then the fallback is to ignore the `UseIn` field, and enumerate all portals indiscriminately. Again, the first one in lexicographic order is used.
* If there are still no portals found, then x-d-p does not implement the interface.

This is not ideal. Ideally, we would be able to distinguish between:

* implementations that *can be* used from any desktop environment, but are less ideal in some desktop environments
    * for example, a GTK `FileChooser` is primarily for use with GTK-based desktops like GNOME, MATE, Cinnamon, LXDE and XFCE; it will look out-of-place in a Qt-based desktop, so ideally in a Qt-based desktop like LXQT, we would use something provided by the desktop instead; but it will still *work* fine in any desktop environment, so it's always better than nothing, and we can safely use it as a fallback
* implementations that can only function on some desktop environments, and will fail on others
    * for example, when x-d-p-gtk implements `o.fd.impl.portal.ScreenCast`, it is relying on mutter APIs, so it can work on GNOME Shell and on Budgie, but will not work at all on (for example) Mate, Cinnamon, GNOME Flashback, LXDE or XFCE

_Originally posted by @smcv in https://github.com/flatpak/xdg-desktop-portal/issues/656#issuecomment-966276573_

**Comment by ebassi** [comment]
A rough straw man proposal:

To solve the first issue and avoid the lexicographic ordering:

- Add `PreferredIn`
  - lists all the environments where a portal should be preferred
- Add `FallbackIn`
  - lists all the environments where a portal should be used as a fallback

xdg-desktop-portal will enumerate all `.portal` implementations and will prefer the ones with `PreferredIn`; if there is no preferred portal, it will use the portal with a `FallbackIn` for the current desktop.

Example:

xdp-gnome:

```
PreferredIn=GNOME;
```

xdp-gtk:

```
FallbackIn=GNOME;XFCE;MATE;
```

This will allow XFCE and/or MATE to create their own portals in the future, if they so choose, with xdp falling back to GTK.

The `UseIn` key would set both `PreferredIn` and `FallbackIn` as a deprecation mechanism. If `UsedIn` is present alongside either `PreferredIn` or `FallbackIn`, then it is ignored.

To solve the issue of implementations of specific interfaces being available only on certain environments we'll have to add a whole new group to the key file. For instance, the xdp-gtk portal could add:

```
[portal org.freedesktop.impl.portal.ScreenCast]
OnlyIn=GNOME;Budgie;
```

xdp would check for a `portal $interface` group and only allow the implementation if it matches the environment in the `OnlyIn` key.

**Comment by Sodivad** [comment]
Oh I made patch recently (but didn't open a MR yet, actually I was just about to do when I saw this issue) that's similar to your idea but goes for a somewhat simpler approach. I just added a  new key `ExclusiveInterfaces` with the purpose to list interfaces that only work in the environments listed in `UseIn`, while the `Interfaces` would signify Interfaces that can be used as fallback. This way backwards compatibility is handled implicitly for older implementations.

I see the flexibility of your prpoposals but I think both problems can be solved simultaneously. 
For example I am not 100% convinced that per-interface granularity is needed. I think it's fair to assume that every interface that a implementation supports in the desktop environment it belongs to. 
On the matter of `PreferredIn` and `FallbackIn` and I can somewhat see it but also not fully convinced, it would already be used as Fallback on XFCE and MATE with my approach and once they add their own portal they would just add their additional/overwritten interfaces to `ExclusiveInterfaces`

**Comment by ebassi** [comment]
> For example I am not 100% convinced that per-interface granularity is needed. I think it's fair to assume that every interface that a implementation supports in the desktop environment it belongs to.

That's not the case for the ScreenCast interface, as explained by Simon: the interface implementation in the GTK portal works only in a couple of environments based on Mutter (since there's where the screencast functionality resides). We have desktop environments based on shared components, which makes a simple interface check isn't enough to support.

The main issue is that while there is definitely a case for simplicity, the existing environments do require some more complexity.

**Comment by smcv** [comment]
> I think it's fair to assume that every interface that a implementation supports in the desktop environment it belongs to

I suspect that `x-d-p-gnome` has some interfaces that are frontends for libmutter or gnome-settings-daemon features (equally applicable in Budgie), and some that are frontends for GNOME Shell features (genuinely GNOME-specific).

Another approach to this might be for all interfaces (or the ones affected by this in practice) to be able to fail initialization gracefully, so that x-d-p can call into x-d-p-gnome, ask "I know you say you implement Screenshot, but do you *really* implement Screenshot?", get a response immediately, and if the response is "no", either fall back to a different implementation or refrain from advertising the interface to apps.

But that would require more async calls (=> more code complexity) in x-d-p, so what @ebassi proposed might be more feasible to get implemented correctly in a finite time, and it's certainly an improvement over what we have right now.

**Comment by ebassi** [comment]
I did consider a run-time approach like that, but even if we asked every portal implementation for the supported interfaces and cached the results, it would indeed require querying a bunch of services and waiting for a reply. The case of multiple portal implementations is small enough to still allow a static list of capabilities.

**Comment by hadess** [comment]
Probably a bad idea, but you could ask each desktop to ship the list of portals they need in a configuration file of some sort, and remove all the runtime checks. The desktops themselves would ship this. This would be similar to how mime defaults are shipped:
```sh
$ rpm -qf /usr/share/applications/gnome-mimeapps.list
gnome-desktop3-43-1.fc37.x86_64
```

That would move the checks from runtime to package-build time, and make it the distribution's problem if it wasn't properly setup.

**Comment by smcv** [comment]
> you could ask each desktop to ship the list of portals they need

That's not going to work for the "I build my own desktop environment from fvwm and duct tape" use-case, for which we have to fall back to *something*, in practice `x-d-p-gtk` (which is the closest thing we have to a reference implementation of portal backends). It's also not going to work for the long tail of less-well-maintained desktop environments that take a few years to catch up with any "new" thing, for which, again, `x-d-p-gtk` is the fallback in practice.

**Comment by Sodivad** [comment]
Thanks for the examples, not coming from that corner of things I was not aware of all of that in detail and see that per-interface is indeed useful and brings much flexibility. (I was about to type out something that maybe the split between `x-d-p-gtk` and  `x-d-p-gnome` is not entirely correct  and if `x-d-p-gtk` is supposed to be a fallback but not fallbacking everywhere and or supporting only one session is doing it a bit weird, but I understand it's historical and we  can't change it now.)

Then the question is do we need `PreferredIn` and `FallbackIn`. I think maybe not? If `x-d-p-gtk` is installed it would be already used as fallback and with the Interfaces that work only in GNOME (or Budgie) being annotated it would be no trouble on some other desktop. 
Or is it more about preferring `x-d-p-gnome` on Gnome over `x-d-p-gtk`? Maybe the correct thing would be to drop `UseIn=Gnome` from `x-d-p-gtk` instead, in a Gnome session you would have `x-d-p-gnome` installed anyways and on other desktops (including DuctTapeDE) makes no difference.

**Comment by hadess** [comment]
> That's not going to work for the "I build my own desktop environment from fvwm and duct tape" use-case, for which we have to fall back to _something_, in practice `x-d-p-gtk` (which is the closest thing we have to a reference implementation of portal backends). It's also not going to work for the long tail of less-well-maintained desktop environments that take a few years to catch up with any "new" thing, for which, again, `x-d-p-gtk` is the fallback in practice.

So, like for mime defaults:
```sh
$ rpm -qf /usr/share/applications/mimeapps.list 
shared-mime-info-2.2-2.fc37.x86_64
```

Ship the default in `xdg-desktop-portal` and make it possible to override with `~/.config/x-d-p/config.ini`. That takes care of the less-well-maintained desktop as well as the fvwm+duct tape cases.

**Comment by smcv** [comment]
> Maybe the correct thing would be to drop UseIn=Gnome from x-d-p-gtk instead

The problem with that is that not everything in x-d-p-gtk is equal. Some of x-d-p-gtk is correct for any GTK-based environment (including GNOME) and doesn't have a reimplementation in x-d-p-gnome, so we do want it to be `UseIn=Gnome` (among others) so that it's preferred over x-d-p-kde or whatever.

Some of x-d-p-gtk is correct for any GTK-based environment but has a better/nicer/more-modern UI in x-d-p-gnome, so we want the -gnome implementation to be preferred for GNOME users, where there is overlap.

Some of x-d-p-gtk is actually GNOME-specific (or libmutter-specific) but is kept for historical reasons, although distros can disable these parts if they have done the migration from x-d-p-gtk to x-d-p-gnome (for instance in Debian 12, most of the GNOME-specific parts of x-d-p-gtk are disabled; but in the backports of recent x-d-p-gtk to Debian 11, they're re-enabled, since Debian 11 was too old to have a separate x-d-p-gnome).

**Comment by Sodivad** [comment]
I think  the main point then that we want to specify a specific fallback on multiple environments while not overriding their own portal if they have one or create one in the future.

I feel that @hadess is on the right track, that it is something that the desktop environments should control themselves.
They can do that currently by creating their own portal with matching `UseIn` somewhat but others are out of luck.
This would remove the burden from x-d-p-gtk to list everyone that would want to use it in `FallbackIn`, and if one project changes their decision having to rely on releases of that.

**Comment by smcv** [comment]
If I understand correctly, the big advantage of what @hadess suggested is that if the maintainers of Budgie find that the ScreenCast part of `x-d-p-gnome` actually happens to work fine on Budgie, they can set it up in `budgie-portals.conf` without having to ask permission from the maintainers of `x-d-p-gnome`. I can see that that's helpful.

But then if the implementation of `x-d-p-gnome` changes, and it becomes genuinely GNOME-specific (perhaps it stops using a libmutter-generic API and starts using a GNOME Shell API), the overall system becomes broken; so there still needs to be coordination between the maintainers of `x-d-p-gnome` and Budgie, if not upstream then at least within each downstream distribution that ships both.

**Comment by smcv** [comment]
I can see the parallel with MIME types, but for MIME type defaults, we're mostly dealing with "this implementation is nicer/more visually consistent on GNOME". Some portals *are* like that (notably AppChooser and FileChooser); but some are more like "this implementation literally only works on GNOME and maybe Budgie", and I'd say that's very rare for MIME handlers.

**Comment by hadess** [comment]
> This seems like it has potential; but as I wrote out that semi-realistic example, my thought was that it seemed quite "inside out". The maintainers of the generic (!) and desktop-specific configuration need to know things about the implementation of specific backends, like the fact that `Account` is non-desktop-specific but `ScreenCast` hooks into the compositor.

The maintainers of the desktop _in distributions_ would need to know the implementation of specific backends. They will be the ones responsible for shipping the aggregated work.

About this one:
```
# /usr/share/xdg-desktop-portal/gnome-portals.conf
# mutter-specific
org.freedesktop.impl.portal.ScreenCast=gnome;gtk;
```
why would one need to fallback from gnome to gtk? If the distribution ships the `gnome` portal, why would they need to fallback?

**Comment by ebassi** [comment]
If the default MIME applications configuration has taught us anything is that downstreams are extremely picky when it comes to shipping configuration that is predicated on choices that have to be made by downstream themselves. Arch is still not shipping a default list of MIME handlers, for instance. I'm always wary of deferring choice to general purpose distributions shipping a bajillion desktops, because they can always legitimately turn around and say: "we can't make a decision when we're shipping the entirety of free and open source software".

I maintain that keeping the defaults near the portals that implement them is a better option. Having some sort of additional configuration in the typical user → site → upstream fallback fashion might be a good idea, in any case.

**Comment by ebassi** [comment]
> And not have to go to `xdg-desktop-portals-gtk` or gnome and have to add themselves to the list there and be on the mercy of the maintainers there to get it merged and released, which most likely happens on a different schedule.

The desktop environments are usually the ones maintaining the portals, outside of the "shared" ones, like xdp-gtk, which are still mainly maintained by the people working on those desktops.

As I said, I don't have an issue with upstream configuring things; my concept of "upstream" mainly refers to the portals themselves. On the other hand, I'm not convinced downstream distributors should be involved, because that way lies making choices that some downstreams are happy to make, and some aren't, and that would lead to bad user experiences and recriminations.

**Comment by hadess** [comment]
I mentioned distributions because there's obviously a packaging side to this problem. You can't ship a portal configuration that requires the "fvwm" portal and not require it as a dependency of that "desktop" environment. But as you mentioned, desktops would the ones shipping those files in the first place.

I think that static configurations would avoid having to create complicated protocols with fallbacks to check for features, especially when some of those checks might be done on desktop startup, and make sure that the combinations that are of interest are tested. This also avoids `xdg-desktop-portal` upstream from having to maintain a list that list on its own, and makes selection problems more straight forward and easier to debug. Finally, it gives an escape hatch for the niche desktops that want to be able to implement all or part of the portals without `xdg-desktop-portal` having to get involved.

**Comment by ebassi** [comment]
So, after going through a couple of iterations, I think @hadess proposal coupled with @smcv comments is probably the best course of action:

- deprecate `UseIn` inside the portal definition file; portal definition files are only used to list the interfaces implemented by a portal
- add a `$DESKTOP-portals.conf` file that is defined to contain the list of portal interfaces and their corresponding portal implementation to be preferred by a desktop environment (as defined by `$XDG_CURRENT_DESKTOP`)
- add a `portals.conf` file that can be used to define custom fallbacks for Build-Your-Own-Desktop environments

The format for the configuration file is a plain key/value file, with each key being the portal interface, and the value a string list with the list of portals to be used, in sequence as a fallback chain.

The special key `default` is used to define the default fallback chain.

The example for GNOME would be a `gnome-portals.conf` file:

```
[portals]
default=gnome;
```

The example for MATE would be `mate-portals.conf`:

```
[portals]
default=gtk;
org.freedesktop.portals.ScreenCast=none;
org.freedesktop.portals.Screenshot=none;
```

The example for Budgie would be `budgie-portals.conf`:

```
[portals]
default=gtk;
org.freedesktop.portals.ScreenCast=gnome;gtk;
```

The special values `none` and `*` can be used:

- `none`: no portal implementation should be used for a given interface
- `*`: use the first portal implementation in the existing lexicographical order

I'm going to open a merge request implementing the outlined behaviour.

**Comment by ebassi** [comment]
The #955 pull request was merged in the main development branch.
