### ISSUE TITLE
file transfer does not handle folders

### ISSUE THREAD

**Issue by matthiasclasen** [flatpak/xdg-desktop-portal#911]
This was reported here: https://gitlab.gnome.org/GNOME/gtk/-/issues/5348

The underlying issue is that AddFiles validates the fds by passing VALIDATE_FD_FILE_TYPE_REGULAR to validate_fd().

I think we should probably add an AddFolders method to the DBus interface.

**Comment by matthiasclasen** [comment]
Alternatively, we could invent some way to validate the fds as 'either regular or folder'

**Comment by CaptainMorgan12** [comment]
this function would be amazing!

**Comment by ebassi** [comment]
Picking this up.

**Comment by ebassi** [comment]
I've played a bit with the idea of adding an `AddFolders` method, which is trivial on the portal side, but gets messy on the toolkit/application side. Aside from the duplication of code paths, it gets "funny" once you start accumulating file descriptors to send over the wire: it means you cannot interleave `AddFiles` and `AddFolders` calls, which is hard to detect on the portal side.

**Comment by ebassi** [comment]
An easier option is to use `VALIDATE_FD_FILE_TYPE_ANY` inside the file transfer portal, which will validate both files and directories; the document portal already supports this, so it should be fine.

**Comment by hfiguiere** [comment]
See #1196
