### ISSUE TITLE
Support buffer negotiation / gpu buffer capture?

### ISSUE THREAD

**Issue by Peque** [flatpak/xdg-desktop-portal#919]
Apparenty [OBS does not currently support NVIDIA on Wayland](https://github.com/obsproject/obs-studio/issues/7866). They claim they cannot do anything since it only depends on other projects:

> to our knowledge no xdg-desktop-portal implementation actually supports proper buffer negotiation (some pending changes for xdg-desktop-portal-gnome and mutter resulted in proper capture, but i have not followed their acceptance or rejection from those projects). So there is nothing we can track here. If you feel things should work please file a bug against your compositor's implementation of the portal.
>
> Since we are not aware of anyone supporting the required infrastructure (xdg-desktop-portal implementations), we cannot make any claims to support nvidia.
>
> If anyone wants to open a bug relating to nvidia on wayland please provide a link to a bug opened against your compositor or xdg-desktop-portal implementation where they claim the issue is in OBS first.

I asked in the discord channel and they said:

> every compositor (the 3 main ones: GNOME, KDE, wlroots) would need to officially support nvidia on wayland for us to consider officially supporting it.
> and of course officially support xdg-desktop-portal on wayland on nvidia as well.
> And that support would need to be for gpu buffer capture as well.

Since my knowledge of the compositor/driver/desktop stack is very limited I wonder, is this the place to open this issue? Is `xdg-desktop-portal` missing "support for buffer negotiation" or "support for gpu buffer capture"?

**Comment by jadahl** [comment]
xdg-desktop-portal itself is not involved in any buffer transfer between applications and screen cast sources / compositors, it only sets up the PipeWire stream itself. Actual buffer allocation/transfer/.. happen elsewhere.

**Comment by Peque** [comment]
@jadahl Thanks for your reply. Could you point me to the right project/repository to report this issue then?

**Comment by jadahl** [comment]
> Could you point me to the right project/repository to report this issue then?

With nvidia supporting gbm for buffer allocation with recent drivers, ideally nothing should be needed in the PipeWire source nor the application, but if it isn't I suggest opening a bug on the component that handles buffer allocation, and see if the issue is there, or if it is in the driver itself. What component that is depends on what desktop environment you're using.

**Comment by Peque** [comment]
@jadahl I'm using GNOME/Mutter. Should I report it here then? https://gitlab.gnome.org/GNOME/mutter

**Comment by jadahl** [comment]
> Should I report it here then?

Sure.

**Comment by Peque** [comment]
Thanks! :blush:

**Comment by Peque** [comment]
In case anybody wants to share more information/details or simply track this issue: https://gitlab.gnome.org/GNOME/mutter/-/issues/2532
