### ISSUE TITLE
Configure portals folder

### ISSUE THREAD

**Issue by 875d** [flatpak/xdg-desktop-portal#927]
How can I configure the folders in which `xdg-desktop-portal` looks for portals?

I'm trying to install for example [xdg-desktop-portal-hyprland](https://github.com/hyprwm/xdg-desktop-portal-hyprland) and [xdg-desktop-portal-termfilechooser](https://github.com/GermainZ/xdg-desktop-portal-termfilechooser), but the portals get installed in `/usr/local/share/xdg-desktop-portal/portals` and `xdg-desktop-portal` seems to read only from `/usr/share/xdg-desktop-portal/portals`

Related #804

**Comment by rusty-snake** [comment]
Looking at the code, you can set `export XDG_DESKTOP_PORTAL_DIR=/usr/local/share/xdg-desktop-portal` to load portals from there, only from there. So to load portals from e.g. `/usr/share/xdg-desktop-portal` too you need to symlink I guess.

https://github.com/flatpak/xdg-desktop-portal/blob/43586c563333b4d9e9269ee7341be911e69efe69/src/portal-impl.c#L160-L162

**Comment by vaxerski** [comment]
> `xdg-desktop-portal` seems to read only from `/usr/share/xdg-desktop-portal/portals`

In the meantime, a fix for that is to do what xdph tells you to do for building:

![image](https://user-images.githubusercontent.com/43317083/206327736-e7577428-cf1b-4444-8fd5-a34d95700dd9.png)

Will make the resulting binary after installing in `/usr/share` and not `/usr/local`

**Comment by 875d** [comment]
> > `xdg-desktop-portal` seems to read only from `/usr/share/xdg-desktop-portal/portals`
> 
> In the meantime, a fix for that is to do what xdph tells you to do for building:
> 
> ![image](https://user-images.githubusercontent.com/43317083/206327736-e7577428-cf1b-4444-8fd5-a34d95700dd9.png)
> 
> Will make the resulting binary after installing in `/usr/share...` and not `/usr/local...`

I find this is not sufficient, as apparently `xdg-desktop-portal` look for the actual portals only under `/usr/lib` and not in `/usr/libexec`. 

So I also need `--libexecdir=lib`.

**Comment by GeorgesStavracas** [comment]
Not really a bug - like everything else in the platform, it'll read from the prefix it was configured to. So you should either configure your custom built portals to `/usr` instead of `/usr/share`, or set `XDG_DESKTOP_PORTAL_DIR`.

**Comment by 875d** [comment]
> Not really a bug - like everything else in the platform, it'll read from the prefix it was configured to. So you should either configure your custom built portals to `/usr` instead of `/usr/share`, or set `XDG_DESKTOP_PORTAL_DIR`.

You mean `/usr` instead of `/usr/local`

**Comment by GeorgesStavracas** [comment]
Yes, that
