### ISSUE TITLE
Support for generic sandbox environments

### ISSUE THREAD

**Issue by valoq** [flatpak/xdg-desktop-portal#930]
Currently, xdg-portals supports only three kinds of applications: Flatpak, Snap and unsandboxed apps.
https://github.com/flatpak/xdg-desktop-portal/blob/main/src/xdp-utils.h#L49

For any use cases that would try to use xdg-portals in other sandboxed environments, a generic XdpAppInfoKind would be useful.
This could be used in the context of a self sandboxing application using namespaces or landlock as well as possibly new container frameworks that would benefit from using portals.

At the moment, any sandboxed process that uses xdg-desktop-portal without running in flatpak or snap context, will be treated as unsandboxed and fail to use the portal like described here: #928

Could we introduce a new type like XDP_APP_INFO_KIND_GENERIC into portals to add support for these use cases?

**Comment by rusty-snake** [comment]
Also related discussion in #741.

I think the biggest problem to solve is to reliable identify a process as sandboxed.

**Comment by GeorgesStavracas** [comment]
I don't think this issue is actionable. It essentially suggests "support everything", which is essentially neither a goal nor a feature. There's a lot of complications and particularities from other sandboxing mechanisms that may require changing *them* to work with portals first. Each one will be an endeavour of its own, and won't happen unless really motivated people sit down and put serious thought and work on it.

**Comment by valoq** [comment]
> I don't think this issue is actionable. It essentially suggests "support everything", which is essentially neither a goal nor a feature. 

No, it suggests to define a specific way for sandboxed applications to use portals, which is the core goal and feature of xdg if Im not mistaken. Having different specification for flatpak and snaps seems already strange and after looking into related code at GTK and QT it becomes quite apparent how much of a mess this is already. E.g. GTK checks /.flatpak-info to determine internally whether to use the portals API or not, while QT checks for /run/user/UID/flatpak-info. 
If only there was a specification for interoperability between different desktop environments to determine this...

Ideally XdpAppInfoKind should only contain two types:
XDP_APP_INFO_KIND_HOST
and
XDP_APP_INFO_KIND_SANDBOXED (to be used for flatpak, snap and possibly other sandboxing frameworks)

> There's a lot of complications and particularities from other sandboxing mechanisms that may require changing _them_ to work with portals first. Each one will be an endeavour of its own, and won't happen unless really motivated people sit down and put serious thought and work on it.

There is no reason why every new framework has to reinvent this again, especially since xdg is in the position to define a standard.

If standardization and interoperability for desktop environments is not an objective of the xdg project, then I would suggest to change the README as well, since right now it appears to imply that is it intended to be used as a standard for apps independent of their environment.

**Comment by alxpettit** [comment]
What we need is to develop a standard, and have codebases like xdg-desktop-portal support _all_ systems that are compliant with that standard. Saying that it's ridiculous to support 'all sandboxing mechanisms' is like saying it's ridiculous to support 'all servers'. Yet somehow, your web browser does not care what kind of server is running on the other end. :P
