### ISSUE TITLE
xdg-desktop-portal version 1.6.0-1ubuntu2 grossly increases CPU usage and spams syslog with errors

### ISSUE THREAD

**Issue by Organic-Marble** [flatpak/xdg-desktop-portal#933]
I got xdg-desktop-portal version 1.6.0-1ubuntu2 through the normal update process on my Ubuntu MATE 20.04 computer. Next login, my CPU usage was 25% higher than normal and my syslog started exploding. Unfortunately in the same update I got a new kernel and new video drivers, so the culprit was not immediately apparent. I did a timeshift restore to before the update and installed the updates one by one. It was clear that the culprit was xdg-desktop-portal. I downgraded it to version 1.6.0-1 and pinned that version, and the problem went away.

Unfortunately the timeshift restore wiped out the logs showing the problem. And other Ubuntu MATE systems in the house are not showing this problem. The most frequent of the syslog errors were related to caja plugins.

**Comment by smcv** [comment]
Version 1.6.x is no longer supported upstream, and in any case this project does not provide support for the modifications made to it by Ubuntu. Please report this to Ubuntu's issue tracking system as a problem with the changes between 1.6.0-1 and 1.6.0-1ubuntu2.
