### ISSUE TITLE
Randomly reproducible crash in xdg-permission-store

### ISSUE THREAD

**Issue by rredford** [flatpak/xdg-desktop-portal#934]
Once a while somehow it causes notification access denied error, then it causes kernel to crash and reboot system. I'm not sure how to fix this.

Dec 17 15:10:22 rolfmint kernel: [337217.141086] xdg-permission-[313081]: segfault at 10000 ip 00007f13b621462d sp 00007ffd3ed060d0 error 4 in libglib-2.0.so.0.6400.6[7f13b61c0000+84000]
Dec 17 15:10:22 rolfmint kernel: [337217.141098] Code: 04 4c 8b 3b 8d 48 ff 48 89 c5 49 89 ce 49 c1 e6 04 4d 01 f7 4d 8b 27 4d 85 e4 0f 84 cd 00 00 00 49 8b 44 24 08 48 85 c0 74 43 <48> 8b 10 49 89 54 24 08 49 89 c4 49 8b 47 08 48 85 c0 74 08 48 83
Dec 17 15:10:22 rolfmint systemd[1]: Started Process Core Dump (PID 316965/UID 0).
Dec 17 15:10:22 rolfmint systemd[1471]: xdg-permission-store.service: Main process exited, code=dumped, status=11/SEGV
Dec 17 15:10:22 rolfmint systemd[1471]: xdg-permission-store.service: Failed with result 'core-dump'.
Dec 17 15:10:22 rolfmint xdg-desktop-por[2211]: Unable to retrieve info for 'x-scheme-handler/https' in the desktop-used-apps table of the permission store: Message recipient disconnected from message bus without replying
Dec 17 15:10:22 rolfmint systemd-coredump[316966]: Process 313081 (xdg-permission-) of user 1000 dumped core.#012#012Stack trace of thread 313081:#012#0  0x00007f13b621462d g_slice_alloc (libglib-2.0.so.0 + 0x7062d)#012#1  0x00007f13b621551a g_slist_prepend (libglib-2.0.so.0 + 0x7151a)#012#2  0x00007f13b62e669c n/a (libgobject-2.0.so.0 + 0x1969c)#012#3  0x00007f13b62e76b8 n/a (libgobject-2.0.so.0 + 0x1a6b8)#012#4  0x00007f13b62e9378 g_object_new_valist (libgobject-2.0.so.0 + 0x1c378)#012#5  0x00007f13b63aabee g_initable_new_valist (libgio-2.0.so.0 + 0x7dbee)#012#6  0x00007f13b63aacbd g_initable_new (libgio-2.0.so.0 + 0x7dcbd)#012#7  0x0000557f0c0bf2b8 n/a (xdg-permission-store + 0x102b8)#012#8  0x0000557f0c0bd5b7 n/a (xdg-permission-store + 0xe5b7)#012#9  0x0000557f0c0bd7d3 n/a (xdg-permission-store + 0xe7d3)#012#10 0x00007f13b5eb6ff5 n/a (libffi.so.7 + 0x6ff5)#012#11 0x00007f13b5eb640a n/a (libffi.so.7 + 0x640a)#012#12 0x00007f13b62e230d g_cclosure_marshal_generic (libgobject-2.0.so.0 + 0x1530d)#012#13 0x00007f13b62e1802 g_closure_invoke (libgobject-2.0.so.0 + 0x14802)#012#14 0x00007f13b62f5814 n/a (libgobject-2.0.so.0 + 0x28814)#012#15 0x00007f13b62ffa57 g_signal_emitv (libgobject-2.0.so.0 + 0x32a57)#012#16 0x0000557f0c0c432c n/a (xdg-permission-store + 0x1532c)#012#17 0x00007f13b645509a n/a (libgio-2.0.so.0 + 0x12809a)#012#18 0x00007f13b643ba24 n/a (libgio-2.0.so.0 + 0x10ea24)#012#19 0x00007f13b61f604e g_main_context_dispatch (libglib-2.0.so.0 + 0x5204e)#012#20 0x00007f13b61f6400 n/a (libglib-2.0.so.0 + 0x52400)#012#21 0x00007f13b61f66f3 g_main_loop_run (libglib-2.0.so.0 + 0x526f3)#012#22 0x0000557f0c0b9b2f n/a (xdg-permission-store + 0xab2f)#012#23 0x00007f13b5fb3083 __libc_start_main (libc.so.6 + 0x24083)#012#24 0x0000557f0c0b9bfe n/a (xdg-permission-store + 0xabfe)#012#012Stack trace of thread 313082:#012#0  0x00007f13b60a199f __GI___poll (libc.so.6 + 0x11299f)#012#1  0x00007f13b61f636e n/a (libglib-2.0.so.0 + 0x5236e)#012#2  0x00007f13b61f64a3 g_main_context_iteration (libglib-2.0.so.0 + 0x524a3)#012#3  0x00007f13b61f64f1 n/a (libglib-2.0.so.0 + 0x524f1)#012#4  0x00007f13b621fad1 n/a (libglib-2.0.so.0 + 0x7bad1)#012#5  0x00007f13b6189609 start_thread (libpthread.so.0 + 0x8609)#012#6  0x00007f13b60ae133 __clone (libc.so.6 + 0x11f133)#012#012Stack trace of thread 313084:#012#0  0x00007f13b60a199f __GI___poll (libc.so.6 + 0x11299f)#012#1  0x00007f13b61f636e n/a (libglib-2.0.so.0 + 0x5236e)#012#2  0x00007f13b61f66f3 g_main_loop_run (libglib-2.0.so.0 + 0x526f3)#012#3  0x00007f13b644bf8a n/a (libgio-2.0.so.0 + 0x11ef8a)#012#4  0x00007f13b621fad1 n/a (libglib-2.0.so.0 + 0x7bad1)#012#5  0x00007f13b6189609 start_thread (libpthread.so.0 + 0x8609)#012#6  0x00007f13b60ae133 __clone (libc.so.6 + 0x11f133)
Dec 17 15:10:22 rolfmint systemd[1]: systemd-coredump@125-316965-0.service: Succeeded.

**Comment by smcv** [comment]
> ```
> Dec 17 15:10:22 rolfmint kernel: [337217.141086] xdg-permission-[313081]: segfault at 10000 ip 00007f13b621462d sp 00007ffd3ed060d0 error 4 in libglib-2.0.so.0.6400.6[7f13b61c0000+84000]
> ```

This is the kernel reporting a crash (a bug) in xdg-permission-store, part of xdg-desktop-portal. From the hostname and the GLib version there, I suspect this is an older version of x-d-p as packaged by Linux Mint, so please report this crash to them: it's possible that it is already fixed in upstream x-d-p.

The rest of the text you quoted is various system components recording and reporting more information about this crash.

> then it causes kernel to crash and reboot system

The kernel should not allow xdg-desktop-portal to do this, even if we wanted it to, so that would be a kernel bug.

**Comment by rredford** [comment]
It is, I updated kernel from 5.4 to 5.15 and it happened again, though much rarer now. Though permissions issue is flatpak side bug. Basically it is 2 bugs interacting that causes os to reboot. I reported it here so you guys can fix your side. :)

**Comment by GeorgesStavracas** [comment]
@rredford is this still reproducible on your end? Which version of xdg-desktop-portal are you running? Is this issue reproducible with the `main` branch?

**Comment by GeorgesStavracas** [comment]
Okay. Reboots now happening "fewer times" instead of "not at all" is outstanding evidence this was not a Flatpak or portal issue. Going to this close this then.
