### ISSUE TITLE
[Feature Request] Add a picture in picture portal

### ISSUE THREAD

**Issue by Etaash-mathamsetty** [flatpak/xdg-desktop-portal#935]
note: I am not a person who develops anything related to wayland or portals

I was thinking that it might be possible to create a picture in picture portal because nearly all compositors have this option easily available to the user (on gnome or kde, it's a right click menu). So I was thinking that it should be possible to just create a portal for this so that apps like firefox can play a picture in picture video without the user having to go and make the window an always on top window. 

I am not sure how a UI would look for this (maybe just a simple allow and deny prompt? And maybe with an additional checkbox to never ask again for this app?)

It would also help in trying to avoid waiting a long time for the wayland developers to make a protocol for this.

**Comment by Mikenux** [comment]
I test with Firefox 108.0.1 flatpak and rpm (Fedora Workstation 37).

In wayland. Firefox rpm here is wayland only, and I disabled "socket=11" for the flatpaked version. Result: PiP doesn't work in wayland. In the gnome-shell overview, a firefox window and the PiP window are shown.

However, Firefox flatpak with socket=x11 enabled, then PiP works. In the gnome-shell overview, only the Firefox window is shown.

**Comment by swick** [comment]
#612

https://gitlab.freedesktop.org/wayland/wayland-protocols/-/merge_requests/132

**Comment by Etaash-mathamsetty** [comment]
oh so this is a duplicate, I guess I will close this then
