### ISSUE TITLE
Possible typo in org.freedesktop.impl.portal.FileChooser SaveFiles method

### ISSUE THREAD

**Issue by A6GibKm** [flatpak/xdg-desktop-portal#938]
The [docs](https://flatpak.github.io/xdg-desktop-portal/index.html#gdbus-method-org-freedesktop-impl-portal-FileChooser.SaveFiles) state that the options vardict has a "handle_token s" key, but this is the only method of a impl that has this. Is this correct?

**Comment by GeorgesStavracas** [comment]
I think this was supposed to be:

```
IN o handle:

    Object path for the [org.freedesktop.impl.portal.Request](https://flatpak.github.io/xdg-desktop-portal/index.html#gdbus-interface-org-freedesktop-impl-portal-Request.top_of_page) object representing this call
```
