### ISSUE TITLE
email portal: email address validation is too strict

### ISSUE THREAD

**Issue by Nico264** [flatpak/xdg-desktop-portal#944]
The current email address validation regex [`^\w+([-+.]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$`](https://github.com/flatpak/xdg-desktop-portal/blob/d7cfc16a6dc11cb925116fe36c5ee23e7075849c/src/email.c#L121) is too strict.
It refuses all slightly esoteric (but valid) email addresses such as `some--address@example.com`.
It also refuses the mailbox format `Some Name <some.name@example.com>` which is required by [RFC2368](https://www.rfc-editor.org/rfc/rfc2368), the format referenced in the [API reference](https://docs.flatpak.org/en/latest/portal-api-reference.html#gdbus-method-org-freedesktop-portal-Email.ComposeEmail).

In my opinion validating addresses/mailboxes is best left to the email composer itself.
Would you accept a patch that removes the validation altogether?

Or if you insist on keeping the validation:
 * Should we follow [RFC2368](https://www.rfc-editor.org/rfc/rfc2368) and accept mailboxes, comments etc?
 * Should we instead follow [RFC6068](https://www.rfc-editor.org/rfc/rfc6068) which only allows plain email addresses?
 * Should we try and accept both?

**Comment by smcv** [comment]
I think the intention in this API is to accept only email addresses, but not arbitrary mailboxes, more like RFC 6068 than 2368. So not accepting `some--address@example.com` is a bug, but not accepting `Some Name <some.name@example.com>` is intentional.

However, note that the D-Bus API is defined in terms of email addresses, not `mailto:` URIs. The reference to RFC 2368 is at a different place in the call chain:

```
caller
  ^
  | D-Bus (o.fd.portal.Email.ComposeEmail) call includes addresses
  v
xdg-desktop-portal
  ^
  | D-Bus (o.fd.portal.impl.Email.ComposeEmail) call includes addresses
  v
a backend such as xdg-desktop-portal-gtk
  ^
  | command-line parameters or o.fd.Application.Open (call includes mailto: URL)
  v
some email client such as Thunderbird or Evolution
```

**Comment by Nico264** [comment]
> I think the intention in this API is to accept only email addresses, but not arbitrary mailboxes, more like RFC 6068 than 2368. So not accepting `some--address@example.com` is a bug, but not accepting `Some Name <some.name@example.com>` is intentional.

That means a Flatpaked app will not be able to open a mail composer to the fancy `Some Name <some.name@example.com>` when the same app outside Flatpak could…
Besides, “email address” has a fuzzy definition, [RFC5322](https://www.rfc-editor.org/rfc/rfc5322#section-3.4) goes as far as writing `address = mailbox / group`.

> In my opinion validating addresses/mailboxes is best left to the email composer itself.

I've taken a look at what some email clients allow or not (they all support `Name <user@example.com>`):
 * Thunderbird only displays a warning in some cases ([using `^[^\s@]+@[^\s@]+$`](https://hg.mozilla.org/comm-central/file/c3930d867b4a13b645aa73bdb4a4b816f3ec6314/mail/base/content/widgets/mailWidgets.js#l1266)), but [doesn't prevent the user from actually sending the email](https://bugzilla.mozilla.org/show_bug.cgi?id=1799390#c6).
 * KMail, via [KCodecs/KEmailAddress](https://invent.kde.org/frameworks/kcodecs/-/blob/b0afeb52145ab48e9b812ab5a12403149f080d2d/src/kemailaddress.cpp#L275), does some complicated validation to try and display an helpful error message and prevents sending the email.
 * Evolution checks if there is a `@` and that the local part is non-empty ([using `strchr (eml, '@') <= eml`](https://gitlab.gnome.org/GNOME/evolution/-/blob/3e591db85135cff1fa114c4bffc945131b2f986f/src/mail/em-composer-utils.c#L293)). Even then it only [displays a warning and lets the user continue](https://gitlab.gnome.org/GNOME/evolution/-/blob/master/src/mail/em-composer-utils.c#L372).

I don't think it makes sense to be stricter than actual email clients, and they are _very_ lenient.

**Comment by matthiasclasen** [comment]
I think it makes a lot of sense to be stricter.

**Comment by Nico264** [comment]
So you think it makes a lot of sense that I can't send an email to my friend firstname.family--name@example.com from Flatpak applications? (having double hyphenated names was common in France between 2005 and 2010)

If that's so then document it! This is part of the public API…
Or do you think it also makes a lot of sense for app developers to go and read the portal code to discover your unique and very restrictive regexp?

The least we could do is copy-paste the regexp from the [HTML Standard](https://html.spec.whatwg.org/multipage/input.html#email-state-(type=email)) and add in the docs:
> Email addresses should be valid according to the HTML specs: see link.

_That_ would actually make sense.
