### ISSUE TITLE
Disable "background activity" popups

### ISSUE THREAD

**Issue by MrPixel1** [flatpak/xdg-desktop-portal#947]
On various occasions, popups like these will appear:

![grafik](https://user-images.githubusercontent.com/16743943/212127753-83f48f2b-4ee9-4d00-9b49-c2fb75151813.png)

They don't just appear when there is background activity, they will appear when opening certain applications in the foreground (e.g. Steam), or when closing foreground applications (e.g. Lutris).

Even if they did only appear when there's background activity, it'd still be... weird and user-unfriendly. To my knowledge, no other OS shows a popup as soon as *something* happens in the background.

I'm not quite certain if this is a bug or a feature, but IMHO, it should be disabled, or at the very least configurable (in which case it should be disabled by default until it works as intended).

**Comment by herzenschein** [comment]
That is the bug: applications trigger this despite being in the foreground.

https://bugs.kde.org/show_bug.cgi?id=420529

**Comment by GeorgesStavracas** [comment]
This shouldn't happen anymore after last year's rework of the background portal
