### ISSUE TITLE
Portal leaks geolocation

### ISSUE THREAD

**Issue by JoseskVolpe** [flatpak/xdg-desktop-portal#958]
When denying access to a Flatpak application to use geolocation, it can still obtain it by using the API.
https://www.youtube.com/watch?v=-700IPl_qvE

I'm not sure it's the right place to post this bug, but since privacy permissions is managed by portal i'm attaching this issue here. 

Steps to reproduce:
* Install Firefox from Flatpak
* Use a new profile
* Access: https://browserleaks.com/geo
* Allow the use of geolocation if the browser asks it
* Deny access to geolocation when portal asks it

System settings:
* Kernel: Linux 5.15.89-1-lts x86_64
* Operating system: Arch Linux
* Desktop environment: KDE Plasma 5.26.5
* Graphics platform: Wayland
* Audio server: PipeWire 0.3.64
* xdg-desktop-portal version: 1.16.0
* Firefox 109.0 (64-Bits)
* geoclue 2.6.0
* Flatpak 1.15.1

**Comment by smcv** [comment]
Is the browser definitely getting geolocation from the portal and Geoclue, as opposed to doing IP-address-based geolocation directly, or talking to Geoclue directly? (`dbus-monitor --session` and `sudo dbus-monitor --system` might give some hints about what is going on.)

Flatpak cannot prevent applications from doing IP-address-based geolocation, it can only prevent them from contacting Geoclue (other than via the portal).

Similarly, the portal only has control over what it does with requests that are sent via the portal. If an application does its own IP-address-based geolocation, or if it has permission to talk to Geoclue directly, then there is nothing that the portal can do about that.

**Comment by JoseskVolpe** [comment]
My IP-Address don't return my precise location, only the state i live on, but the location Firefox is being able to get is my precise location and in real-time, so i think that indicates it's being exposed to the API.

I'll look into it and send the dbus-monitor log soon.

**Comment by codicodi** [comment]
I'm pretty sure Firefox has its own geolocation engine. 
You may be able to restrict it by revoking dbus access to NetworkManager.

**Comment by rusty-snake** [comment]
FTR To restrict Firefox' build-in geolocation you need to revoke network permission.

**Comment by JoseskVolpe** [comment]
By checking dbus-monitor logs, Firefox tries to call Geoclue, wich is denied, then NetworkManager dbus is called many times checking the available WiFi frequencies, then precise location is prompted by browserleaks.
By revoking access to org.freedesktop.NetworkManager dbus, the browser is now unable to get precise location and use IP Address location, wich returns a inaccurate value.

An unwarnned user would think that disabling location is sufficient to protect it, but still an app could use other dbus-es wich would be enabled by default. Portal permissions is not finished yet, ¿so is it planned to integrate special dbus-es (such as NetworkManager) into the permission settings in the future?

**Comment by swick** [comment]
The right thing to do here is to remove access to NetworkManager for Firefox but it probably currently has access for a reason. So, one has to figure out what that reason is and how to satisfy it with portals or other sandbox-friendly means.

**Comment by mcatanzaro** [comment]
This should be closed. It's a Firefox problem, not a portal bug.

Applications that grant themselves static permissions that allow them to bypass other permissions will always succeed at that.

**Comment by jadahl** [comment]
Closing as per above comment.
