### ISSUE TITLE
Duplicate names with multi-monitor setup

### ISSUE THREAD

**Issue by szszoke** [flatpak/xdg-desktop-portal#959]
I have a multi-monitor setup with two displays from `Acer`. Whenever I try to share my screen, the two displays have the exact same name.

![image](https://user-images.githubusercontent.com/2766129/214834111-27fa64fe-7d74-4e5b-a062-48eb3ecca361.png)

Is there a way to avoid this situation and show more descriptive names?

Where are these names coming from? Maybe they can be renamed there?

**Comment by GeorgesStavracas** [comment]
This is an issue inhttps://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/, could you please file it there? Thanks

**Comment by szszoke** [comment]
Someone beat me to it: https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/issues/9
