### ISSUE TITLE
GlobalShortcuts docs are missing a description

### ISSUE THREAD

**Issue by allanday** [flatpak/xdg-desktop-portal#971]
Looking at the API docs for the GlobalShortcuts portal, it's a bit sparse on details:

https://flatpak.github.io/xdg-desktop-portal/#gdbus-org.freedesktop.portal.GlobalShortcuts

The name is just `org.freedesktop.portal.GlobalShortcuts`. The other portals have more descriptive names, like `org.freedesktop.portal.Notification — Portal for sending notifications` or `org.freedesktop.portal.Screenshot — Portal for taking screenshots`.

The description section also seems to be empty:

![image](https://user-images.githubusercontent.com/213068/220951382-4711be45-4ecf-4bb7-8934-697aaab9ce83.png)

**Comment by GeorgesStavracas** [comment]
@aleixpol check this out

**Comment by jokeyrhyme** [comment]
Relatedly, I don't quite understand what Activated and Deactivated means in this context

Are these key-pressed and key-released?

Or do they refer to the bindings themselves: e.g. Activated means future key presses will be forwarded? And Deactivated means future key presses will not be forwarded?

Does the app receive the key press events directly from the compositor just as though the window had focus? Or does the app only receive these key press events via DBus here?

**Comment by aleixpol** [comment]
@jokeyrhyme please don't hijack an issue for something completely different. Please open a separate issue for that, feel free to include me by name.

**Comment by GeorgesStavracas** [comment]
This seems to work now that we moved to Sphinx: https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.portal.GlobalShortcuts.html
