### ISSUE TITLE
FIDO2 Portal Proposal

### ISSUE THREAD

**Issue by ItsJamie9494** [flatpak/xdg-desktop-portal#987]
# Proposal

Create a portal that provides access to libfido2, for authentication and security, throughout the sandbox. This could be used for allowing applications like Epiphany to have access to FIDO2-compatible hardware keys, while not exposing too much access to the system; as well as guaranteeing that all apps using hardware keys are secure.

One idea of how to implement this is to create a D-Bus service (fido2-proxy, for example) that acts as a frontend for libfido2, and the portal would consume this D-Bus service.

# Existing Implementations and Specifications

- https://github.com/AlfioEmanueleFresta/xdg-credentials-portal
A Rust-based FIDO2 and FIDO2 UTF library, along with a sample Portal specification
- https://gitlab.freedesktop.org/dueno/fido2-proxy
A D-Bus service providing libfido2 access

**Comment by jadahl** [comment]
Related: https://github.com/flatpak/flatpak/issues/2764

**Comment by GeorgesStavracas** [comment]
Duplicate of https://github.com/flatpak/xdg-desktop-portal/issues/989
