### ISSUE TITLE
Add `lang` attribute in `html` element

### ISSUE THREAD

**Issue by TheEvilSkeleton** [flatpak/xdg-desktop-portal#988]
W3schools recommends to ALWAYS use `lang` https://www.w3schools.com/tags/ref_language_codes.asp

In https://flatpak.github.io/xdg-desktop-portal, the HTML starts with:

```html
<html xmlns="http://www.w3.org/1999/xhtml">
```

**Comment by smcv** [comment]
The only non-generated HTML is `doc/redirect.html` which is completely trivial and shouldn't ever be seen for more than a moment (merge requests welcome for that).

HTML that's generated by a tool is not directly fixable within this project. `portal-docs.html` is generated by xmlto, which I believe uses the Docbook XSL stylesheets.

(Also, please copy/paste text in preference to pictures of text, especially if you're interested in accessibility on the web.)

**Comment by GeorgesStavracas** [comment]
The new doc framework (Sphinx) seems to generate pages with the `lang` attribute:

![Captura de tela de 2023-11-20 18-12-30](https://github.com/flatpak/xdg-desktop-portal/assets/3518204/4e4d2ad9-f733-4a49-b819-f6a082d38e0e)
