### ISSUE TITLE
File kept busy by portal process

### ISSUE THREAD

**Issue by BillDietrich** [flatpak/xdg-desktop-portal#994]
When using Flatpak of an app, and portals, I use some file X, then I quit from the app, try to dismount the disk or USB stick or LUKS container that file X resides on, and get a "can't unmount because busy" error.  I do something like:

    lsof -c xdg | grep REG | grep -v -E '/usr|/var|/run|/SYSV|/memfd'

and find out that a portal process still has file X open.  I have to kill the process to be able to unmount the drive.

Before you say this is an app bug, go file against the app, I've seen it in multiple apps and distros and DEs, which leads me to think perhaps the portal specification or guidance or API maybe is lacking in this area.  Is there a way for an app to tell the portal process to let go of the file ?  Is this advertised to app developers ?  Today the UX of the overall system can be bad because of this issue.  What can be done to improve it ?  Thanks.

**Comment by rusty-snake** [comment]
Duplicated oft #689 and all its duplicates.

**Comment by BillDietrich** [comment]
Maybe some portal API change is needed ?  Something to say "no longer using file X" ?
