### ISSUE TITLE
xdg-desktop-portal-gnome times out under KDE

### ISSUE THREAD

**Issue by agriffis** [flatpak/xdg-desktop-portal#998]
I'm running KDE on Fedora 38. Applications are taking about 45 seconds to start, and when I look at my journal, I see:

```
Apr 05 09:10:25 jasperodus systemd[1975]: Starting xdg-desktop-portal.service - Portal service...
Apr 05 09:10:25 jasperodus systemd[1975]: Starting xdg-desktop-portal-gnome.service - Portal service (GNOME implementation)...
Apr 05 09:11:11 jasperodus systemd[1975]: xdg-desktop-portal.service: start operation timed out. Terminating.
Apr 05 09:11:11 jasperodus systemd[1975]: xdg-desktop-portal-gnome.service: start operation timed out. Terminating.
Apr 05 09:11:11 jasperodus systemd[1975]: xdg-desktop-portal.service: Failed with result 'timeout'.
Apr 05 09:11:11 jasperodus systemd[1975]: Failed to start xdg-desktop-portal.service - Portal service.
Apr 05 09:11:11 jasperodus systemd[1975]: xdg-desktop-portal-gnome.service: Failed with result 'timeout'.
Apr 05 09:11:11 jasperodus systemd[1975]: Failed to start xdg-desktop-portal-gnome.service - Portal service (GNOME implementation).
Apr 05 09:11:11 jasperodus plasmashell[10659]: (obsidian:13): Gdk-WARNING **: 09:11:11.147: Failed to read portal settings: GDBus.Error:org.freedesktop.DBus.Error.NameHasNoOwner: Could not activate remote peer: startup job failed.
```

I tried a couple things, like `strace /usr/libexec/xdg-desktop-portal-gnome`, but it's not obvious what's going wrong, and I'm not sure what to look for. 

Here is what I see for versions:

```
✸ rpm -qa | grep xdg-desktop-portal
xdg-desktop-portal-1.16.0-2.fc38.x86_64
xdg-desktop-portal-gtk-1.14.1-2.fc38.x86_64
xdg-desktop-portal-wlr-0.6.0-4.fc38.x86_64
xdg-desktop-portal-gnome-44~rc-1.fc38.x86_64
xdg-desktop-portal-kde-5.27.3-1.fc38.x86_64
```

**Comment by jadahl** [comment]
The delay should be fixed by https://gitlab.gnome.org/GNOME/xdg-desktop-portal-gnome/-/merge_requests/78.

But it needs https://github.com/flatpak/xdg-desktop-portal/pull/985.

**Comment by agriffis** [comment]
Thank you @jadahl 

I moved aside some of the portal files to restore usability of my system:

```
✸ ls -l /usr/share/xdg-desktop-portal/*
total 24K
-rw-r--r-- 1 root root 100 Jun  1  2020 gnome-keyring.portal.NOPE
-rw-r--r-- 1 root root  99 Mar 19 06:58 gnome-shell.portal.NOPE
-rw-r--r-- 1 root root 548 Mar  6 19:00 gnome.portal.NOPE
-rw-r--r-- 1 root root 458 Jan 20 19:00 gtk.portal
-rw-r--r-- 1 root root 658 Mar 13 20:00 kde.portal
-rw-r--r-- 1 root root 188 Jun  9  2022 wlr.portal
```

However I'm wondering, is this misbehavior the result of a configuration on my part, or something that changed recently in the code? I was using GNOME previously and I've been experimenting with KDE, but I can't imagine that all KDE users are putting up with this timeout. What's different between normal setups and mine?

**Comment by jadahl** [comment]
It's not your configuration, it was code in `xdg-desktop-portal-gnome` that waited for the display server to show up, forgetting that `UseIn` is conveniently ignored by `xdg-desktop-portal`. The fix is to change the waiting to be systemd based, and only apply when autostarted, and the fix in `xdg-desktop-portal` is to not always assume a portal backend with `UseIn` ignored will actually work.
